package moe.brianhsu.live2d.adapter.gateway.avatar.motion

import moe.brianhsu.live2d.adapter.gateway.avatar.settings.json.JsonSettingsReader
import moe.brianhsu.live2d.enitiy.avatar.motion.data.CurveTarget.{Model, Parameter, PartOpacity}
import moe.brianhsu.live2d.enitiy.avatar.motion.data.SegmentType._
import moe.brianhsu.live2d.enitiy.avatar.motion.data.{MotionCurve, MotionPoint, MotionSegment}
import moe.brianhsu.live2d.enitiy.avatar.settings.Settings
import org.scalatest.featurespec.AnyFeatureSpec
import org.scalatest.matchers.should.Matchers
import org.scalatest.{GivenWhenThen, TryValues}

import scala.io.Source
import scala.util.Using

class AvatarMotionDataReaderFeature extends AnyFeatureSpec with GivenWhenThen with Matchers with TryValues {
  Feature("Read pose parts data from Live2D avatar settings") {

    Scenario("Load motion idle[0] from avatar Mark") {
      Given("A folder path contains json files for a Live2D avatar model")
      val folderPath = "src/test/resources/models/Mark"

      When("Create a MotionData from this Live2D avatar settings")
      val jsonSettingsReader = new JsonSettingsReader(folderPath)
      val settings: Settings = jsonSettingsReader.loadSettings().success.value
      val motionData = new AvatarMotionDataReader(settings.motionGroups("idle")(0)).loadMotionData()

      motionData.fps shouldBe 30.0
      motionData.isLoop shouldBe true
      motionData.curveCount shouldBe 37
      motionData.duration shouldBe 10.4f
      val curves = motionData.curvesList
      curves.size shouldBe 37
      curves(0) shouldBe MotionCurve("Opacity", Model, 1, 0, -1.0f, -1.0f)
      curves(1) shouldBe MotionCurve("EyeBlink", Model, 9, 1, -1.0f, -1.0f)
      curves(2) shouldBe MotionCurve("ParamAngleX", Parameter, 16, 10, -1.0f, -1.0f)
      curves(3) shouldBe MotionCurve("ParamAngleY", Parameter, 32, 26, -1.0f, -1.0f)
      curves(4) shouldBe MotionCurve("ParamAngleZ", Parameter, 17, 58, -1.0f, -1.0f)
      curves(5) shouldBe MotionCurve("ParamEyeBallX", Parameter, 21, 75, -1.0f, -1.0f)
      curves(6) shouldBe MotionCurve("ParamEyeBallY", Parameter, 21, 96, -1.0f, -1.0f)
      curves(7) shouldBe MotionCurve("ParamBrowLY", Parameter, 16, 117, -1.0f, -1.0f)
      curves(8) shouldBe MotionCurve("ParamBrowRY", Parameter, 16, 133, -1.0f, -1.0f)
      curves(9) shouldBe MotionCurve("ParamMouthOpenY", Parameter, 16, 149, -1.0f, -1.0f)
      curves(10) shouldBe MotionCurve("ParamArmL", Parameter, 32, 165, -1.0f, -1.0f)
      curves(11) shouldBe MotionCurve("ParamArmR", Parameter, 32, 197, -1.0f, -1.0f)
      curves(12) shouldBe MotionCurve("ParamLeftLeg", Parameter, 16, 229, -1.0f, -1.0f)
      curves(13) shouldBe MotionCurve("ParamRightLeg", Parameter, 16, 245, -1.0f, -1.0f)
      curves(14) shouldBe MotionCurve("ParamBodyAngleX", Parameter, 16, 261, -1.0f, -1.0f)
      curves(15) shouldBe MotionCurve("ParamBodyAngleY", Parameter, 32, 277, -1.0f, -1.0f)
      curves(16) shouldBe MotionCurve("ParamBodyAngleZ", Parameter, 16, 309, -1.0f, -1.0f)
      curves(17) shouldBe MotionCurve("ParamBreath", Parameter, 16, 325, -1.0f, -1.0f)
      curves(18) shouldBe MotionCurve("ParamHairFront", Parameter, 16, 341, -1.0f, -1.0f)
      curves(19) shouldBe MotionCurve("ParamHairSide", Parameter, 16, 357, -1.0f, -1.0f)
      curves(20) shouldBe MotionCurve("ParamHairBack", Parameter, 16, 373, -1.0f, -1.0f)
      curves(21) shouldBe MotionCurve("PartHead", PartOpacity, 1, 389, -1.0f, -1.0f)
      curves(22) shouldBe MotionCurve("PartHairFront", PartOpacity, 1, 390, -1.0f, -1.0f)
      curves(23) shouldBe MotionCurve("PartEyeL", PartOpacity, 1, 391, -1.0f, -1.0f)
      curves(24) shouldBe MotionCurve("PartEyeBallL", PartOpacity, 1, 392, -1.0f, -1.0f)
      curves(25) shouldBe MotionCurve("PartEyeWhiteL", PartOpacity, 1, 393, -1.0f, -1.0f)
      curves(26) shouldBe MotionCurve("PartEyeR", PartOpacity, 1, 394, -1.0f, -1.0f)
      curves(27) shouldBe MotionCurve("PartEyeBallR", PartOpacity, 1, 395, -1.0f, -1.0f)
      curves(28) shouldBe MotionCurve("PartEyeWhiteR", PartOpacity, 1, 396, -1.0f, -1.0f)
      curves(29) shouldBe MotionCurve("PartHairSide", PartOpacity, 1, 397, -1.0f, -1.0f)
      curves(30) shouldBe MotionCurve("PartMouth", PartOpacity, 1, 398, -1.0f, -1.0f)
      curves(31) shouldBe MotionCurve("PartOral", PartOpacity, 1, 399, -1.0f, -1.0f)
      curves(32) shouldBe MotionCurve("PartFace", PartOpacity, 1, 400, -1.0f, -1.0f)
      curves(33) shouldBe MotionCurve("PartBody", PartOpacity, 1, 401, -1.0f, -1.0f)
      curves(34) shouldBe MotionCurve("PartArmL", PartOpacity, 1, 402, -1.0f, -1.0f)
      curves(35) shouldBe MotionCurve("PartArmR", PartOpacity, 1, 403, -1.0f, -1.0f)
      curves(36) shouldBe MotionCurve("PartHairBack", PartOpacity, 1, 404, -1.0f, -1.0f)

      val segments = motionData.segmentsList
      segments.size shouldBe 405
      segments(0) shouldBe MotionSegment(Linear, 0)
      segments(1) shouldBe MotionSegment(Bezier, 2)
      segments(2) shouldBe MotionSegment(Bezier, 5)
      segments(3) shouldBe MotionSegment(Bezier, 8)
      segments(4) shouldBe MotionSegment(Bezier, 11)
      segments(5) shouldBe MotionSegment(Bezier, 14)
      segments(6) shouldBe MotionSegment(Bezier, 17)
      segments(7) shouldBe MotionSegment(Bezier, 20)
      segments(8) shouldBe MotionSegment(Bezier, 23)
      segments(9) shouldBe MotionSegment(Linear, 26)
      segments(10) shouldBe MotionSegment(Bezier, 28)
      segments(11) shouldBe MotionSegment(Bezier, 31)
      segments(12) shouldBe MotionSegment(Bezier, 34)
      segments(13) shouldBe MotionSegment(Bezier, 37)
      segments(14) shouldBe MotionSegment(Bezier, 40)
      segments(15) shouldBe MotionSegment(Bezier, 43)
      segments(16) shouldBe MotionSegment(Bezier, 46)
      segments(17) shouldBe MotionSegment(Bezier, 49)
      segments(18) shouldBe MotionSegment(Bezier, 52)
      segments(19) shouldBe MotionSegment(Bezier, 55)
      segments(20) shouldBe MotionSegment(Bezier, 58)
      segments(21) shouldBe MotionSegment(Bezier, 61)
      segments(22) shouldBe MotionSegment(Bezier, 64)
      segments(23) shouldBe MotionSegment(Bezier, 67)
      segments(24) shouldBe MotionSegment(Bezier, 70)
      segments(25) shouldBe MotionSegment(Bezier, 73)
      segments(26) shouldBe MotionSegment(Bezier, 77)
      segments(27) shouldBe MotionSegment(Bezier, 80)
      segments(28) shouldBe MotionSegment(Bezier, 83)
      segments(29) shouldBe MotionSegment(Bezier, 86)
      segments(30) shouldBe MotionSegment(Bezier, 89)
      segments(31) shouldBe MotionSegment(Bezier, 92)
      segments(32) shouldBe MotionSegment(Bezier, 95)
      segments(33) shouldBe MotionSegment(Bezier, 98)
      segments(34) shouldBe MotionSegment(Bezier, 101)
      segments(35) shouldBe MotionSegment(Bezier, 104)
      segments(36) shouldBe MotionSegment(Bezier, 107)
      segments(37) shouldBe MotionSegment(Bezier, 110)
      segments(38) shouldBe MotionSegment(Bezier, 113)
      segments(39) shouldBe MotionSegment(Bezier, 116)
      segments(40) shouldBe MotionSegment(Bezier, 119)
      segments(41) shouldBe MotionSegment(Bezier, 122)
      segments(42) shouldBe MotionSegment(Bezier, 125)
      segments(43) shouldBe MotionSegment(Bezier, 128)
      segments(44) shouldBe MotionSegment(Bezier, 131)
      segments(45) shouldBe MotionSegment(Bezier, 134)
      segments(46) shouldBe MotionSegment(Bezier, 137)
      segments(47) shouldBe MotionSegment(Bezier, 140)
      segments(48) shouldBe MotionSegment(Bezier, 143)
      segments(49) shouldBe MotionSegment(Bezier, 146)
      segments(50) shouldBe MotionSegment(Bezier, 149)
      segments(51) shouldBe MotionSegment(Bezier, 152)
      segments(52) shouldBe MotionSegment(Bezier, 155)
      segments(53) shouldBe MotionSegment(Bezier, 158)
      segments(54) shouldBe MotionSegment(Bezier, 161)
      segments(55) shouldBe MotionSegment(Bezier, 164)
      segments(56) shouldBe MotionSegment(Bezier, 167)
      segments(57) shouldBe MotionSegment(Bezier, 170)
      segments(58) shouldBe MotionSegment(Bezier, 174)
      segments(59) shouldBe MotionSegment(Bezier, 177)
      segments(60) shouldBe MotionSegment(Bezier, 180)
      segments(61) shouldBe MotionSegment(Bezier, 183)
      segments(62) shouldBe MotionSegment(Bezier, 186)
      segments(63) shouldBe MotionSegment(Bezier, 189)
      segments(64) shouldBe MotionSegment(Bezier, 192)
      segments(65) shouldBe MotionSegment(Bezier, 195)
      segments(66) shouldBe MotionSegment(Bezier, 198)
      segments(67) shouldBe MotionSegment(Bezier, 201)
      segments(68) shouldBe MotionSegment(Bezier, 204)
      segments(69) shouldBe MotionSegment(Bezier, 207)
      segments(70) shouldBe MotionSegment(Bezier, 210)
      segments(71) shouldBe MotionSegment(Bezier, 213)
      segments(72) shouldBe MotionSegment(Bezier, 216)
      segments(73) shouldBe MotionSegment(Bezier, 219)
      segments(74) shouldBe MotionSegment(Bezier, 222)
      segments(75) shouldBe MotionSegment(Bezier, 226)
      segments(76) shouldBe MotionSegment(Bezier, 229)
      segments(77) shouldBe MotionSegment(Bezier, 232)
      segments(78) shouldBe MotionSegment(Bezier, 235)
      segments(79) shouldBe MotionSegment(Bezier, 238)
      segments(80) shouldBe MotionSegment(Bezier, 241)
      segments(81) shouldBe MotionSegment(Bezier, 244)
      segments(82) shouldBe MotionSegment(Bezier, 247)
      segments(83) shouldBe MotionSegment(Bezier, 250)
      segments(84) shouldBe MotionSegment(Bezier, 253)
      segments(85) shouldBe MotionSegment(Bezier, 256)
      segments(86) shouldBe MotionSegment(Bezier, 259)
      segments(87) shouldBe MotionSegment(Bezier, 262)
      segments(88) shouldBe MotionSegment(Bezier, 265)
      segments(89) shouldBe MotionSegment(Bezier, 268)
      segments(90) shouldBe MotionSegment(Bezier, 271)
      segments(91) shouldBe MotionSegment(Bezier, 274)
      segments(92) shouldBe MotionSegment(Bezier, 277)
      segments(93) shouldBe MotionSegment(Bezier, 280)
      segments(94) shouldBe MotionSegment(Bezier, 283)
      segments(95) shouldBe MotionSegment(Bezier, 286)
      segments(96) shouldBe MotionSegment(Bezier, 290)
      segments(97) shouldBe MotionSegment(Bezier, 293)
      segments(98) shouldBe MotionSegment(Bezier, 296)
      segments(99) shouldBe MotionSegment(Bezier, 299)
      segments(100) shouldBe MotionSegment(Bezier, 302)
      segments(101) shouldBe MotionSegment(Bezier, 305)
      segments(102) shouldBe MotionSegment(Bezier, 308)
      segments(103) shouldBe MotionSegment(Bezier, 311)
      segments(104) shouldBe MotionSegment(Bezier, 314)
      segments(105) shouldBe MotionSegment(Bezier, 317)
      segments(106) shouldBe MotionSegment(Bezier, 320)
      segments(107) shouldBe MotionSegment(Bezier, 323)
      segments(108) shouldBe MotionSegment(Bezier, 326)
      segments(109) shouldBe MotionSegment(Bezier, 329)
      segments(110) shouldBe MotionSegment(Bezier, 332)
      segments(111) shouldBe MotionSegment(Bezier, 335)
      segments(112) shouldBe MotionSegment(Bezier, 338)
      segments(113) shouldBe MotionSegment(Bezier, 341)
      segments(114) shouldBe MotionSegment(Bezier, 344)
      segments(115) shouldBe MotionSegment(Bezier, 347)
      segments(116) shouldBe MotionSegment(Bezier, 350)
      segments(117) shouldBe MotionSegment(Bezier, 354)
      segments(118) shouldBe MotionSegment(Bezier, 357)
      segments(119) shouldBe MotionSegment(Bezier, 360)
      segments(120) shouldBe MotionSegment(Bezier, 363)
      segments(121) shouldBe MotionSegment(Bezier, 366)
      segments(122) shouldBe MotionSegment(Bezier, 369)
      segments(123) shouldBe MotionSegment(Bezier, 372)
      segments(124) shouldBe MotionSegment(Bezier, 375)
      segments(125) shouldBe MotionSegment(Bezier, 378)
      segments(126) shouldBe MotionSegment(Bezier, 381)
      segments(127) shouldBe MotionSegment(Bezier, 384)
      segments(128) shouldBe MotionSegment(Bezier, 387)
      segments(129) shouldBe MotionSegment(Bezier, 390)
      segments(130) shouldBe MotionSegment(Bezier, 393)
      segments(131) shouldBe MotionSegment(Bezier, 396)
      segments(132) shouldBe MotionSegment(Bezier, 399)
      segments(133) shouldBe MotionSegment(Bezier, 403)
      segments(134) shouldBe MotionSegment(Bezier, 406)
      segments(135) shouldBe MotionSegment(Bezier, 409)
      segments(136) shouldBe MotionSegment(Bezier, 412)
      segments(137) shouldBe MotionSegment(Bezier, 415)
      segments(138) shouldBe MotionSegment(Bezier, 418)
      segments(139) shouldBe MotionSegment(Bezier, 421)
      segments(140) shouldBe MotionSegment(Bezier, 424)
      segments(141) shouldBe MotionSegment(Bezier, 427)
      segments(142) shouldBe MotionSegment(Bezier, 430)
      segments(143) shouldBe MotionSegment(Bezier, 433)
      segments(144) shouldBe MotionSegment(Bezier, 436)
      segments(145) shouldBe MotionSegment(Bezier, 439)
      segments(146) shouldBe MotionSegment(Bezier, 442)
      segments(147) shouldBe MotionSegment(Bezier, 445)
      segments(148) shouldBe MotionSegment(Bezier, 448)
      segments(149) shouldBe MotionSegment(Bezier, 452)
      segments(150) shouldBe MotionSegment(Bezier, 455)
      segments(151) shouldBe MotionSegment(Bezier, 458)
      segments(152) shouldBe MotionSegment(Bezier, 461)
      segments(153) shouldBe MotionSegment(Bezier, 464)
      segments(154) shouldBe MotionSegment(Bezier, 467)
      segments(155) shouldBe MotionSegment(Bezier, 470)
      segments(156) shouldBe MotionSegment(Bezier, 473)
      segments(157) shouldBe MotionSegment(Bezier, 476)
      segments(158) shouldBe MotionSegment(Bezier, 479)
      segments(159) shouldBe MotionSegment(Bezier, 482)
      segments(160) shouldBe MotionSegment(Bezier, 485)
      segments(161) shouldBe MotionSegment(Bezier, 488)
      segments(162) shouldBe MotionSegment(Bezier, 491)
      segments(163) shouldBe MotionSegment(Bezier, 494)
      segments(164) shouldBe MotionSegment(Bezier, 497)
      segments(165) shouldBe MotionSegment(Bezier, 501)
      segments(166) shouldBe MotionSegment(Bezier, 504)
      segments(167) shouldBe MotionSegment(Bezier, 507)
      segments(168) shouldBe MotionSegment(Bezier, 510)
      segments(169) shouldBe MotionSegment(Bezier, 513)
      segments(170) shouldBe MotionSegment(Bezier, 516)
      segments(171) shouldBe MotionSegment(Bezier, 519)
      segments(172) shouldBe MotionSegment(Bezier, 522)
      segments(173) shouldBe MotionSegment(Bezier, 525)
      segments(174) shouldBe MotionSegment(Bezier, 528)
      segments(175) shouldBe MotionSegment(Bezier, 531)
      segments(176) shouldBe MotionSegment(Bezier, 534)
      segments(177) shouldBe MotionSegment(Bezier, 537)
      segments(178) shouldBe MotionSegment(Bezier, 540)
      segments(179) shouldBe MotionSegment(Bezier, 543)
      segments(180) shouldBe MotionSegment(Bezier, 546)
      segments(181) shouldBe MotionSegment(Bezier, 549)
      segments(182) shouldBe MotionSegment(Bezier, 552)
      segments(183) shouldBe MotionSegment(Bezier, 555)
      segments(184) shouldBe MotionSegment(Bezier, 558)
      segments(185) shouldBe MotionSegment(Bezier, 561)
      segments(186) shouldBe MotionSegment(Bezier, 564)
      segments(187) shouldBe MotionSegment(Bezier, 567)
      segments(188) shouldBe MotionSegment(Bezier, 570)
      segments(189) shouldBe MotionSegment(Bezier, 573)
      segments(190) shouldBe MotionSegment(Bezier, 576)
      segments(191) shouldBe MotionSegment(Bezier, 579)
      segments(192) shouldBe MotionSegment(Bezier, 582)
      segments(193) shouldBe MotionSegment(Bezier, 585)
      segments(194) shouldBe MotionSegment(Bezier, 588)
      segments(195) shouldBe MotionSegment(Bezier, 591)
      segments(196) shouldBe MotionSegment(Bezier, 594)
      segments(197) shouldBe MotionSegment(Bezier, 598)
      segments(198) shouldBe MotionSegment(Bezier, 601)
      segments(199) shouldBe MotionSegment(Bezier, 604)
      segments(200) shouldBe MotionSegment(Bezier, 607)
      segments(201) shouldBe MotionSegment(Bezier, 610)
      segments(202) shouldBe MotionSegment(Bezier, 613)
      segments(203) shouldBe MotionSegment(Bezier, 616)
      segments(204) shouldBe MotionSegment(Bezier, 619)
      segments(205) shouldBe MotionSegment(Bezier, 622)
      segments(206) shouldBe MotionSegment(Bezier, 625)
      segments(207) shouldBe MotionSegment(Bezier, 628)
      segments(208) shouldBe MotionSegment(Bezier, 631)
      segments(209) shouldBe MotionSegment(Bezier, 634)
      segments(210) shouldBe MotionSegment(Bezier, 637)
      segments(211) shouldBe MotionSegment(Bezier, 640)
      segments(212) shouldBe MotionSegment(Bezier, 643)
      segments(213) shouldBe MotionSegment(Bezier, 646)
      segments(214) shouldBe MotionSegment(Bezier, 649)
      segments(215) shouldBe MotionSegment(Bezier, 652)
      segments(216) shouldBe MotionSegment(Bezier, 655)
      segments(217) shouldBe MotionSegment(Bezier, 658)
      segments(218) shouldBe MotionSegment(Bezier, 661)
      segments(219) shouldBe MotionSegment(Bezier, 664)
      segments(220) shouldBe MotionSegment(Bezier, 667)
      segments(221) shouldBe MotionSegment(Bezier, 670)
      segments(222) shouldBe MotionSegment(Bezier, 673)
      segments(223) shouldBe MotionSegment(Bezier, 676)
      segments(224) shouldBe MotionSegment(Bezier, 679)
      segments(225) shouldBe MotionSegment(Bezier, 682)
      segments(226) shouldBe MotionSegment(Bezier, 685)
      segments(227) shouldBe MotionSegment(Bezier, 688)
      segments(228) shouldBe MotionSegment(Bezier, 691)
      segments(229) shouldBe MotionSegment(Bezier, 695)
      segments(230) shouldBe MotionSegment(Bezier, 698)
      segments(231) shouldBe MotionSegment(Bezier, 701)
      segments(232) shouldBe MotionSegment(Bezier, 704)
      segments(233) shouldBe MotionSegment(Bezier, 707)
      segments(234) shouldBe MotionSegment(Bezier, 710)
      segments(235) shouldBe MotionSegment(Bezier, 713)
      segments(236) shouldBe MotionSegment(Bezier, 716)
      segments(237) shouldBe MotionSegment(Bezier, 719)
      segments(238) shouldBe MotionSegment(Bezier, 722)
      segments(239) shouldBe MotionSegment(Bezier, 725)
      segments(240) shouldBe MotionSegment(Bezier, 728)
      segments(241) shouldBe MotionSegment(Bezier, 731)
      segments(242) shouldBe MotionSegment(Bezier, 734)
      segments(243) shouldBe MotionSegment(Bezier, 737)
      segments(244) shouldBe MotionSegment(Bezier, 740)
      segments(245) shouldBe MotionSegment(Bezier, 744)
      segments(246) shouldBe MotionSegment(Bezier, 747)
      segments(247) shouldBe MotionSegment(Bezier, 750)
      segments(248) shouldBe MotionSegment(Bezier, 753)
      segments(249) shouldBe MotionSegment(Bezier, 756)
      segments(250) shouldBe MotionSegment(Bezier, 759)
      segments(251) shouldBe MotionSegment(Bezier, 762)
      segments(252) shouldBe MotionSegment(Bezier, 765)
      segments(253) shouldBe MotionSegment(Bezier, 768)
      segments(254) shouldBe MotionSegment(Bezier, 771)
      segments(255) shouldBe MotionSegment(Bezier, 774)
      segments(256) shouldBe MotionSegment(Bezier, 777)
      segments(257) shouldBe MotionSegment(Bezier, 780)
      segments(258) shouldBe MotionSegment(Bezier, 783)
      segments(259) shouldBe MotionSegment(Bezier, 786)
      segments(260) shouldBe MotionSegment(Bezier, 789)
      segments(261) shouldBe MotionSegment(Bezier, 793)
      segments(262) shouldBe MotionSegment(Bezier, 796)
      segments(263) shouldBe MotionSegment(Bezier, 799)
      segments(264) shouldBe MotionSegment(Bezier, 802)
      segments(265) shouldBe MotionSegment(Bezier, 805)
      segments(266) shouldBe MotionSegment(Bezier, 808)
      segments(267) shouldBe MotionSegment(Bezier, 811)
      segments(268) shouldBe MotionSegment(Bezier, 814)
      segments(269) shouldBe MotionSegment(Bezier, 817)
      segments(270) shouldBe MotionSegment(Bezier, 820)
      segments(271) shouldBe MotionSegment(Bezier, 823)
      segments(272) shouldBe MotionSegment(Bezier, 826)
      segments(273) shouldBe MotionSegment(Bezier, 829)
      segments(274) shouldBe MotionSegment(Bezier, 832)
      segments(275) shouldBe MotionSegment(Bezier, 835)
      segments(276) shouldBe MotionSegment(Bezier, 838)
      segments(277) shouldBe MotionSegment(Bezier, 842)
      segments(278) shouldBe MotionSegment(Bezier, 845)
      segments(279) shouldBe MotionSegment(Bezier, 848)
      segments(280) shouldBe MotionSegment(Bezier, 851)
      segments(281) shouldBe MotionSegment(Bezier, 854)
      segments(282) shouldBe MotionSegment(Bezier, 857)
      segments(283) shouldBe MotionSegment(Bezier, 860)
      segments(284) shouldBe MotionSegment(Bezier, 863)
      segments(285) shouldBe MotionSegment(Bezier, 866)
      segments(286) shouldBe MotionSegment(Bezier, 869)
      segments(287) shouldBe MotionSegment(Bezier, 872)
      segments(288) shouldBe MotionSegment(Bezier, 875)
      segments(289) shouldBe MotionSegment(Bezier, 878)
      segments(290) shouldBe MotionSegment(Bezier, 881)
      segments(291) shouldBe MotionSegment(Bezier, 884)
      segments(292) shouldBe MotionSegment(Bezier, 887)
      segments(293) shouldBe MotionSegment(Bezier, 890)
      segments(294) shouldBe MotionSegment(Bezier, 893)
      segments(295) shouldBe MotionSegment(Bezier, 896)
      segments(296) shouldBe MotionSegment(Bezier, 899)
      segments(297) shouldBe MotionSegment(Bezier, 902)
      segments(298) shouldBe MotionSegment(Bezier, 905)
      segments(299) shouldBe MotionSegment(Bezier, 908)
      segments(300) shouldBe MotionSegment(Bezier, 911)
      segments(301) shouldBe MotionSegment(Bezier, 914)
      segments(302) shouldBe MotionSegment(Bezier, 917)
      segments(303) shouldBe MotionSegment(Bezier, 920)
      segments(304) shouldBe MotionSegment(Bezier, 923)
      segments(305) shouldBe MotionSegment(Bezier, 926)
      segments(306) shouldBe MotionSegment(Bezier, 929)
      segments(307) shouldBe MotionSegment(Bezier, 932)
      segments(308) shouldBe MotionSegment(Bezier, 935)
      segments(309) shouldBe MotionSegment(Bezier, 939)
      segments(310) shouldBe MotionSegment(Bezier, 942)
      segments(311) shouldBe MotionSegment(Bezier, 945)
      segments(312) shouldBe MotionSegment(Bezier, 948)
      segments(313) shouldBe MotionSegment(Bezier, 951)
      segments(314) shouldBe MotionSegment(Bezier, 954)
      segments(315) shouldBe MotionSegment(Bezier, 957)
      segments(316) shouldBe MotionSegment(Bezier, 960)
      segments(317) shouldBe MotionSegment(Bezier, 963)
      segments(318) shouldBe MotionSegment(Bezier, 966)
      segments(319) shouldBe MotionSegment(Bezier, 969)
      segments(320) shouldBe MotionSegment(Bezier, 972)
      segments(321) shouldBe MotionSegment(Bezier, 975)
      segments(322) shouldBe MotionSegment(Bezier, 978)
      segments(323) shouldBe MotionSegment(Bezier, 981)
      segments(324) shouldBe MotionSegment(Bezier, 984)
      segments(325) shouldBe MotionSegment(Bezier, 988)
      segments(326) shouldBe MotionSegment(Bezier, 991)
      segments(327) shouldBe MotionSegment(Bezier, 994)
      segments(328) shouldBe MotionSegment(Bezier, 997)
      segments(329) shouldBe MotionSegment(Bezier, 1000)
      segments(330) shouldBe MotionSegment(Bezier, 1003)
      segments(331) shouldBe MotionSegment(Bezier, 1006)
      segments(332) shouldBe MotionSegment(Bezier, 1009)
      segments(333) shouldBe MotionSegment(Bezier, 1012)
      segments(334) shouldBe MotionSegment(Bezier, 1015)
      segments(335) shouldBe MotionSegment(Bezier, 1018)
      segments(336) shouldBe MotionSegment(Bezier, 1021)
      segments(337) shouldBe MotionSegment(Bezier, 1024)
      segments(338) shouldBe MotionSegment(Bezier, 1027)
      segments(339) shouldBe MotionSegment(Bezier, 1030)
      segments(340) shouldBe MotionSegment(Bezier, 1033)
      segments(341) shouldBe MotionSegment(Bezier, 1037)
      segments(342) shouldBe MotionSegment(Bezier, 1040)
      segments(343) shouldBe MotionSegment(Bezier, 1043)
      segments(344) shouldBe MotionSegment(Bezier, 1046)
      segments(345) shouldBe MotionSegment(Bezier, 1049)
      segments(346) shouldBe MotionSegment(Bezier, 1052)
      segments(347) shouldBe MotionSegment(Bezier, 1055)
      segments(348) shouldBe MotionSegment(Bezier, 1058)
      segments(349) shouldBe MotionSegment(Bezier, 1061)
      segments(350) shouldBe MotionSegment(Bezier, 1064)
      segments(351) shouldBe MotionSegment(Bezier, 1067)
      segments(352) shouldBe MotionSegment(Bezier, 1070)
      segments(353) shouldBe MotionSegment(Bezier, 1073)
      segments(354) shouldBe MotionSegment(Bezier, 1076)
      segments(355) shouldBe MotionSegment(Bezier, 1079)
      segments(356) shouldBe MotionSegment(Bezier, 1082)
      segments(357) shouldBe MotionSegment(Bezier, 1086)
      segments(358) shouldBe MotionSegment(Bezier, 1089)
      segments(359) shouldBe MotionSegment(Bezier, 1092)
      segments(360) shouldBe MotionSegment(Bezier, 1095)
      segments(361) shouldBe MotionSegment(Bezier, 1098)
      segments(362) shouldBe MotionSegment(Bezier, 1101)
      segments(363) shouldBe MotionSegment(Bezier, 1104)
      segments(364) shouldBe MotionSegment(Bezier, 1107)
      segments(365) shouldBe MotionSegment(Bezier, 1110)
      segments(366) shouldBe MotionSegment(Bezier, 1113)
      segments(367) shouldBe MotionSegment(Bezier, 1116)
      segments(368) shouldBe MotionSegment(Bezier, 1119)
      segments(369) shouldBe MotionSegment(Bezier, 1122)
      segments(370) shouldBe MotionSegment(Bezier, 1125)
      segments(371) shouldBe MotionSegment(Bezier, 1128)
      segments(372) shouldBe MotionSegment(Bezier, 1131)
      segments(373) shouldBe MotionSegment(Bezier, 1135)
      segments(374) shouldBe MotionSegment(Bezier, 1138)
      segments(375) shouldBe MotionSegment(Bezier, 1141)
      segments(376) shouldBe MotionSegment(Bezier, 1144)
      segments(377) shouldBe MotionSegment(Bezier, 1147)
      segments(378) shouldBe MotionSegment(Bezier, 1150)
      segments(379) shouldBe MotionSegment(Bezier, 1153)
      segments(380) shouldBe MotionSegment(Bezier, 1156)
      segments(381) shouldBe MotionSegment(Bezier, 1159)
      segments(382) shouldBe MotionSegment(Bezier, 1162)
      segments(383) shouldBe MotionSegment(Bezier, 1165)
      segments(384) shouldBe MotionSegment(Bezier, 1168)
      segments(385) shouldBe MotionSegment(Bezier, 1171)
      segments(386) shouldBe MotionSegment(Bezier, 1174)
      segments(387) shouldBe MotionSegment(Bezier, 1177)
      segments(388) shouldBe MotionSegment(Bezier, 1180)
      segments(389) shouldBe MotionSegment(Linear, 1184)
      segments(390) shouldBe MotionSegment(Linear, 1186)
      segments(391) shouldBe MotionSegment(Linear, 1188)
      segments(392) shouldBe MotionSegment(Linear, 1190)
      segments(393) shouldBe MotionSegment(Linear, 1192)
      segments(394) shouldBe MotionSegment(Linear, 1194)
      segments(395) shouldBe MotionSegment(Linear, 1196)
      segments(396) shouldBe MotionSegment(Linear, 1198)
      segments(397) shouldBe MotionSegment(Linear, 1200)
      segments(398) shouldBe MotionSegment(Linear, 1202)
      segments(399) shouldBe MotionSegment(Linear, 1204)
      segments(400) shouldBe MotionSegment(Linear, 1206)
      segments(401) shouldBe MotionSegment(Linear, 1208)
      segments(402) shouldBe MotionSegment(Linear, 1210)
      segments(403) shouldBe MotionSegment(Linear, 1212)
      segments(404) shouldBe MotionSegment(Linear, 1214)

      assertPointList("src/test/resources/expectation/markMotionIdle0Points.csv", motionData.pointsList)
    }

    Scenario("Load motion idle[1] from avatar Mark") {
      Given("A folder path contains json files for a Live2D avatar model")
      val folderPath = "src/test/resources/models/Mark"

      When("Create a MotionData from this Live2D avatar settings")
      val jsonSettingsReader = new JsonSettingsReader(folderPath)
      val settings: Settings = jsonSettingsReader.loadSettings().success.value
      val motionData = new AvatarMotionDataReader(settings.motionGroups("idle")(1)).loadMotionData()

      motionData.fps shouldBe 30.0
      motionData.isLoop shouldBe true
      motionData.curveCount shouldBe 37
      motionData.duration shouldBe 4.8f

      val curves = motionData.curvesList
      curves.size shouldBe 37
      curves(0) shouldBe MotionCurve("Opacity", Model, 1, 0, -1.0f, -1.0f)
      curves(1) shouldBe MotionCurve("EyeBlink", Model, 1, 1, -1.0f, -1.0f)
      curves(2) shouldBe MotionCurve("ParamAngleX", Parameter, 16, 2, -1.0f, -1.0f)
      curves(3) shouldBe MotionCurve("ParamAngleY", Parameter, 17, 18, -1.0f, -1.0f)
      curves(4) shouldBe MotionCurve("ParamAngleZ", Parameter, 9, 35, -1.0f, -1.0f)
      curves(5) shouldBe MotionCurve("ParamEyeBallX", Parameter, 8, 44, -1.0f, -1.0f)
      curves(6) shouldBe MotionCurve("ParamEyeBallY", Parameter, 8, 52, -1.0f, -1.0f)
      curves(7) shouldBe MotionCurve("ParamBrowLY", Parameter, 8, 60, -1.0f, -1.0f)
      curves(8) shouldBe MotionCurve("ParamBrowRY", Parameter, 8, 68, -1.0f, -1.0f)
      curves(9) shouldBe MotionCurve("ParamMouthOpenY", Parameter, 8, 76, -1.0f, -1.0f)
      curves(10) shouldBe MotionCurve("ParamArmL", Parameter, 16, 84, -1.0f, -1.0f)
      curves(11) shouldBe MotionCurve("ParamArmR", Parameter, 16, 100, -1.0f, -1.0f)
      curves(12) shouldBe MotionCurve("ParamLeftLeg", Parameter, 16, 116, -1.0f, -1.0f)
      curves(13) shouldBe MotionCurve("ParamRightLeg", Parameter, 16, 132, -1.0f, -1.0f)
      curves(14) shouldBe MotionCurve("ParamBodyAngleX", Parameter, 16, 148, -1.0f, -1.0f)
      curves(15) shouldBe MotionCurve("ParamBodyAngleY", Parameter, 32, 164, -1.0f, -1.0f)
      curves(16) shouldBe MotionCurve("ParamBodyAngleZ", Parameter, 16, 196, -1.0f, -1.0f)
      curves(17) shouldBe MotionCurve("ParamBreath", Parameter, 8, 212, -1.0f, -1.0f)
      curves(18) shouldBe MotionCurve("ParamHairFront", Parameter, 8, 220, -1.0f, -1.0f)
      curves(19) shouldBe MotionCurve("ParamHairSide", Parameter, 8, 228, -1.0f, -1.0f)
      curves(20) shouldBe MotionCurve("ParamHairBack", Parameter, 8, 236, -1.0f, -1.0f)
      curves(21) shouldBe MotionCurve("PartHead", PartOpacity, 1, 244, -1.0f, -1.0f)
      curves(22) shouldBe MotionCurve("PartHairFront", PartOpacity, 1, 245, -1.0f, -1.0f)
      curves(23) shouldBe MotionCurve("PartEyeL", PartOpacity, 1, 246, -1.0f, -1.0f)
      curves(24) shouldBe MotionCurve("PartEyeBallL", PartOpacity, 1, 247, -1.0f, -1.0f)
      curves(25) shouldBe MotionCurve("PartEyeWhiteL", PartOpacity, 1, 248, -1.0f, -1.0f)
      curves(26) shouldBe MotionCurve("PartEyeR", PartOpacity, 1, 249, -1.0f, -1.0f)
      curves(27) shouldBe MotionCurve("PartEyeBallR", PartOpacity, 1, 250, -1.0f, -1.0f)
      curves(28) shouldBe MotionCurve("PartEyeWhiteR", PartOpacity, 1, 251, -1.0f, -1.0f)
      curves(29) shouldBe MotionCurve("PartHairSide", PartOpacity, 1, 252, -1.0f, -1.0f)
      curves(30) shouldBe MotionCurve("PartMouth", PartOpacity, 1, 253, -1.0f, -1.0f)
      curves(31) shouldBe MotionCurve("PartOral", PartOpacity, 1, 254, -1.0f, -1.0f)
      curves(32) shouldBe MotionCurve("PartFace", PartOpacity, 1, 255, -1.0f, -1.0f)
      curves(33) shouldBe MotionCurve("PartBody", PartOpacity, 1, 256, -1.0f, -1.0f)
      curves(34) shouldBe MotionCurve("PartArmL", PartOpacity, 1, 257, -1.0f, -1.0f)
      curves(35) shouldBe MotionCurve("PartArmR", PartOpacity, 1, 258, -1.0f, -1.0f)
      curves(36) shouldBe MotionCurve("PartHairBack", PartOpacity, 1, 259, -1.0f, -1.0f)

      val segments = motionData.segmentsList
      segments.size shouldBe 260
      segments(0) shouldBe MotionSegment(Linear, 0)
      segments(1) shouldBe MotionSegment(Linear, 2)
      segments(2) shouldBe MotionSegment(Bezier, 4)
      segments(3) shouldBe MotionSegment(Bezier, 7)
      segments(4) shouldBe MotionSegment(Bezier, 10)
      segments(5) shouldBe MotionSegment(Bezier, 13)
      segments(6) shouldBe MotionSegment(Bezier, 16)
      segments(7) shouldBe MotionSegment(Bezier, 19)
      segments(8) shouldBe MotionSegment(Bezier, 22)
      segments(9) shouldBe MotionSegment(Bezier, 25)
      segments(10) shouldBe MotionSegment(Bezier, 28)
      segments(11) shouldBe MotionSegment(Bezier, 31)
      segments(12) shouldBe MotionSegment(Bezier, 34)
      segments(13) shouldBe MotionSegment(Bezier, 37)
      segments(14) shouldBe MotionSegment(Bezier, 40)
      segments(15) shouldBe MotionSegment(Bezier, 43)
      segments(16) shouldBe MotionSegment(Bezier, 46)
      segments(17) shouldBe MotionSegment(Bezier, 49)
      segments(18) shouldBe MotionSegment(Bezier, 53)
      segments(19) shouldBe MotionSegment(Bezier, 56)
      segments(20) shouldBe MotionSegment(Bezier, 59)
      segments(21) shouldBe MotionSegment(Bezier, 62)
      segments(22) shouldBe MotionSegment(Bezier, 65)
      segments(23) shouldBe MotionSegment(Bezier, 68)
      segments(24) shouldBe MotionSegment(Bezier, 71)
      segments(25) shouldBe MotionSegment(Bezier, 74)
      segments(26) shouldBe MotionSegment(Bezier, 77)
      segments(27) shouldBe MotionSegment(Bezier, 80)
      segments(28) shouldBe MotionSegment(Bezier, 83)
      segments(29) shouldBe MotionSegment(Bezier, 86)
      segments(30) shouldBe MotionSegment(Bezier, 89)
      segments(31) shouldBe MotionSegment(Bezier, 92)
      segments(32) shouldBe MotionSegment(Bezier, 95)
      segments(33) shouldBe MotionSegment(Bezier, 98)
      segments(34) shouldBe MotionSegment(Bezier, 101)
      segments(35) shouldBe MotionSegment(Bezier, 105)
      segments(36) shouldBe MotionSegment(Bezier, 108)
      segments(37) shouldBe MotionSegment(Bezier, 111)
      segments(38) shouldBe MotionSegment(Bezier, 114)
      segments(39) shouldBe MotionSegment(Bezier, 117)
      segments(40) shouldBe MotionSegment(Bezier, 120)
      segments(41) shouldBe MotionSegment(Bezier, 123)
      segments(42) shouldBe MotionSegment(Bezier, 126)
      segments(43) shouldBe MotionSegment(Bezier, 129)
      segments(44) shouldBe MotionSegment(Bezier, 133)
      segments(45) shouldBe MotionSegment(Bezier, 136)
      segments(46) shouldBe MotionSegment(Bezier, 139)
      segments(47) shouldBe MotionSegment(Bezier, 142)
      segments(48) shouldBe MotionSegment(Bezier, 145)
      segments(49) shouldBe MotionSegment(Bezier, 148)
      segments(50) shouldBe MotionSegment(Bezier, 151)
      segments(51) shouldBe MotionSegment(Bezier, 154)
      segments(52) shouldBe MotionSegment(Bezier, 158)
      segments(53) shouldBe MotionSegment(Bezier, 161)
      segments(54) shouldBe MotionSegment(Bezier, 164)
      segments(55) shouldBe MotionSegment(Bezier, 167)
      segments(56) shouldBe MotionSegment(Bezier, 170)
      segments(57) shouldBe MotionSegment(Bezier, 173)
      segments(58) shouldBe MotionSegment(Bezier, 176)
      segments(59) shouldBe MotionSegment(Bezier, 179)
      segments(60) shouldBe MotionSegment(Bezier, 183)
      segments(61) shouldBe MotionSegment(Bezier, 186)
      segments(62) shouldBe MotionSegment(Bezier, 189)
      segments(63) shouldBe MotionSegment(Bezier, 192)
      segments(64) shouldBe MotionSegment(Bezier, 195)
      segments(65) shouldBe MotionSegment(Bezier, 198)
      segments(66) shouldBe MotionSegment(Bezier, 201)
      segments(67) shouldBe MotionSegment(Bezier, 204)
      segments(68) shouldBe MotionSegment(Bezier, 208)
      segments(69) shouldBe MotionSegment(Bezier, 211)
      segments(70) shouldBe MotionSegment(Bezier, 214)
      segments(71) shouldBe MotionSegment(Bezier, 217)
      segments(72) shouldBe MotionSegment(Bezier, 220)
      segments(73) shouldBe MotionSegment(Bezier, 223)
      segments(74) shouldBe MotionSegment(Bezier, 226)
      segments(75) shouldBe MotionSegment(Bezier, 229)
      segments(76) shouldBe MotionSegment(Bezier, 233)
      segments(77) shouldBe MotionSegment(Bezier, 236)
      segments(78) shouldBe MotionSegment(Bezier, 239)
      segments(79) shouldBe MotionSegment(Bezier, 242)
      segments(80) shouldBe MotionSegment(Bezier, 245)
      segments(81) shouldBe MotionSegment(Bezier, 248)
      segments(82) shouldBe MotionSegment(Bezier, 251)
      segments(83) shouldBe MotionSegment(Bezier, 254)
      segments(84) shouldBe MotionSegment(Bezier, 258)
      segments(85) shouldBe MotionSegment(Bezier, 261)
      segments(86) shouldBe MotionSegment(Bezier, 264)
      segments(87) shouldBe MotionSegment(Bezier, 267)
      segments(88) shouldBe MotionSegment(Bezier, 270)
      segments(89) shouldBe MotionSegment(Bezier, 273)
      segments(90) shouldBe MotionSegment(Bezier, 276)
      segments(91) shouldBe MotionSegment(Bezier, 279)
      segments(92) shouldBe MotionSegment(Bezier, 282)
      segments(93) shouldBe MotionSegment(Bezier, 285)
      segments(94) shouldBe MotionSegment(Bezier, 288)
      segments(95) shouldBe MotionSegment(Bezier, 291)
      segments(96) shouldBe MotionSegment(Bezier, 294)
      segments(97) shouldBe MotionSegment(Bezier, 297)
      segments(98) shouldBe MotionSegment(Bezier, 300)
      segments(99) shouldBe MotionSegment(Bezier, 303)
      segments(100) shouldBe MotionSegment(Bezier, 307)
      segments(101) shouldBe MotionSegment(Bezier, 310)
      segments(102) shouldBe MotionSegment(Bezier, 313)
      segments(103) shouldBe MotionSegment(Bezier, 316)
      segments(104) shouldBe MotionSegment(Bezier, 319)
      segments(105) shouldBe MotionSegment(Bezier, 322)
      segments(106) shouldBe MotionSegment(Bezier, 325)
      segments(107) shouldBe MotionSegment(Bezier, 328)
      segments(108) shouldBe MotionSegment(Bezier, 331)
      segments(109) shouldBe MotionSegment(Bezier, 334)
      segments(110) shouldBe MotionSegment(Bezier, 337)
      segments(111) shouldBe MotionSegment(Bezier, 340)
      segments(112) shouldBe MotionSegment(Bezier, 343)
      segments(113) shouldBe MotionSegment(Bezier, 346)
      segments(114) shouldBe MotionSegment(Bezier, 349)
      segments(115) shouldBe MotionSegment(Bezier, 352)
      segments(116) shouldBe MotionSegment(Bezier, 356)
      segments(117) shouldBe MotionSegment(Bezier, 359)
      segments(118) shouldBe MotionSegment(Bezier, 362)
      segments(119) shouldBe MotionSegment(Bezier, 365)
      segments(120) shouldBe MotionSegment(Bezier, 368)
      segments(121) shouldBe MotionSegment(Bezier, 371)
      segments(122) shouldBe MotionSegment(Bezier, 374)
      segments(123) shouldBe MotionSegment(Bezier, 377)
      segments(124) shouldBe MotionSegment(Bezier, 380)
      segments(125) shouldBe MotionSegment(Bezier, 383)
      segments(126) shouldBe MotionSegment(Bezier, 386)
      segments(127) shouldBe MotionSegment(Bezier, 389)
      segments(128) shouldBe MotionSegment(Bezier, 392)
      segments(129) shouldBe MotionSegment(Bezier, 395)
      segments(130) shouldBe MotionSegment(Bezier, 398)
      segments(131) shouldBe MotionSegment(Bezier, 401)
      segments(132) shouldBe MotionSegment(Bezier, 405)
      segments(133) shouldBe MotionSegment(Bezier, 408)
      segments(134) shouldBe MotionSegment(Bezier, 411)
      segments(135) shouldBe MotionSegment(Bezier, 414)
      segments(136) shouldBe MotionSegment(Bezier, 417)
      segments(137) shouldBe MotionSegment(Bezier, 420)
      segments(138) shouldBe MotionSegment(Bezier, 423)
      segments(139) shouldBe MotionSegment(Bezier, 426)
      segments(140) shouldBe MotionSegment(Bezier, 429)
      segments(141) shouldBe MotionSegment(Bezier, 432)
      segments(142) shouldBe MotionSegment(Bezier, 435)
      segments(143) shouldBe MotionSegment(Bezier, 438)
      segments(144) shouldBe MotionSegment(Bezier, 441)
      segments(145) shouldBe MotionSegment(Bezier, 444)
      segments(146) shouldBe MotionSegment(Bezier, 447)
      segments(147) shouldBe MotionSegment(Bezier, 450)
      segments(148) shouldBe MotionSegment(Bezier, 454)
      segments(149) shouldBe MotionSegment(Bezier, 457)
      segments(150) shouldBe MotionSegment(Bezier, 460)
      segments(151) shouldBe MotionSegment(Bezier, 463)
      segments(152) shouldBe MotionSegment(Bezier, 466)
      segments(153) shouldBe MotionSegment(Bezier, 469)
      segments(154) shouldBe MotionSegment(Bezier, 472)
      segments(155) shouldBe MotionSegment(Bezier, 475)
      segments(156) shouldBe MotionSegment(Bezier, 478)
      segments(157) shouldBe MotionSegment(Bezier, 481)
      segments(158) shouldBe MotionSegment(Bezier, 484)
      segments(159) shouldBe MotionSegment(Bezier, 487)
      segments(160) shouldBe MotionSegment(Bezier, 490)
      segments(161) shouldBe MotionSegment(Bezier, 493)
      segments(162) shouldBe MotionSegment(Bezier, 496)
      segments(163) shouldBe MotionSegment(Bezier, 499)
      segments(164) shouldBe MotionSegment(Bezier, 503)
      segments(165) shouldBe MotionSegment(Bezier, 506)
      segments(166) shouldBe MotionSegment(Bezier, 509)
      segments(167) shouldBe MotionSegment(Bezier, 512)
      segments(168) shouldBe MotionSegment(Bezier, 515)
      segments(169) shouldBe MotionSegment(Bezier, 518)
      segments(170) shouldBe MotionSegment(Bezier, 521)
      segments(171) shouldBe MotionSegment(Bezier, 524)
      segments(172) shouldBe MotionSegment(Bezier, 527)
      segments(173) shouldBe MotionSegment(Bezier, 530)
      segments(174) shouldBe MotionSegment(Bezier, 533)
      segments(175) shouldBe MotionSegment(Bezier, 536)
      segments(176) shouldBe MotionSegment(Bezier, 539)
      segments(177) shouldBe MotionSegment(Bezier, 542)
      segments(178) shouldBe MotionSegment(Bezier, 545)
      segments(179) shouldBe MotionSegment(Bezier, 548)
      segments(180) shouldBe MotionSegment(Bezier, 551)
      segments(181) shouldBe MotionSegment(Bezier, 554)
      segments(182) shouldBe MotionSegment(Bezier, 557)
      segments(183) shouldBe MotionSegment(Bezier, 560)
      segments(184) shouldBe MotionSegment(Bezier, 563)
      segments(185) shouldBe MotionSegment(Bezier, 566)
      segments(186) shouldBe MotionSegment(Bezier, 569)
      segments(187) shouldBe MotionSegment(Bezier, 572)
      segments(188) shouldBe MotionSegment(Bezier, 575)
      segments(189) shouldBe MotionSegment(Bezier, 578)
      segments(190) shouldBe MotionSegment(Bezier, 581)
      segments(191) shouldBe MotionSegment(Bezier, 584)
      segments(192) shouldBe MotionSegment(Bezier, 587)
      segments(193) shouldBe MotionSegment(Bezier, 590)
      segments(194) shouldBe MotionSegment(Bezier, 593)
      segments(195) shouldBe MotionSegment(Bezier, 596)
      segments(196) shouldBe MotionSegment(Bezier, 600)
      segments(197) shouldBe MotionSegment(Bezier, 603)
      segments(198) shouldBe MotionSegment(Bezier, 606)
      segments(199) shouldBe MotionSegment(Bezier, 609)
      segments(200) shouldBe MotionSegment(Bezier, 612)
      segments(201) shouldBe MotionSegment(Bezier, 615)
      segments(202) shouldBe MotionSegment(Bezier, 618)
      segments(203) shouldBe MotionSegment(Bezier, 621)
      segments(204) shouldBe MotionSegment(Bezier, 624)
      segments(205) shouldBe MotionSegment(Bezier, 627)
      segments(206) shouldBe MotionSegment(Bezier, 630)
      segments(207) shouldBe MotionSegment(Bezier, 633)
      segments(208) shouldBe MotionSegment(Bezier, 636)
      segments(209) shouldBe MotionSegment(Bezier, 639)
      segments(210) shouldBe MotionSegment(Bezier, 642)
      segments(211) shouldBe MotionSegment(Bezier, 645)
      segments(212) shouldBe MotionSegment(Bezier, 649)
      segments(213) shouldBe MotionSegment(Bezier, 652)
      segments(214) shouldBe MotionSegment(Bezier, 655)
      segments(215) shouldBe MotionSegment(Bezier, 658)
      segments(216) shouldBe MotionSegment(Bezier, 661)
      segments(217) shouldBe MotionSegment(Bezier, 664)
      segments(218) shouldBe MotionSegment(Bezier, 667)
      segments(219) shouldBe MotionSegment(Bezier, 670)
      segments(220) shouldBe MotionSegment(Bezier, 674)
      segments(221) shouldBe MotionSegment(Bezier, 677)
      segments(222) shouldBe MotionSegment(Bezier, 680)
      segments(223) shouldBe MotionSegment(Bezier, 683)
      segments(224) shouldBe MotionSegment(Bezier, 686)
      segments(225) shouldBe MotionSegment(Bezier, 689)
      segments(226) shouldBe MotionSegment(Bezier, 692)
      segments(227) shouldBe MotionSegment(Bezier, 695)
      segments(228) shouldBe MotionSegment(Bezier, 699)
      segments(229) shouldBe MotionSegment(Bezier, 702)
      segments(230) shouldBe MotionSegment(Bezier, 705)
      segments(231) shouldBe MotionSegment(Bezier, 708)
      segments(232) shouldBe MotionSegment(Bezier, 711)
      segments(233) shouldBe MotionSegment(Bezier, 714)
      segments(234) shouldBe MotionSegment(Bezier, 717)
      segments(235) shouldBe MotionSegment(Bezier, 720)
      segments(236) shouldBe MotionSegment(Bezier, 724)
      segments(237) shouldBe MotionSegment(Bezier, 727)
      segments(238) shouldBe MotionSegment(Bezier, 730)
      segments(239) shouldBe MotionSegment(Bezier, 733)
      segments(240) shouldBe MotionSegment(Bezier, 736)
      segments(241) shouldBe MotionSegment(Bezier, 739)
      segments(242) shouldBe MotionSegment(Bezier, 742)
      segments(243) shouldBe MotionSegment(Bezier, 745)
      segments(244) shouldBe MotionSegment(Linear, 749)
      segments(245) shouldBe MotionSegment(Linear, 751)
      segments(246) shouldBe MotionSegment(Linear, 753)
      segments(247) shouldBe MotionSegment(Linear, 755)
      segments(248) shouldBe MotionSegment(Linear, 757)
      segments(249) shouldBe MotionSegment(Linear, 759)
      segments(250) shouldBe MotionSegment(Linear, 761)
      segments(251) shouldBe MotionSegment(Linear, 763)
      segments(252) shouldBe MotionSegment(Linear, 765)
      segments(253) shouldBe MotionSegment(Linear, 767)
      segments(254) shouldBe MotionSegment(Linear, 769)
      segments(255) shouldBe MotionSegment(Linear, 771)
      segments(256) shouldBe MotionSegment(Linear, 773)
      segments(257) shouldBe MotionSegment(Linear, 775)
      segments(258) shouldBe MotionSegment(Linear, 777)
      segments(259) shouldBe MotionSegment(Linear, 779)

      assertPointList("src/test/resources/expectation/markMotionIdle1Points.csv", motionData.pointsList)
    }

    Scenario("Load motion idle[3] from avatar Mark") {
      Given("A folder path contains json files for a Live2D avatar model")
      val folderPath = "src/test/resources/models/Mark"

      When("Create a MotionData from this Live2D avatar settings")
      val jsonSettingsReader = new JsonSettingsReader(folderPath)
      val settings: Settings = jsonSettingsReader.loadSettings().success.value
      val motionData = new AvatarMotionDataReader(settings.motionGroups("idle")(3)).loadMotionData()

      motionData.fps shouldBe 30.0
      motionData.isLoop shouldBe true
      motionData.curveCount shouldBe 37
      motionData.duration shouldBe 4.833f

      val curves = motionData.curvesList
      curves.size shouldBe 37
      curves(0) shouldBe MotionCurve("Opacity", Model, 2, 0, -1.0f, -1.0f)
      curves(1) shouldBe MotionCurve("EyeBlink", Model, 5, 2, -1.0f, -1.0f)
      curves(2) shouldBe MotionCurve("ParamAngleX", Parameter, 11, 7, -1.0f, -1.0f)
      curves(3) shouldBe MotionCurve("ParamAngleY", Parameter, 9, 18, -1.0f, -1.0f)
      curves(4) shouldBe MotionCurve("ParamAngleZ", Parameter, 13, 27, -1.0f, -1.0f)
      curves(5) shouldBe MotionCurve("ParamEyeBallX", Parameter, 11, 40, -1.0f, -1.0f)
      curves(6) shouldBe MotionCurve("ParamEyeBallY", Parameter, 11, 51, -1.0f, -1.0f)
      curves(7) shouldBe MotionCurve("ParamBrowLY", Parameter, 9, 62, -1.0f, -1.0f)
      curves(8) shouldBe MotionCurve("ParamBrowRY", Parameter, 9, 71, -1.0f, -1.0f)
      curves(9) shouldBe MotionCurve("ParamMouthOpenY", Parameter, 8, 80, -1.0f, -1.0f)
      curves(10) shouldBe MotionCurve("ParamArmL", Parameter, 13, 88, -1.0f, -1.0f)
      curves(11) shouldBe MotionCurve("ParamArmR", Parameter, 13, 101, -1.0f, -1.0f)
      curves(12) shouldBe MotionCurve("ParamLeftLeg", Parameter, 8, 114, -1.0f, -1.0f)
      curves(13) shouldBe MotionCurve("ParamRightLeg", Parameter, 8, 122, -1.0f, -1.0f)
      curves(14) shouldBe MotionCurve("ParamBodyAngleX", Parameter, 11, 130, -1.0f, -1.0f)
      curves(15) shouldBe MotionCurve("ParamBodyAngleY", Parameter, 10, 141, -1.0f, -1.0f)
      curves(16) shouldBe MotionCurve("ParamBodyAngleZ", Parameter, 9, 151, -1.0f, -1.0f)
      curves(17) shouldBe MotionCurve("ParamBreath", Parameter, 8, 160, -1.0f, -1.0f)
      curves(18) shouldBe MotionCurve("ParamHairFront", Parameter, 8, 168, -1.0f, -1.0f)
      curves(19) shouldBe MotionCurve("ParamHairSide", Parameter, 8, 176, -1.0f, -1.0f)
      curves(20) shouldBe MotionCurve("ParamHairBack", Parameter, 8, 184, -1.0f, -1.0f)
      curves(21) shouldBe MotionCurve("PartHead", PartOpacity, 2, 192, -1.0f, -1.0f)
      curves(22) shouldBe MotionCurve("PartHairFront", PartOpacity, 2, 194, -1.0f, -1.0f)
      curves(23) shouldBe MotionCurve("PartEyeL", PartOpacity, 2, 196, -1.0f, -1.0f)
      curves(24) shouldBe MotionCurve("PartEyeBallL", PartOpacity, 2, 198, -1.0f, -1.0f)
      curves(25) shouldBe MotionCurve("PartEyeWhiteL", PartOpacity, 2, 200, -1.0f, -1.0f)
      curves(26) shouldBe MotionCurve("PartEyeR", PartOpacity, 2, 202, -1.0f, -1.0f)
      curves(27) shouldBe MotionCurve("PartEyeBallR", PartOpacity, 2, 204, -1.0f, -1.0f)
      curves(28) shouldBe MotionCurve("PartEyeWhiteR", PartOpacity, 2, 206, -1.0f, -1.0f)
      curves(29) shouldBe MotionCurve("PartHairSide", PartOpacity, 2, 208, -1.0f, -1.0f)
      curves(30) shouldBe MotionCurve("PartMouth", PartOpacity, 2, 210, -1.0f, -1.0f)
      curves(31) shouldBe MotionCurve("PartOral", PartOpacity, 2, 212, -1.0f, -1.0f)
      curves(32) shouldBe MotionCurve("PartFace", PartOpacity, 2, 214, -1.0f, -1.0f)
      curves(33) shouldBe MotionCurve("PartBody", PartOpacity, 2, 216, -1.0f, -1.0f)
      curves(34) shouldBe MotionCurve("PartArmL", PartOpacity, 2, 218, -1.0f, -1.0f)
      curves(35) shouldBe MotionCurve("PartArmR", PartOpacity, 2, 220, -1.0f, -1.0f)
      curves(36) shouldBe MotionCurve("PartHairBack", PartOpacity, 2, 222, -1.0f, -1.0f)

      val segments = motionData.segmentsList
      segments.size shouldBe 224
      segments(0) shouldBe MotionSegment(Bezier, 0)
      segments(1) shouldBe MotionSegment(Linear, 3)
      segments(2) shouldBe MotionSegment(Bezier, 5)
      segments(3) shouldBe MotionSegment(Bezier, 8)
      segments(4) shouldBe MotionSegment(Bezier, 11)
      segments(5) shouldBe MotionSegment(Bezier, 14)
      segments(6) shouldBe MotionSegment(Linear, 17)
      segments(7) shouldBe MotionSegment(Bezier, 19)
      segments(8) shouldBe MotionSegment(Bezier, 22)
      segments(9) shouldBe MotionSegment(Bezier, 25)
      segments(10) shouldBe MotionSegment(Bezier, 28)
      segments(11) shouldBe MotionSegment(Bezier, 31)
      segments(12) shouldBe MotionSegment(Bezier, 34)
      segments(13) shouldBe MotionSegment(Bezier, 37)
      segments(14) shouldBe MotionSegment(Bezier, 40)
      segments(15) shouldBe MotionSegment(Bezier, 43)
      segments(16) shouldBe MotionSegment(Bezier, 46)
      segments(17) shouldBe MotionSegment(Linear, 49)
      segments(18) shouldBe MotionSegment(Bezier, 51)
      segments(19) shouldBe MotionSegment(Bezier, 54)
      segments(20) shouldBe MotionSegment(Bezier, 57)
      segments(21) shouldBe MotionSegment(Bezier, 60)
      segments(22) shouldBe MotionSegment(Bezier, 63)
      segments(23) shouldBe MotionSegment(Bezier, 66)
      segments(24) shouldBe MotionSegment(Bezier, 69)
      segments(25) shouldBe MotionSegment(Bezier, 72)
      segments(26) shouldBe MotionSegment(Linear, 75)
      segments(27) shouldBe MotionSegment(Bezier, 77)
      segments(28) shouldBe MotionSegment(Bezier, 80)
      segments(29) shouldBe MotionSegment(Bezier, 83)
      segments(30) shouldBe MotionSegment(Bezier, 86)
      segments(31) shouldBe MotionSegment(Bezier, 89)
      segments(32) shouldBe MotionSegment(Bezier, 92)
      segments(33) shouldBe MotionSegment(Bezier, 95)
      segments(34) shouldBe MotionSegment(Bezier, 98)
      segments(35) shouldBe MotionSegment(Bezier, 101)
      segments(36) shouldBe MotionSegment(Bezier, 104)
      segments(37) shouldBe MotionSegment(Bezier, 107)
      segments(38) shouldBe MotionSegment(Bezier, 110)
      segments(39) shouldBe MotionSegment(Linear, 113)
      segments(40) shouldBe MotionSegment(Bezier, 115)
      segments(41) shouldBe MotionSegment(Bezier, 118)
      segments(42) shouldBe MotionSegment(Bezier, 121)
      segments(43) shouldBe MotionSegment(Bezier, 124)
      segments(44) shouldBe MotionSegment(Bezier, 127)
      segments(45) shouldBe MotionSegment(Bezier, 130)
      segments(46) shouldBe MotionSegment(Bezier, 133)
      segments(47) shouldBe MotionSegment(Bezier, 136)
      segments(48) shouldBe MotionSegment(Bezier, 139)
      segments(49) shouldBe MotionSegment(Bezier, 142)
      segments(50) shouldBe MotionSegment(Linear, 145)
      segments(51) shouldBe MotionSegment(Bezier, 147)
      segments(52) shouldBe MotionSegment(Bezier, 150)
      segments(53) shouldBe MotionSegment(Bezier, 153)
      segments(54) shouldBe MotionSegment(Bezier, 156)
      segments(55) shouldBe MotionSegment(Bezier, 159)
      segments(56) shouldBe MotionSegment(Bezier, 162)
      segments(57) shouldBe MotionSegment(Bezier, 165)
      segments(58) shouldBe MotionSegment(Bezier, 168)
      segments(59) shouldBe MotionSegment(Bezier, 171)
      segments(60) shouldBe MotionSegment(Bezier, 174)
      segments(61) shouldBe MotionSegment(Linear, 177)
      segments(62) shouldBe MotionSegment(Bezier, 179)
      segments(63) shouldBe MotionSegment(Bezier, 182)
      segments(64) shouldBe MotionSegment(Bezier, 185)
      segments(65) shouldBe MotionSegment(Bezier, 188)
      segments(66) shouldBe MotionSegment(Bezier, 191)
      segments(67) shouldBe MotionSegment(Bezier, 194)
      segments(68) shouldBe MotionSegment(Bezier, 197)
      segments(69) shouldBe MotionSegment(Bezier, 200)
      segments(70) shouldBe MotionSegment(Linear, 203)
      segments(71) shouldBe MotionSegment(Bezier, 205)
      segments(72) shouldBe MotionSegment(Bezier, 208)
      segments(73) shouldBe MotionSegment(Bezier, 211)
      segments(74) shouldBe MotionSegment(Bezier, 214)
      segments(75) shouldBe MotionSegment(Bezier, 217)
      segments(76) shouldBe MotionSegment(Bezier, 220)
      segments(77) shouldBe MotionSegment(Bezier, 223)
      segments(78) shouldBe MotionSegment(Bezier, 226)
      segments(79) shouldBe MotionSegment(Linear, 229)
      segments(80) shouldBe MotionSegment(Bezier, 231)
      segments(81) shouldBe MotionSegment(Bezier, 234)
      segments(82) shouldBe MotionSegment(Bezier, 237)
      segments(83) shouldBe MotionSegment(Bezier, 240)
      segments(84) shouldBe MotionSegment(Bezier, 243)
      segments(85) shouldBe MotionSegment(Bezier, 246)
      segments(86) shouldBe MotionSegment(Bezier, 249)
      segments(87) shouldBe MotionSegment(Linear, 252)
      segments(88) shouldBe MotionSegment(Bezier, 254)
      segments(89) shouldBe MotionSegment(Bezier, 257)
      segments(90) shouldBe MotionSegment(Bezier, 260)
      segments(91) shouldBe MotionSegment(Bezier, 263)
      segments(92) shouldBe MotionSegment(Bezier, 266)
      segments(93) shouldBe MotionSegment(Bezier, 269)
      segments(94) shouldBe MotionSegment(Bezier, 272)
      segments(95) shouldBe MotionSegment(Bezier, 275)
      segments(96) shouldBe MotionSegment(Bezier, 278)
      segments(97) shouldBe MotionSegment(Bezier, 281)
      segments(98) shouldBe MotionSegment(Bezier, 284)
      segments(99) shouldBe MotionSegment(Bezier, 287)
      segments(100) shouldBe MotionSegment(Linear, 290)
      segments(101) shouldBe MotionSegment(Bezier, 292)
      segments(102) shouldBe MotionSegment(Bezier, 295)
      segments(103) shouldBe MotionSegment(Bezier, 298)
      segments(104) shouldBe MotionSegment(Bezier, 301)
      segments(105) shouldBe MotionSegment(Bezier, 304)
      segments(106) shouldBe MotionSegment(Bezier, 307)
      segments(107) shouldBe MotionSegment(Bezier, 310)
      segments(108) shouldBe MotionSegment(Bezier, 313)
      segments(109) shouldBe MotionSegment(Bezier, 316)
      segments(110) shouldBe MotionSegment(Bezier, 319)
      segments(111) shouldBe MotionSegment(Bezier, 322)
      segments(112) shouldBe MotionSegment(Bezier, 325)
      segments(113) shouldBe MotionSegment(Linear, 328)
      segments(114) shouldBe MotionSegment(Bezier, 330)
      segments(115) shouldBe MotionSegment(Bezier, 333)
      segments(116) shouldBe MotionSegment(Bezier, 336)
      segments(117) shouldBe MotionSegment(Bezier, 339)
      segments(118) shouldBe MotionSegment(Bezier, 342)
      segments(119) shouldBe MotionSegment(Bezier, 345)
      segments(120) shouldBe MotionSegment(Bezier, 348)
      segments(121) shouldBe MotionSegment(Linear, 351)
      segments(122) shouldBe MotionSegment(Bezier, 353)
      segments(123) shouldBe MotionSegment(Bezier, 356)
      segments(124) shouldBe MotionSegment(Bezier, 359)
      segments(125) shouldBe MotionSegment(Bezier, 362)
      segments(126) shouldBe MotionSegment(Bezier, 365)
      segments(127) shouldBe MotionSegment(Bezier, 368)
      segments(128) shouldBe MotionSegment(Bezier, 371)
      segments(129) shouldBe MotionSegment(Linear, 374)
      segments(130) shouldBe MotionSegment(Bezier, 376)
      segments(131) shouldBe MotionSegment(Bezier, 379)
      segments(132) shouldBe MotionSegment(Bezier, 382)
      segments(133) shouldBe MotionSegment(Bezier, 385)
      segments(134) shouldBe MotionSegment(Bezier, 388)
      segments(135) shouldBe MotionSegment(Bezier, 391)
      segments(136) shouldBe MotionSegment(Bezier, 394)
      segments(137) shouldBe MotionSegment(Bezier, 397)
      segments(138) shouldBe MotionSegment(Bezier, 400)
      segments(139) shouldBe MotionSegment(Bezier, 403)
      segments(140) shouldBe MotionSegment(Linear, 406)
      segments(141) shouldBe MotionSegment(Bezier, 408)
      segments(142) shouldBe MotionSegment(Bezier, 411)
      segments(143) shouldBe MotionSegment(Bezier, 414)
      segments(144) shouldBe MotionSegment(Bezier, 417)
      segments(145) shouldBe MotionSegment(Bezier, 420)
      segments(146) shouldBe MotionSegment(Bezier, 423)
      segments(147) shouldBe MotionSegment(Bezier, 426)
      segments(148) shouldBe MotionSegment(Bezier, 429)
      segments(149) shouldBe MotionSegment(Bezier, 432)
      segments(150) shouldBe MotionSegment(Linear, 435)
      segments(151) shouldBe MotionSegment(Linear, 437)
      segments(152) shouldBe MotionSegment(Bezier, 438)
      segments(153) shouldBe MotionSegment(Bezier, 441)
      segments(154) shouldBe MotionSegment(Bezier, 444)
      segments(155) shouldBe MotionSegment(Bezier, 447)
      segments(156) shouldBe MotionSegment(Bezier, 450)
      segments(157) shouldBe MotionSegment(Bezier, 453)
      segments(158) shouldBe MotionSegment(Bezier, 456)
      segments(159) shouldBe MotionSegment(Linear, 459)
      segments(160) shouldBe MotionSegment(Bezier, 461)
      segments(161) shouldBe MotionSegment(Bezier, 464)
      segments(162) shouldBe MotionSegment(Bezier, 467)
      segments(163) shouldBe MotionSegment(Bezier, 470)
      segments(164) shouldBe MotionSegment(Bezier, 473)
      segments(165) shouldBe MotionSegment(Bezier, 476)
      segments(166) shouldBe MotionSegment(Bezier, 479)
      segments(167) shouldBe MotionSegment(Linear, 482)
      segments(168) shouldBe MotionSegment(Bezier, 484)
      segments(169) shouldBe MotionSegment(Bezier, 487)
      segments(170) shouldBe MotionSegment(Bezier, 490)
      segments(171) shouldBe MotionSegment(Bezier, 493)
      segments(172) shouldBe MotionSegment(Bezier, 496)
      segments(173) shouldBe MotionSegment(Bezier, 499)
      segments(174) shouldBe MotionSegment(Bezier, 502)
      segments(175) shouldBe MotionSegment(Linear, 505)
      segments(176) shouldBe MotionSegment(Bezier, 507)
      segments(177) shouldBe MotionSegment(Bezier, 510)
      segments(178) shouldBe MotionSegment(Bezier, 513)
      segments(179) shouldBe MotionSegment(Bezier, 516)
      segments(180) shouldBe MotionSegment(Bezier, 519)
      segments(181) shouldBe MotionSegment(Bezier, 522)
      segments(182) shouldBe MotionSegment(Bezier, 525)
      segments(183) shouldBe MotionSegment(Linear, 528)
      segments(184) shouldBe MotionSegment(Bezier, 530)
      segments(185) shouldBe MotionSegment(Bezier, 533)
      segments(186) shouldBe MotionSegment(Bezier, 536)
      segments(187) shouldBe MotionSegment(Bezier, 539)
      segments(188) shouldBe MotionSegment(Bezier, 542)
      segments(189) shouldBe MotionSegment(Bezier, 545)
      segments(190) shouldBe MotionSegment(Bezier, 548)
      segments(191) shouldBe MotionSegment(Linear, 551)
      segments(192) shouldBe MotionSegment(InverseStepped, 553)
      segments(193) shouldBe MotionSegment(Linear, 554)
      segments(194) shouldBe MotionSegment(Stepped, 556)
      segments(195) shouldBe MotionSegment(Linear, 557)
      segments(196) shouldBe MotionSegment(Stepped, 559)
      segments(197) shouldBe MotionSegment(Linear, 560)
      segments(198) shouldBe MotionSegment(Stepped, 562)
      segments(199) shouldBe MotionSegment(Linear, 563)
      segments(200) shouldBe MotionSegment(Stepped, 565)
      segments(201) shouldBe MotionSegment(Linear, 566)
      segments(202) shouldBe MotionSegment(Stepped, 568)
      segments(203) shouldBe MotionSegment(Linear, 569)
      segments(204) shouldBe MotionSegment(Stepped, 571)
      segments(205) shouldBe MotionSegment(Linear, 572)
      segments(206) shouldBe MotionSegment(Stepped, 574)
      segments(207) shouldBe MotionSegment(Linear, 575)
      segments(208) shouldBe MotionSegment(Stepped, 577)
      segments(209) shouldBe MotionSegment(Linear, 578)
      segments(210) shouldBe MotionSegment(Stepped, 580)
      segments(211) shouldBe MotionSegment(Linear, 581)
      segments(212) shouldBe MotionSegment(Stepped, 583)
      segments(213) shouldBe MotionSegment(Linear, 584)
      segments(214) shouldBe MotionSegment(Stepped, 586)
      segments(215) shouldBe MotionSegment(Linear, 587)
      segments(216) shouldBe MotionSegment(Stepped, 589)
      segments(217) shouldBe MotionSegment(Linear, 590)
      segments(218) shouldBe MotionSegment(Stepped, 592)
      segments(219) shouldBe MotionSegment(Linear, 593)
      segments(220) shouldBe MotionSegment(Stepped, 595)
      segments(221) shouldBe MotionSegment(Linear, 596)
      segments(222) shouldBe MotionSegment(Stepped, 598)
      segments(223) shouldBe MotionSegment(Linear, 599)

      assertPointList("src/test/resources/expectation/markMotionIdle3Points.csv", motionData.pointsList)
    }

    Scenario("Load motion from avatar Hiyori") {
      Given("A folder path contains json files for a Live2D avatar model")
      val folderPath = "src/test/resources/models/Hiyori"

      When("Create a MotionData from this Live2D avatar settings")
      val jsonSettingsReader = new JsonSettingsReader(folderPath)
      val settings: Settings = jsonSettingsReader.loadSettings().success.value
      val motionData = new AvatarMotionDataReader(settings.motionGroups("idle")(0)).loadMotionData()

      motionData.fps shouldBe 30.0
      motionData.isLoop shouldBe true
      motionData.curveCount shouldBe 31
      motionData.duration shouldBe 4.7f

      val curves = motionData.curvesList
      curves.size shouldBe 31
      curves(0) shouldBe MotionCurve("ParamAngleX", Parameter, 10, 0, 0.2f, -1.0f)
      curves(1) shouldBe MotionCurve("ParamAngleY", Parameter, 12, 10, -1.0f, 0.3f)
      curves(2) shouldBe MotionCurve("ParamAngleZ", Parameter, 9, 22, 0.4f, 0.5f)
      curves(3) shouldBe MotionCurve("ParamCheek", Parameter, 1, 31, -1.0f, -1.0f)
      curves(4) shouldBe MotionCurve("ParamEyeLOpen", Parameter, 9, 32, -1.0f, -1.0f)
      curves(5) shouldBe MotionCurve("ParamEyeLSmile", Parameter, 1, 41, -1.0f, -1.0f)
      curves(6) shouldBe MotionCurve("ParamEyeROpen", Parameter, 9, 42, -1.0f, -1.0f)
      curves(7) shouldBe MotionCurve("ParamEyeRSmile", Parameter, 1, 51, -1.0f, -1.0f)
      curves(8) shouldBe MotionCurve("ParamEyeBallX", Parameter, 7, 52, -1.0f, -1.0f)
      curves(9) shouldBe MotionCurve("ParamEyeBallY", Parameter, 7, 59, -1.0f, -1.0f)
      curves(10) shouldBe MotionCurve("ParamBrowLY", Parameter, 1, 66, -1.0f, -1.0f)
      curves(11) shouldBe MotionCurve("ParamBrowRY", Parameter, 1, 67, -1.0f, -1.0f)
      curves(12) shouldBe MotionCurve("ParamBrowLX", Parameter, 1, 68, -1.0f, -1.0f)
      curves(13) shouldBe MotionCurve("ParamBrowRX", Parameter, 1, 69, -1.0f, -1.0f)
      curves(14) shouldBe MotionCurve("ParamBrowLAngle", Parameter, 1, 70, -1.0f, -1.0f)
      curves(15) shouldBe MotionCurve("ParamBrowRAngle", Parameter, 1, 71, -1.0f, -1.0f)
      curves(16) shouldBe MotionCurve("ParamBrowLForm", Parameter, 1, 72, -1.0f, -1.0f)
      curves(17) shouldBe MotionCurve("ParamBrowRForm", Parameter, 1, 73, -1.0f, -1.0f)
      curves(18) shouldBe MotionCurve("ParamMouthForm", Parameter, 1, 74, -1.0f, -1.0f)
      curves(19) shouldBe MotionCurve("ParamMouthOpenY", Parameter, 1, 75, -1.0f, -1.0f)
      curves(20) shouldBe MotionCurve("ParamBodyAngleX", Parameter, 4, 76, -1.0f, -1.0f)
      curves(21) shouldBe MotionCurve("ParamBodyAngleY", Parameter, 12, 80, -1.0f, -1.0f)
      curves(22) shouldBe MotionCurve("ParamBodyAngleZ", Parameter, 5, 92, -1.0f, -1.0f)
      curves(23) shouldBe MotionCurve("ParamBreath", Parameter, 1, 97, -1.0f, -1.0f)
      curves(24) shouldBe MotionCurve("ParamShoulder", Parameter, 6, 98, -1.0f, -1.0f)
      curves(25) shouldBe MotionCurve("ParamLeg", Parameter, 1, 104, -1.0f, -1.0f)
      curves(26) shouldBe MotionCurve("ParamArmLA", Parameter, 8, 105, -1.0f, -1.0f)
      curves(27) shouldBe MotionCurve("ParamArmRA", Parameter, 8, 113, -1.0f, -1.0f)
      curves(28) shouldBe MotionCurve("ParamHairAhoge", Parameter, 12, 121, -1.0f, -1.0f)
      curves(29) shouldBe MotionCurve("PartArmA", PartOpacity, 1, 133, -1.0f, -1.0f)
      curves(30) shouldBe MotionCurve("PartArmB", PartOpacity, 0, 134, -1.0f, -1.0f)

      val segments = motionData.segmentsList
      segments.size shouldBe 134
      segments(0) shouldBe MotionSegment(BezierCardanoInterpretation, 0)
      segments(1) shouldBe MotionSegment(BezierCardanoInterpretation, 3)
      segments(2) shouldBe MotionSegment(BezierCardanoInterpretation, 6)
      segments(3) shouldBe MotionSegment(BezierCardanoInterpretation, 9)
      segments(4) shouldBe MotionSegment(BezierCardanoInterpretation, 12)
      segments(5) shouldBe MotionSegment(BezierCardanoInterpretation, 15)
      segments(6) shouldBe MotionSegment(BezierCardanoInterpretation, 18)
      segments(7) shouldBe MotionSegment(BezierCardanoInterpretation, 21)
      segments(8) shouldBe MotionSegment(BezierCardanoInterpretation, 24)
      segments(9) shouldBe MotionSegment(Linear, 27)
      segments(10) shouldBe MotionSegment(BezierCardanoInterpretation, 29)
      segments(11) shouldBe MotionSegment(BezierCardanoInterpretation, 32)
      segments(12) shouldBe MotionSegment(BezierCardanoInterpretation, 35)
      segments(13) shouldBe MotionSegment(BezierCardanoInterpretation, 38)
      segments(14) shouldBe MotionSegment(BezierCardanoInterpretation, 41)
      segments(15) shouldBe MotionSegment(BezierCardanoInterpretation, 44)
      segments(16) shouldBe MotionSegment(BezierCardanoInterpretation, 47)
      segments(17) shouldBe MotionSegment(BezierCardanoInterpretation, 50)
      segments(18) shouldBe MotionSegment(BezierCardanoInterpretation, 53)
      segments(19) shouldBe MotionSegment(BezierCardanoInterpretation, 56)
      segments(20) shouldBe MotionSegment(BezierCardanoInterpretation, 59)
      segments(21) shouldBe MotionSegment(Linear, 62)
      segments(22) shouldBe MotionSegment(BezierCardanoInterpretation, 64)
      segments(23) shouldBe MotionSegment(BezierCardanoInterpretation, 67)
      segments(24) shouldBe MotionSegment(BezierCardanoInterpretation, 70)
      segments(25) shouldBe MotionSegment(BezierCardanoInterpretation, 73)
      segments(26) shouldBe MotionSegment(BezierCardanoInterpretation, 76)
      segments(27) shouldBe MotionSegment(BezierCardanoInterpretation, 79)
      segments(28) shouldBe MotionSegment(BezierCardanoInterpretation, 82)
      segments(29) shouldBe MotionSegment(BezierCardanoInterpretation, 85)
      segments(30) shouldBe MotionSegment(Linear, 88)
      segments(31) shouldBe MotionSegment(Linear, 90)
      segments(32) shouldBe MotionSegment(BezierCardanoInterpretation, 92)
      segments(33) shouldBe MotionSegment(BezierCardanoInterpretation, 95)
      segments(34) shouldBe MotionSegment(BezierCardanoInterpretation, 98)
      segments(35) shouldBe MotionSegment(BezierCardanoInterpretation, 101)
      segments(36) shouldBe MotionSegment(BezierCardanoInterpretation, 104)
      segments(37) shouldBe MotionSegment(BezierCardanoInterpretation, 107)
      segments(38) shouldBe MotionSegment(BezierCardanoInterpretation, 110)
      segments(39) shouldBe MotionSegment(BezierCardanoInterpretation, 113)
      segments(40) shouldBe MotionSegment(Linear, 116)
      segments(41) shouldBe MotionSegment(Linear, 118)
      segments(42) shouldBe MotionSegment(BezierCardanoInterpretation, 120)
      segments(43) shouldBe MotionSegment(BezierCardanoInterpretation, 123)
      segments(44) shouldBe MotionSegment(BezierCardanoInterpretation, 126)
      segments(45) shouldBe MotionSegment(BezierCardanoInterpretation, 129)
      segments(46) shouldBe MotionSegment(BezierCardanoInterpretation, 132)
      segments(47) shouldBe MotionSegment(BezierCardanoInterpretation, 135)
      segments(48) shouldBe MotionSegment(BezierCardanoInterpretation, 138)
      segments(49) shouldBe MotionSegment(BezierCardanoInterpretation, 141)
      segments(50) shouldBe MotionSegment(Linear, 144)
      segments(51) shouldBe MotionSegment(Linear, 146)
      segments(52) shouldBe MotionSegment(BezierCardanoInterpretation, 148)
      segments(53) shouldBe MotionSegment(BezierCardanoInterpretation, 151)
      segments(54) shouldBe MotionSegment(BezierCardanoInterpretation, 154)
      segments(55) shouldBe MotionSegment(BezierCardanoInterpretation, 157)
      segments(56) shouldBe MotionSegment(BezierCardanoInterpretation, 160)
      segments(57) shouldBe MotionSegment(BezierCardanoInterpretation, 163)
      segments(58) shouldBe MotionSegment(Linear, 166)
      segments(59) shouldBe MotionSegment(BezierCardanoInterpretation, 168)
      segments(60) shouldBe MotionSegment(BezierCardanoInterpretation, 171)
      segments(61) shouldBe MotionSegment(BezierCardanoInterpretation, 174)
      segments(62) shouldBe MotionSegment(BezierCardanoInterpretation, 177)
      segments(63) shouldBe MotionSegment(BezierCardanoInterpretation, 180)
      segments(64) shouldBe MotionSegment(BezierCardanoInterpretation, 183)
      segments(65) shouldBe MotionSegment(Linear, 186)
      segments(66) shouldBe MotionSegment(Linear, 188)
      segments(67) shouldBe MotionSegment(Linear, 190)
      segments(68) shouldBe MotionSegment(Linear, 192)
      segments(69) shouldBe MotionSegment(Linear, 194)
      segments(70) shouldBe MotionSegment(Linear, 196)
      segments(71) shouldBe MotionSegment(Linear, 198)
      segments(72) shouldBe MotionSegment(Linear, 200)
      segments(73) shouldBe MotionSegment(Linear, 202)
      segments(74) shouldBe MotionSegment(Linear, 204)
      segments(75) shouldBe MotionSegment(Linear, 206)
      segments(76) shouldBe MotionSegment(BezierCardanoInterpretation, 208)
      segments(77) shouldBe MotionSegment(BezierCardanoInterpretation, 211)
      segments(78) shouldBe MotionSegment(BezierCardanoInterpretation, 214)
      segments(79) shouldBe MotionSegment(Linear, 217)
      segments(80) shouldBe MotionSegment(BezierCardanoInterpretation, 219)
      segments(81) shouldBe MotionSegment(BezierCardanoInterpretation, 222)
      segments(82) shouldBe MotionSegment(BezierCardanoInterpretation, 225)
      segments(83) shouldBe MotionSegment(BezierCardanoInterpretation, 228)
      segments(84) shouldBe MotionSegment(BezierCardanoInterpretation, 231)
      segments(85) shouldBe MotionSegment(BezierCardanoInterpretation, 234)
      segments(86) shouldBe MotionSegment(BezierCardanoInterpretation, 237)
      segments(87) shouldBe MotionSegment(BezierCardanoInterpretation, 240)
      segments(88) shouldBe MotionSegment(BezierCardanoInterpretation, 243)
      segments(89) shouldBe MotionSegment(BezierCardanoInterpretation, 246)
      segments(90) shouldBe MotionSegment(BezierCardanoInterpretation, 249)
      segments(91) shouldBe MotionSegment(Linear, 252)
      segments(92) shouldBe MotionSegment(BezierCardanoInterpretation, 254)
      segments(93) shouldBe MotionSegment(BezierCardanoInterpretation, 257)
      segments(94) shouldBe MotionSegment(BezierCardanoInterpretation, 260)
      segments(95) shouldBe MotionSegment(BezierCardanoInterpretation, 263)
      segments(96) shouldBe MotionSegment(Linear, 266)
      segments(97) shouldBe MotionSegment(Linear, 268)
      segments(98) shouldBe MotionSegment(BezierCardanoInterpretation, 270)
      segments(99) shouldBe MotionSegment(BezierCardanoInterpretation, 273)
      segments(100) shouldBe MotionSegment(BezierCardanoInterpretation, 276)
      segments(101) shouldBe MotionSegment(BezierCardanoInterpretation, 279)
      segments(102) shouldBe MotionSegment(BezierCardanoInterpretation, 282)
      segments(103) shouldBe MotionSegment(Linear, 285)
      segments(104) shouldBe MotionSegment(Linear, 287)
      segments(105) shouldBe MotionSegment(BezierCardanoInterpretation, 289)
      segments(106) shouldBe MotionSegment(BezierCardanoInterpretation, 292)
      segments(107) shouldBe MotionSegment(BezierCardanoInterpretation, 295)
      segments(108) shouldBe MotionSegment(BezierCardanoInterpretation, 298)
      segments(109) shouldBe MotionSegment(BezierCardanoInterpretation, 301)
      segments(110) shouldBe MotionSegment(BezierCardanoInterpretation, 304)
      segments(111) shouldBe MotionSegment(BezierCardanoInterpretation, 307)
      segments(112) shouldBe MotionSegment(Linear, 310)
      segments(113) shouldBe MotionSegment(BezierCardanoInterpretation, 312)
      segments(114) shouldBe MotionSegment(BezierCardanoInterpretation, 315)
      segments(115) shouldBe MotionSegment(BezierCardanoInterpretation, 318)
      segments(116) shouldBe MotionSegment(BezierCardanoInterpretation, 321)
      segments(117) shouldBe MotionSegment(BezierCardanoInterpretation, 324)
      segments(118) shouldBe MotionSegment(BezierCardanoInterpretation, 327)
      segments(119) shouldBe MotionSegment(BezierCardanoInterpretation, 330)
      segments(120) shouldBe MotionSegment(Linear, 333)
      segments(121) shouldBe MotionSegment(BezierCardanoInterpretation, 335)
      segments(122) shouldBe MotionSegment(BezierCardanoInterpretation, 338)
      segments(123) shouldBe MotionSegment(BezierCardanoInterpretation, 341)
      segments(124) shouldBe MotionSegment(BezierCardanoInterpretation, 344)
      segments(125) shouldBe MotionSegment(BezierCardanoInterpretation, 347)
      segments(126) shouldBe MotionSegment(BezierCardanoInterpretation, 350)
      segments(127) shouldBe MotionSegment(BezierCardanoInterpretation, 353)
      segments(128) shouldBe MotionSegment(BezierCardanoInterpretation, 356)
      segments(129) shouldBe MotionSegment(BezierCardanoInterpretation, 359)
      segments(130) shouldBe MotionSegment(BezierCardanoInterpretation, 362)
      segments(131) shouldBe MotionSegment(BezierCardanoInterpretation, 365)
      segments(132) shouldBe MotionSegment(Linear, 368)
      segments(133) shouldBe MotionSegment(Linear, 370)

      assertPointList("src/test/resources/expectation/hiyoriMotionIdle0Points.csv", motionData.pointsList)
    }
  }

  private def assertPointList(expectationFile: String, points: List[MotionPoint]): Unit = {
    val source = Source.fromFile(expectationFile)
    val testData = Using.resource(source) { source => source.getLines().toList.drop(1) }
    points.size shouldBe testData.size
    testData.zipWithIndex.foreach { case (line, index) =>
      val Array(time, value) = line.split("\\s+")
      withClue(s"$expectationFile[$index]") {
        points(index) shouldBe MotionPoint(time.toFloat, value.toFloat)
      }
    }
  }
}
