name: "Run Unit Test And Coverage Report"
runs:
  using: "composite"
  steps:
    - name: "Setup Git Information"
      shell: bash
      run: |
        git config --global user.email "brianhsu.hsu+githu@gmail.com"
        git config --global user.name "GitHub Action"

    - name: "Prepare Building Environment"
      shell: bash
      run: |
          apt-get update -yqq
          apt-get install apt-transport-https -yqq
          echo "deb https://repo.scala-sbt.org/scalasbt/debian all main" | tee /etc/apt/sources.list.d/sbt.list
          echo "deb https://repo.scala-sbt.org/scalasbt/debian /" | tee /etc/apt/sources.list.d/sbt_old.list
          curl -sL "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x2EE0EA64E40A89B84B2DF73499E82A75642AC823" | apt-key add
          apt-get update
          apt-get -y install sbt
          apt-get -y install xorg-dev libglu1-mesa libgl1-mesa-dev xvfb libxinerama1 libxcursor1 libswt-gtk-4-java libswt-gtk-4-jni libxml2-utils bc zip
    
    - name: "Run Unit Test and Coverage Report"
      shell: bash
      run: |
        ./distclean
        xvfb-run --auto-servernum sbt coverage test coverageAggregate

    - name: "Archive Test Reports"
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: target/test-reports-html/


