name: "Run Unit Test And Coverage Report"
runs:
  using: "composite"
  steps:
    - name: "Setup Git Information"
      shell: bash
      run: |
        git config --global user.email "brianhsu.hsu+githu@gmail.com"
        git config --global user.name "GitHub Action"
   
    - name: "Run Unit Test and Coverage Report"
      shell: bash
      run: |
        ./distclean
        xvfb-run --auto-servernum sbt coverage test coverageAggregate

    - name: "Export Coverage Rate"
      shell: bash
      run: |
        echo "COVERAGE_RATE=$(xmllint --xpath "string(/scoverage/@branch-rate)" target/scala-2.13/scoverage-report/scoverage.xml)" >> "$GITHUB_ENV"

    - name: "Archive Test Results"
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: target/test-reports-html/

