package moe.brianhsu.porting.live2d.temp

import moe.brianhsu.live2d.adapter.gateway.avatar.settings.json.JsonSettingsReader
import moe.brianhsu.live2d.enitiy.avatar.settings.Settings
import moe.brianhsu.porting.live2d.framework.CubismMotionCurveTarget.{Model, Parameter, PartOpacity}
import moe.brianhsu.porting.live2d.framework.CubismMotionSegment.{BezierEvaluate, BezierEvaluateCardanoInterpretation, LinearEvaluate}
import moe.brianhsu.porting.live2d.framework.{CubismMotionCurve, CubismMotionCurveTarget, CubismMotionData, CubismMotionSegment}
import org.json4s.{DefaultFormats, Formats, ShortTypeHints}
import org.scalatest.featurespec.AnyFeatureSpec
import org.scalatest.matchers.should.Matchers
import org.scalatest.{GivenWhenThen, TryValues}

class MotionDataFeature extends AnyFeatureSpec with GivenWhenThen with Matchers with TryValues {
  Feature("Read pose parts data from Live2D avatar settings") {

    Scenario("Load motion idle[0] from avatar Mark") {
      Given("A folder path contains json files for a Live2D avatar model")
      val folderPath = "src/test/resources/models/Mark"

      When("Create a MotionData from this Live2D avatar settings")
      val jsonSettingsReader = new JsonSettingsReader(folderPath)
      val settings: Settings = jsonSettingsReader.loadSettings().success.value
      val motionData = CubismMotionData.apply(settings.motionGroups("idle")(0))

      motionData.fps shouldBe 30.0
      motionData.isLoop shouldBe true
      motionData.curveCount shouldBe 37
      motionData.duration shouldBe 10.4f
      motionData.curvesList should contain theSameElementsInOrderAs List(
        CubismMotionCurve("Opacity", Model, 1, 0, -1.0f, -1.0f),
        CubismMotionCurve("EyeBlink", Model, 9, 1, -1.0f, -1.0f),
        CubismMotionCurve("ParamAngleX", Parameter, 16, 10, -1.0f, -1.0f),
        CubismMotionCurve("ParamAngleY", Parameter, 32, 26, -1.0f, -1.0f),
        CubismMotionCurve("ParamAngleZ", Parameter, 17, 58, -1.0f, -1.0f),
        CubismMotionCurve("ParamEyeBallX", Parameter, 21, 75, -1.0f, -1.0f),
        CubismMotionCurve("ParamEyeBallY", Parameter, 21, 96, -1.0f, -1.0f),
        CubismMotionCurve("ParamBrowLY", Parameter, 16, 117, -1.0f, -1.0f),
        CubismMotionCurve("ParamBrowRY", Parameter, 16, 133, -1.0f, -1.0f),
        CubismMotionCurve("ParamMouthOpenY", Parameter, 16, 149, -1.0f, -1.0f),
        CubismMotionCurve("ParamArmL", Parameter, 32, 165, -1.0f, -1.0f),
        CubismMotionCurve("ParamArmR", Parameter, 32, 197, -1.0f, -1.0f),
        CubismMotionCurve("ParamLeftLeg", Parameter, 16, 229, -1.0f, -1.0f),
        CubismMotionCurve("ParamRightLeg", Parameter, 16, 245, -1.0f, -1.0f),
        CubismMotionCurve("ParamBodyAngleX", Parameter, 16, 261, -1.0f, -1.0f),
        CubismMotionCurve("ParamBodyAngleY", Parameter, 32, 277, -1.0f, -1.0f),
        CubismMotionCurve("ParamBodyAngleZ", Parameter, 16, 309, -1.0f, -1.0f),
        CubismMotionCurve("ParamBreath", Parameter, 16, 325, -1.0f, -1.0f),
        CubismMotionCurve("ParamHairFront", Parameter, 16, 341, -1.0f, -1.0f),
        CubismMotionCurve("ParamHairSide", Parameter, 16, 357, -1.0f, -1.0f),
        CubismMotionCurve("ParamHairBack", Parameter, 16, 373, -1.0f, -1.0f),
        CubismMotionCurve("PartHead", PartOpacity, 1, 389, -1.0f, -1.0f),
        CubismMotionCurve("PartHairFront", PartOpacity, 1, 390, -1.0f, -1.0f),
        CubismMotionCurve("PartEyeL", PartOpacity, 1, 391, -1.0f, -1.0f),
        CubismMotionCurve("PartEyeBallL", PartOpacity, 1, 392, -1.0f, -1.0f),
        CubismMotionCurve("PartEyeWhiteL", PartOpacity, 1, 393, -1.0f, -1.0f),
        CubismMotionCurve("PartEyeR", PartOpacity, 1, 394, -1.0f, -1.0f),
        CubismMotionCurve("PartEyeBallR", PartOpacity, 1, 395, -1.0f, -1.0f),
        CubismMotionCurve("PartEyeWhiteR", PartOpacity, 1, 396, -1.0f, -1.0f),
        CubismMotionCurve("PartHairSide", PartOpacity, 1, 397, -1.0f, -1.0f),
        CubismMotionCurve("PartMouth", PartOpacity, 1, 398, -1.0f, -1.0f),
        CubismMotionCurve("PartOral", PartOpacity, 1, 399, -1.0f, -1.0f),
        CubismMotionCurve("PartFace", PartOpacity, 1, 400, -1.0f, -1.0f),
        CubismMotionCurve("PartBody", PartOpacity, 1, 401, -1.0f, -1.0f),
        CubismMotionCurve("PartArmL", PartOpacity, 1, 402, -1.0f, -1.0f),
        CubismMotionCurve("PartArmR", PartOpacity, 1, 403, -1.0f, -1.0f),
        CubismMotionCurve("PartHairBack", PartOpacity, 1, 404, -1.0f, -1.0f)
      )
      val seg = motionData.segmentsList
      seg(0) shouldBe CubismMotionSegment(LinearEvaluate,0,0)
      seg(1) shouldBe CubismMotionSegment(BezierEvaluate,2,1)
      seg(2) shouldBe CubismMotionSegment(BezierEvaluate,5,1)
      seg(3) shouldBe CubismMotionSegment(BezierEvaluate,8,1)
      seg(4) shouldBe CubismMotionSegment(BezierEvaluate,11,1)
      seg(5) shouldBe CubismMotionSegment(BezierEvaluate,14,1)
      seg(6) shouldBe CubismMotionSegment(BezierEvaluate,17,1)
      seg(7) shouldBe CubismMotionSegment(BezierEvaluate,20,1)
      seg(8) shouldBe CubismMotionSegment(BezierEvaluate,23,1)
      seg(9) shouldBe CubismMotionSegment(LinearEvaluate,26,0)
      seg(10) shouldBe CubismMotionSegment(BezierEvaluate,28,1)
      seg(11) shouldBe CubismMotionSegment(BezierEvaluate,31,1)
      seg(12) shouldBe CubismMotionSegment(BezierEvaluate,34,1)
      seg(13) shouldBe CubismMotionSegment(BezierEvaluate,37,1)
      seg(14) shouldBe CubismMotionSegment(BezierEvaluate,40,1)
      seg(15) shouldBe CubismMotionSegment(BezierEvaluate,43,1)
      seg(16) shouldBe CubismMotionSegment(BezierEvaluate,46,1)
      seg(17) shouldBe CubismMotionSegment(BezierEvaluate,49,1)
      seg(18) shouldBe CubismMotionSegment(BezierEvaluate,52,1)
      seg(19) shouldBe CubismMotionSegment(BezierEvaluate,55,1)
      seg(20) shouldBe CubismMotionSegment(BezierEvaluate,58,1)
      seg(21) shouldBe CubismMotionSegment(BezierEvaluate,61,1)
      seg(22) shouldBe CubismMotionSegment(BezierEvaluate,64,1)
      seg(23) shouldBe CubismMotionSegment(BezierEvaluate,67,1)
      seg(24) shouldBe CubismMotionSegment(BezierEvaluate,70,1)
      seg(25) shouldBe CubismMotionSegment(BezierEvaluate,73,1)
      seg(26) shouldBe CubismMotionSegment(BezierEvaluate,77,1)
      seg(27) shouldBe CubismMotionSegment(BezierEvaluate,80,1)
      seg(28) shouldBe CubismMotionSegment(BezierEvaluate,83,1)
      seg(29) shouldBe CubismMotionSegment(BezierEvaluate,86,1)
      seg(30) shouldBe CubismMotionSegment(BezierEvaluate,89,1)
      seg(31) shouldBe CubismMotionSegment(BezierEvaluate,92,1)
      seg(32) shouldBe CubismMotionSegment(BezierEvaluate,95,1)
      seg(33) shouldBe CubismMotionSegment(BezierEvaluate,98,1)
      seg(34) shouldBe CubismMotionSegment(BezierEvaluate,101,1)
      seg(35) shouldBe CubismMotionSegment(BezierEvaluate,104,1)
      seg(36) shouldBe CubismMotionSegment(BezierEvaluate,107,1)
      seg(37) shouldBe CubismMotionSegment(BezierEvaluate,110,1)
      seg(38) shouldBe CubismMotionSegment(BezierEvaluate,113,1)
      seg(39) shouldBe CubismMotionSegment(BezierEvaluate,116,1)
      seg(40) shouldBe CubismMotionSegment(BezierEvaluate,119,1)
      seg(41) shouldBe CubismMotionSegment(BezierEvaluate,122,1)
      seg(42) shouldBe CubismMotionSegment(BezierEvaluate,125,1)
      seg(43) shouldBe CubismMotionSegment(BezierEvaluate,128,1)
      seg(44) shouldBe CubismMotionSegment(BezierEvaluate,131,1)
      seg(45) shouldBe CubismMotionSegment(BezierEvaluate,134,1)
      seg(46) shouldBe CubismMotionSegment(BezierEvaluate,137,1)
      seg(47) shouldBe CubismMotionSegment(BezierEvaluate,140,1)
      seg(48) shouldBe CubismMotionSegment(BezierEvaluate,143,1)
      seg(49) shouldBe CubismMotionSegment(BezierEvaluate,146,1)
      seg(50) shouldBe CubismMotionSegment(BezierEvaluate,149,1)
      seg(51) shouldBe CubismMotionSegment(BezierEvaluate,152,1)
      seg(52) shouldBe CubismMotionSegment(BezierEvaluate,155,1)
      seg(53) shouldBe CubismMotionSegment(BezierEvaluate,158,1)
      seg(54) shouldBe CubismMotionSegment(BezierEvaluate,161,1)
      seg(55) shouldBe CubismMotionSegment(BezierEvaluate,164,1)
      seg(56) shouldBe CubismMotionSegment(BezierEvaluate,167,1)
      seg(57) shouldBe CubismMotionSegment(BezierEvaluate,170,1)
      seg(58) shouldBe CubismMotionSegment(BezierEvaluate,174,1)
      seg(59) shouldBe CubismMotionSegment(BezierEvaluate,177,1)
      seg(60) shouldBe CubismMotionSegment(BezierEvaluate,180,1)
      seg(61) shouldBe CubismMotionSegment(BezierEvaluate,183,1)
      seg(62) shouldBe CubismMotionSegment(BezierEvaluate,186,1)
      seg(63) shouldBe CubismMotionSegment(BezierEvaluate,189,1)
      seg(64) shouldBe CubismMotionSegment(BezierEvaluate,192,1)
      seg(65) shouldBe CubismMotionSegment(BezierEvaluate,195,1)
      seg(66) shouldBe CubismMotionSegment(BezierEvaluate,198,1)
      seg(67) shouldBe CubismMotionSegment(BezierEvaluate,201,1)
      seg(68) shouldBe CubismMotionSegment(BezierEvaluate,204,1)
      seg(69) shouldBe CubismMotionSegment(BezierEvaluate,207,1)
      seg(70) shouldBe CubismMotionSegment(BezierEvaluate,210,1)
      seg(71) shouldBe CubismMotionSegment(BezierEvaluate,213,1)
      seg(72) shouldBe CubismMotionSegment(BezierEvaluate,216,1)
      seg(73) shouldBe CubismMotionSegment(BezierEvaluate,219,1)
      seg(74) shouldBe CubismMotionSegment(BezierEvaluate,222,1)
      seg(75) shouldBe CubismMotionSegment(BezierEvaluate,226,1)
      seg(76) shouldBe CubismMotionSegment(BezierEvaluate,229,1)
      seg(77) shouldBe CubismMotionSegment(BezierEvaluate,232,1)
      seg(78) shouldBe CubismMotionSegment(BezierEvaluate,235,1)
      seg(79) shouldBe CubismMotionSegment(BezierEvaluate,238,1)
      seg(80) shouldBe CubismMotionSegment(BezierEvaluate,241,1)
      seg(81) shouldBe CubismMotionSegment(BezierEvaluate,244,1)
      seg(82) shouldBe CubismMotionSegment(BezierEvaluate,247,1)
      seg(83) shouldBe CubismMotionSegment(BezierEvaluate,250,1)
      seg(84) shouldBe CubismMotionSegment(BezierEvaluate,253,1)
      seg(85) shouldBe CubismMotionSegment(BezierEvaluate,256,1)
      seg(86) shouldBe CubismMotionSegment(BezierEvaluate,259,1)
      seg(87) shouldBe CubismMotionSegment(BezierEvaluate,262,1)
      seg(88) shouldBe CubismMotionSegment(BezierEvaluate,265,1)
      seg(89) shouldBe CubismMotionSegment(BezierEvaluate,268,1)
      seg(90) shouldBe CubismMotionSegment(BezierEvaluate,271,1)
      seg(91) shouldBe CubismMotionSegment(BezierEvaluate,274,1)
      seg(92) shouldBe CubismMotionSegment(BezierEvaluate,277,1)
      seg(93) shouldBe CubismMotionSegment(BezierEvaluate,280,1)
      seg(94) shouldBe CubismMotionSegment(BezierEvaluate,283,1)
      seg(95) shouldBe CubismMotionSegment(BezierEvaluate,286,1)
      seg(96) shouldBe CubismMotionSegment(BezierEvaluate,290,1)
      seg(97) shouldBe CubismMotionSegment(BezierEvaluate,293,1)
      seg(98) shouldBe CubismMotionSegment(BezierEvaluate,296,1)
      seg(99) shouldBe CubismMotionSegment(BezierEvaluate,299,1)
      seg(100) shouldBe CubismMotionSegment(BezierEvaluate,302,1)
      seg(101) shouldBe CubismMotionSegment(BezierEvaluate,305,1)
      seg(102) shouldBe CubismMotionSegment(BezierEvaluate,308,1)
      seg(103) shouldBe CubismMotionSegment(BezierEvaluate,311,1)
      seg(104) shouldBe CubismMotionSegment(BezierEvaluate,314,1)
      seg(105) shouldBe CubismMotionSegment(BezierEvaluate,317,1)
      seg(106) shouldBe CubismMotionSegment(BezierEvaluate,320,1)
      seg(107) shouldBe CubismMotionSegment(BezierEvaluate,323,1)
      seg(108) shouldBe CubismMotionSegment(BezierEvaluate,326,1)
      seg(109) shouldBe CubismMotionSegment(BezierEvaluate,329,1)
      seg(110) shouldBe CubismMotionSegment(BezierEvaluate,332,1)
      seg(111) shouldBe CubismMotionSegment(BezierEvaluate,335,1)
      seg(112) shouldBe CubismMotionSegment(BezierEvaluate,338,1)
      seg(113) shouldBe CubismMotionSegment(BezierEvaluate,341,1)
      seg(114) shouldBe CubismMotionSegment(BezierEvaluate,344,1)
      seg(115) shouldBe CubismMotionSegment(BezierEvaluate,347,1)
      seg(116) shouldBe CubismMotionSegment(BezierEvaluate,350,1)
      seg(117) shouldBe CubismMotionSegment(BezierEvaluate,354,1)
      seg(118) shouldBe CubismMotionSegment(BezierEvaluate,357,1)
      seg(119) shouldBe CubismMotionSegment(BezierEvaluate,360,1)
      seg(120) shouldBe CubismMotionSegment(BezierEvaluate,363,1)
      seg(121) shouldBe CubismMotionSegment(BezierEvaluate,366,1)
      seg(122) shouldBe CubismMotionSegment(BezierEvaluate,369,1)
      seg(123) shouldBe CubismMotionSegment(BezierEvaluate,372,1)
      seg(124) shouldBe CubismMotionSegment(BezierEvaluate,375,1)
      seg(125) shouldBe CubismMotionSegment(BezierEvaluate,378,1)
      seg(126) shouldBe CubismMotionSegment(BezierEvaluate,381,1)
      seg(127) shouldBe CubismMotionSegment(BezierEvaluate,384,1)
      seg(128) shouldBe CubismMotionSegment(BezierEvaluate,387,1)
      seg(129) shouldBe CubismMotionSegment(BezierEvaluate,390,1)
      seg(130) shouldBe CubismMotionSegment(BezierEvaluate,393,1)
      seg(131) shouldBe CubismMotionSegment(BezierEvaluate,396,1)
      seg(132) shouldBe CubismMotionSegment(BezierEvaluate,399,1)
      seg(133) shouldBe CubismMotionSegment(BezierEvaluate,403,1)
      seg(134) shouldBe CubismMotionSegment(BezierEvaluate,406,1)
      seg(135) shouldBe CubismMotionSegment(BezierEvaluate,409,1)
      seg(136) shouldBe CubismMotionSegment(BezierEvaluate,412,1)
      seg(137) shouldBe CubismMotionSegment(BezierEvaluate,415,1)
      seg(138) shouldBe CubismMotionSegment(BezierEvaluate,418,1)
      seg(139) shouldBe CubismMotionSegment(BezierEvaluate,421,1)
      seg(140) shouldBe CubismMotionSegment(BezierEvaluate,424,1)
      seg(141) shouldBe CubismMotionSegment(BezierEvaluate,427,1)
      seg(142) shouldBe CubismMotionSegment(BezierEvaluate,430,1)
      seg(143) shouldBe CubismMotionSegment(BezierEvaluate,433,1)
      seg(144) shouldBe CubismMotionSegment(BezierEvaluate,436,1)
      seg(145) shouldBe CubismMotionSegment(BezierEvaluate,439,1)
      seg(146) shouldBe CubismMotionSegment(BezierEvaluate,442,1)
      seg(147) shouldBe CubismMotionSegment(BezierEvaluate,445,1)
      seg(148) shouldBe CubismMotionSegment(BezierEvaluate,448,1)
      seg(149) shouldBe CubismMotionSegment(BezierEvaluate,452,1)
      seg(150) shouldBe CubismMotionSegment(BezierEvaluate,455,1)
      seg(151) shouldBe CubismMotionSegment(BezierEvaluate,458,1)
      seg(152) shouldBe CubismMotionSegment(BezierEvaluate,461,1)
      seg(153) shouldBe CubismMotionSegment(BezierEvaluate,464,1)
      seg(154) shouldBe CubismMotionSegment(BezierEvaluate,467,1)
      seg(155) shouldBe CubismMotionSegment(BezierEvaluate,470,1)
      seg(156) shouldBe CubismMotionSegment(BezierEvaluate,473,1)
      seg(157) shouldBe CubismMotionSegment(BezierEvaluate,476,1)
      seg(158) shouldBe CubismMotionSegment(BezierEvaluate,479,1)
      seg(159) shouldBe CubismMotionSegment(BezierEvaluate,482,1)
      seg(160) shouldBe CubismMotionSegment(BezierEvaluate,485,1)
      seg(161) shouldBe CubismMotionSegment(BezierEvaluate,488,1)
      seg(162) shouldBe CubismMotionSegment(BezierEvaluate,491,1)
      seg(163) shouldBe CubismMotionSegment(BezierEvaluate,494,1)
      seg(164) shouldBe CubismMotionSegment(BezierEvaluate,497,1)
      seg(165) shouldBe CubismMotionSegment(BezierEvaluate,501,1)
      seg(166) shouldBe CubismMotionSegment(BezierEvaluate,504,1)
      seg(167) shouldBe CubismMotionSegment(BezierEvaluate,507,1)
      seg(168) shouldBe CubismMotionSegment(BezierEvaluate,510,1)
      seg(169) shouldBe CubismMotionSegment(BezierEvaluate,513,1)
      seg(170) shouldBe CubismMotionSegment(BezierEvaluate,516,1)
      seg(171) shouldBe CubismMotionSegment(BezierEvaluate,519,1)
      seg(172) shouldBe CubismMotionSegment(BezierEvaluate,522,1)
      seg(173) shouldBe CubismMotionSegment(BezierEvaluate,525,1)
      seg(174) shouldBe CubismMotionSegment(BezierEvaluate,528,1)
      seg(175) shouldBe CubismMotionSegment(BezierEvaluate,531,1)
      seg(176) shouldBe CubismMotionSegment(BezierEvaluate,534,1)
      seg(177) shouldBe CubismMotionSegment(BezierEvaluate,537,1)
      seg(178) shouldBe CubismMotionSegment(BezierEvaluate,540,1)
      seg(179) shouldBe CubismMotionSegment(BezierEvaluate,543,1)
      seg(180) shouldBe CubismMotionSegment(BezierEvaluate,546,1)
      seg(181) shouldBe CubismMotionSegment(BezierEvaluate,549,1)
      seg(182) shouldBe CubismMotionSegment(BezierEvaluate,552,1)
      seg(183) shouldBe CubismMotionSegment(BezierEvaluate,555,1)
      seg(184) shouldBe CubismMotionSegment(BezierEvaluate,558,1)
      seg(185) shouldBe CubismMotionSegment(BezierEvaluate,561,1)
      seg(186) shouldBe CubismMotionSegment(BezierEvaluate,564,1)
      seg(187) shouldBe CubismMotionSegment(BezierEvaluate,567,1)
      seg(188) shouldBe CubismMotionSegment(BezierEvaluate,570,1)
      seg(189) shouldBe CubismMotionSegment(BezierEvaluate,573,1)
      seg(190) shouldBe CubismMotionSegment(BezierEvaluate,576,1)
      seg(191) shouldBe CubismMotionSegment(BezierEvaluate,579,1)
      seg(192) shouldBe CubismMotionSegment(BezierEvaluate,582,1)
      seg(193) shouldBe CubismMotionSegment(BezierEvaluate,585,1)
      seg(194) shouldBe CubismMotionSegment(BezierEvaluate,588,1)
      seg(195) shouldBe CubismMotionSegment(BezierEvaluate,591,1)
      seg(196) shouldBe CubismMotionSegment(BezierEvaluate,594,1)
      seg(197) shouldBe CubismMotionSegment(BezierEvaluate,598,1)
      seg(198) shouldBe CubismMotionSegment(BezierEvaluate,601,1)
      seg(199) shouldBe CubismMotionSegment(BezierEvaluate,604,1)
      seg(200) shouldBe CubismMotionSegment(BezierEvaluate,607,1)
      seg(201) shouldBe CubismMotionSegment(BezierEvaluate,610,1)
      seg(202) shouldBe CubismMotionSegment(BezierEvaluate,613,1)
      seg(203) shouldBe CubismMotionSegment(BezierEvaluate,616,1)
      seg(204) shouldBe CubismMotionSegment(BezierEvaluate,619,1)
      seg(205) shouldBe CubismMotionSegment(BezierEvaluate,622,1)
      seg(206) shouldBe CubismMotionSegment(BezierEvaluate,625,1)
      seg(207) shouldBe CubismMotionSegment(BezierEvaluate,628,1)
      seg(208) shouldBe CubismMotionSegment(BezierEvaluate,631,1)
      seg(209) shouldBe CubismMotionSegment(BezierEvaluate,634,1)
      seg(210) shouldBe CubismMotionSegment(BezierEvaluate,637,1)
      seg(211) shouldBe CubismMotionSegment(BezierEvaluate,640,1)
      seg(212) shouldBe CubismMotionSegment(BezierEvaluate,643,1)
      seg(213) shouldBe CubismMotionSegment(BezierEvaluate,646,1)
      seg(214) shouldBe CubismMotionSegment(BezierEvaluate,649,1)
      seg(215) shouldBe CubismMotionSegment(BezierEvaluate,652,1)
      seg(216) shouldBe CubismMotionSegment(BezierEvaluate,655,1)
      seg(217) shouldBe CubismMotionSegment(BezierEvaluate,658,1)
      seg(218) shouldBe CubismMotionSegment(BezierEvaluate,661,1)
      seg(219) shouldBe CubismMotionSegment(BezierEvaluate,664,1)
      seg(220) shouldBe CubismMotionSegment(BezierEvaluate,667,1)
      seg(221) shouldBe CubismMotionSegment(BezierEvaluate,670,1)
      seg(222) shouldBe CubismMotionSegment(BezierEvaluate,673,1)
      seg(223) shouldBe CubismMotionSegment(BezierEvaluate,676,1)
      seg(224) shouldBe CubismMotionSegment(BezierEvaluate,679,1)
      seg(225) shouldBe CubismMotionSegment(BezierEvaluate,682,1)
      seg(226) shouldBe CubismMotionSegment(BezierEvaluate,685,1)
      seg(227) shouldBe CubismMotionSegment(BezierEvaluate,688,1)
      seg(228) shouldBe CubismMotionSegment(BezierEvaluate,691,1)
      seg(229) shouldBe CubismMotionSegment(BezierEvaluate,695,1)
      seg(230) shouldBe CubismMotionSegment(BezierEvaluate,698,1)
      seg(231) shouldBe CubismMotionSegment(BezierEvaluate,701,1)
      seg(232) shouldBe CubismMotionSegment(BezierEvaluate,704,1)
      seg(233) shouldBe CubismMotionSegment(BezierEvaluate,707,1)
      seg(234) shouldBe CubismMotionSegment(BezierEvaluate,710,1)
      seg(235) shouldBe CubismMotionSegment(BezierEvaluate,713,1)
      seg(236) shouldBe CubismMotionSegment(BezierEvaluate,716,1)
      seg(237) shouldBe CubismMotionSegment(BezierEvaluate,719,1)
      seg(238) shouldBe CubismMotionSegment(BezierEvaluate,722,1)
      seg(239) shouldBe CubismMotionSegment(BezierEvaluate,725,1)
      seg(240) shouldBe CubismMotionSegment(BezierEvaluate,728,1)
      seg(241) shouldBe CubismMotionSegment(BezierEvaluate,731,1)
      seg(242) shouldBe CubismMotionSegment(BezierEvaluate,734,1)
      seg(243) shouldBe CubismMotionSegment(BezierEvaluate,737,1)
      seg(244) shouldBe CubismMotionSegment(BezierEvaluate,740,1)
      seg(245) shouldBe CubismMotionSegment(BezierEvaluate,744,1)
      seg(246) shouldBe CubismMotionSegment(BezierEvaluate,747,1)
      seg(247) shouldBe CubismMotionSegment(BezierEvaluate,750,1)
      seg(248) shouldBe CubismMotionSegment(BezierEvaluate,753,1)
      seg(249) shouldBe CubismMotionSegment(BezierEvaluate,756,1)
      seg(250) shouldBe CubismMotionSegment(BezierEvaluate,759,1)
      seg(251) shouldBe CubismMotionSegment(BezierEvaluate,762,1)
      seg(252) shouldBe CubismMotionSegment(BezierEvaluate,765,1)
      seg(253) shouldBe CubismMotionSegment(BezierEvaluate,768,1)
      seg(254) shouldBe CubismMotionSegment(BezierEvaluate,771,1)
      seg(255) shouldBe CubismMotionSegment(BezierEvaluate,774,1)
      seg(256) shouldBe CubismMotionSegment(BezierEvaluate,777,1)
      seg(257) shouldBe CubismMotionSegment(BezierEvaluate,780,1)
      seg(258) shouldBe CubismMotionSegment(BezierEvaluate,783,1)
      seg(259) shouldBe CubismMotionSegment(BezierEvaluate,786,1)
      seg(260) shouldBe CubismMotionSegment(BezierEvaluate,789,1)
      seg(261) shouldBe CubismMotionSegment(BezierEvaluate,793,1)
      seg(262) shouldBe CubismMotionSegment(BezierEvaluate,796,1)
      seg(263) shouldBe CubismMotionSegment(BezierEvaluate,799,1)
      seg(264) shouldBe CubismMotionSegment(BezierEvaluate,802,1)
      seg(265) shouldBe CubismMotionSegment(BezierEvaluate,805,1)
      seg(266) shouldBe CubismMotionSegment(BezierEvaluate,808,1)
      seg(267) shouldBe CubismMotionSegment(BezierEvaluate,811,1)
      seg(268) shouldBe CubismMotionSegment(BezierEvaluate,814,1)
      seg(269) shouldBe CubismMotionSegment(BezierEvaluate,817,1)
      seg(270) shouldBe CubismMotionSegment(BezierEvaluate,820,1)
      seg(271) shouldBe CubismMotionSegment(BezierEvaluate,823,1)
      seg(272) shouldBe CubismMotionSegment(BezierEvaluate,826,1)
      seg(273) shouldBe CubismMotionSegment(BezierEvaluate,829,1)
      seg(274) shouldBe CubismMotionSegment(BezierEvaluate,832,1)
      seg(275) shouldBe CubismMotionSegment(BezierEvaluate,835,1)
      seg(276) shouldBe CubismMotionSegment(BezierEvaluate,838,1)
      seg(277) shouldBe CubismMotionSegment(BezierEvaluate,842,1)
      seg(278) shouldBe CubismMotionSegment(BezierEvaluate,845,1)
      seg(279) shouldBe CubismMotionSegment(BezierEvaluate,848,1)
      seg(280) shouldBe CubismMotionSegment(BezierEvaluate,851,1)
      seg(281) shouldBe CubismMotionSegment(BezierEvaluate,854,1)
      seg(282) shouldBe CubismMotionSegment(BezierEvaluate,857,1)
      seg(283) shouldBe CubismMotionSegment(BezierEvaluate,860,1)
      seg(284) shouldBe CubismMotionSegment(BezierEvaluate,863,1)
      seg(285) shouldBe CubismMotionSegment(BezierEvaluate,866,1)
      seg(286) shouldBe CubismMotionSegment(BezierEvaluate,869,1)
      seg(287) shouldBe CubismMotionSegment(BezierEvaluate,872,1)
      seg(288) shouldBe CubismMotionSegment(BezierEvaluate,875,1)
      seg(289) shouldBe CubismMotionSegment(BezierEvaluate,878,1)
      seg(290) shouldBe CubismMotionSegment(BezierEvaluate,881,1)
      seg(291) shouldBe CubismMotionSegment(BezierEvaluate,884,1)
      seg(292) shouldBe CubismMotionSegment(BezierEvaluate,887,1)
      seg(293) shouldBe CubismMotionSegment(BezierEvaluate,890,1)
      seg(294) shouldBe CubismMotionSegment(BezierEvaluate,893,1)
      seg(295) shouldBe CubismMotionSegment(BezierEvaluate,896,1)
      seg(296) shouldBe CubismMotionSegment(BezierEvaluate,899,1)
      seg(297) shouldBe CubismMotionSegment(BezierEvaluate,902,1)
      seg(298) shouldBe CubismMotionSegment(BezierEvaluate,905,1)
      seg(299) shouldBe CubismMotionSegment(BezierEvaluate,908,1)
      seg(300) shouldBe CubismMotionSegment(BezierEvaluate,911,1)
      seg(301) shouldBe CubismMotionSegment(BezierEvaluate,914,1)
      seg(302) shouldBe CubismMotionSegment(BezierEvaluate,917,1)
      seg(303) shouldBe CubismMotionSegment(BezierEvaluate,920,1)
      seg(304) shouldBe CubismMotionSegment(BezierEvaluate,923,1)
      seg(305) shouldBe CubismMotionSegment(BezierEvaluate,926,1)
      seg(306) shouldBe CubismMotionSegment(BezierEvaluate,929,1)
      seg(307) shouldBe CubismMotionSegment(BezierEvaluate,932,1)
      seg(308) shouldBe CubismMotionSegment(BezierEvaluate,935,1)
      seg(309) shouldBe CubismMotionSegment(BezierEvaluate,939,1)
      seg(310) shouldBe CubismMotionSegment(BezierEvaluate,942,1)
      seg(311) shouldBe CubismMotionSegment(BezierEvaluate,945,1)
      seg(312) shouldBe CubismMotionSegment(BezierEvaluate,948,1)
      seg(313) shouldBe CubismMotionSegment(BezierEvaluate,951,1)
      seg(314) shouldBe CubismMotionSegment(BezierEvaluate,954,1)
      seg(315) shouldBe CubismMotionSegment(BezierEvaluate,957,1)
      seg(316) shouldBe CubismMotionSegment(BezierEvaluate,960,1)
      seg(317) shouldBe CubismMotionSegment(BezierEvaluate,963,1)
      seg(318) shouldBe CubismMotionSegment(BezierEvaluate,966,1)
      seg(319) shouldBe CubismMotionSegment(BezierEvaluate,969,1)
      seg(320) shouldBe CubismMotionSegment(BezierEvaluate,972,1)
      seg(321) shouldBe CubismMotionSegment(BezierEvaluate,975,1)
      seg(322) shouldBe CubismMotionSegment(BezierEvaluate,978,1)
      seg(323) shouldBe CubismMotionSegment(BezierEvaluate,981,1)
      seg(324) shouldBe CubismMotionSegment(BezierEvaluate,984,1)
      seg(325) shouldBe CubismMotionSegment(BezierEvaluate,988,1)
      seg(326) shouldBe CubismMotionSegment(BezierEvaluate,991,1)
      seg(327) shouldBe CubismMotionSegment(BezierEvaluate,994,1)
      seg(328) shouldBe CubismMotionSegment(BezierEvaluate,997,1)
      seg(329) shouldBe CubismMotionSegment(BezierEvaluate,1000,1)
      seg(330) shouldBe CubismMotionSegment(BezierEvaluate,1003,1)
      seg(331) shouldBe CubismMotionSegment(BezierEvaluate,1006,1)
      seg(332) shouldBe CubismMotionSegment(BezierEvaluate,1009,1)
      seg(333) shouldBe CubismMotionSegment(BezierEvaluate,1012,1)
      seg(334) shouldBe CubismMotionSegment(BezierEvaluate,1015,1)
      seg(335) shouldBe CubismMotionSegment(BezierEvaluate,1018,1)
      seg(336) shouldBe CubismMotionSegment(BezierEvaluate,1021,1)
      seg(337) shouldBe CubismMotionSegment(BezierEvaluate,1024,1)
      seg(338) shouldBe CubismMotionSegment(BezierEvaluate,1027,1)
      seg(339) shouldBe CubismMotionSegment(BezierEvaluate,1030,1)
      seg(340) shouldBe CubismMotionSegment(BezierEvaluate,1033,1)
      seg(341) shouldBe CubismMotionSegment(BezierEvaluate,1037,1)
      seg(342) shouldBe CubismMotionSegment(BezierEvaluate,1040,1)
      seg(343) shouldBe CubismMotionSegment(BezierEvaluate,1043,1)
      seg(344) shouldBe CubismMotionSegment(BezierEvaluate,1046,1)
      seg(345) shouldBe CubismMotionSegment(BezierEvaluate,1049,1)
      seg(346) shouldBe CubismMotionSegment(BezierEvaluate,1052,1)
      seg(347) shouldBe CubismMotionSegment(BezierEvaluate,1055,1)
      seg(348) shouldBe CubismMotionSegment(BezierEvaluate,1058,1)
      seg(349) shouldBe CubismMotionSegment(BezierEvaluate,1061,1)
      seg(350) shouldBe CubismMotionSegment(BezierEvaluate,1064,1)
      seg(351) shouldBe CubismMotionSegment(BezierEvaluate,1067,1)
      seg(352) shouldBe CubismMotionSegment(BezierEvaluate,1070,1)
      seg(353) shouldBe CubismMotionSegment(BezierEvaluate,1073,1)
      seg(354) shouldBe CubismMotionSegment(BezierEvaluate,1076,1)
      seg(355) shouldBe CubismMotionSegment(BezierEvaluate,1079,1)
      seg(356) shouldBe CubismMotionSegment(BezierEvaluate,1082,1)
      seg(357) shouldBe CubismMotionSegment(BezierEvaluate,1086,1)
      seg(358) shouldBe CubismMotionSegment(BezierEvaluate,1089,1)
      seg(359) shouldBe CubismMotionSegment(BezierEvaluate,1092,1)
      seg(360) shouldBe CubismMotionSegment(BezierEvaluate,1095,1)
      seg(361) shouldBe CubismMotionSegment(BezierEvaluate,1098,1)
      seg(362) shouldBe CubismMotionSegment(BezierEvaluate,1101,1)
      seg(363) shouldBe CubismMotionSegment(BezierEvaluate,1104,1)
      seg(364) shouldBe CubismMotionSegment(BezierEvaluate,1107,1)
      seg(365) shouldBe CubismMotionSegment(BezierEvaluate,1110,1)
      seg(366) shouldBe CubismMotionSegment(BezierEvaluate,1113,1)
      seg(367) shouldBe CubismMotionSegment(BezierEvaluate,1116,1)
      seg(368) shouldBe CubismMotionSegment(BezierEvaluate,1119,1)
      seg(369) shouldBe CubismMotionSegment(BezierEvaluate,1122,1)
      seg(370) shouldBe CubismMotionSegment(BezierEvaluate,1125,1)
      seg(371) shouldBe CubismMotionSegment(BezierEvaluate,1128,1)
      seg(372) shouldBe CubismMotionSegment(BezierEvaluate,1131,1)
      seg(373) shouldBe CubismMotionSegment(BezierEvaluate,1135,1)
      seg(374) shouldBe CubismMotionSegment(BezierEvaluate,1138,1)
      seg(375) shouldBe CubismMotionSegment(BezierEvaluate,1141,1)
      seg(376) shouldBe CubismMotionSegment(BezierEvaluate,1144,1)
      seg(377) shouldBe CubismMotionSegment(BezierEvaluate,1147,1)
      seg(378) shouldBe CubismMotionSegment(BezierEvaluate,1150,1)
      seg(379) shouldBe CubismMotionSegment(BezierEvaluate,1153,1)
      seg(380) shouldBe CubismMotionSegment(BezierEvaluate,1156,1)
      seg(381) shouldBe CubismMotionSegment(BezierEvaluate,1159,1)
      seg(382) shouldBe CubismMotionSegment(BezierEvaluate,1162,1)
      seg(383) shouldBe CubismMotionSegment(BezierEvaluate,1165,1)
      seg(384) shouldBe CubismMotionSegment(BezierEvaluate,1168,1)
      seg(385) shouldBe CubismMotionSegment(BezierEvaluate,1171,1)
      seg(386) shouldBe CubismMotionSegment(BezierEvaluate,1174,1)
      seg(387) shouldBe CubismMotionSegment(BezierEvaluate,1177,1)
      seg(388) shouldBe CubismMotionSegment(BezierEvaluate,1180,1)
      seg(389) shouldBe CubismMotionSegment(LinearEvaluate,1184,0)
      seg(390) shouldBe CubismMotionSegment(LinearEvaluate,1186,0)
      seg(391) shouldBe CubismMotionSegment(LinearEvaluate,1188,0)
      seg(392) shouldBe CubismMotionSegment(LinearEvaluate,1190,0)
      seg(393) shouldBe CubismMotionSegment(LinearEvaluate,1192,0)
      seg(394) shouldBe CubismMotionSegment(LinearEvaluate,1194,0)
      seg(395) shouldBe CubismMotionSegment(LinearEvaluate,1196,0)
      seg(396) shouldBe CubismMotionSegment(LinearEvaluate,1198,0)
      seg(397) shouldBe CubismMotionSegment(LinearEvaluate,1200,0)
      seg(398) shouldBe CubismMotionSegment(LinearEvaluate,1202,0)
      seg(399) shouldBe CubismMotionSegment(LinearEvaluate,1204,0)
      seg(400) shouldBe CubismMotionSegment(LinearEvaluate,1206,0)
      seg(401) shouldBe CubismMotionSegment(LinearEvaluate,1208,0)
      seg(402) shouldBe CubismMotionSegment(LinearEvaluate,1210,0)
      seg(403) shouldBe CubismMotionSegment(LinearEvaluate,1212,0)
      seg(404) shouldBe CubismMotionSegment(LinearEvaluate,1214,0)

      CubismMotionData.apply(settings.motionGroups("idle")(3))
    }

    Scenario("Load motion idle[1] from avatar Mark") {
      Given("A folder path contains json files for a Live2D avatar model")
      val folderPath = "src/test/resources/models/Mark"

      When("Create a MotionData from this Live2D avatar settings")
      val jsonSettingsReader = new JsonSettingsReader(folderPath)
      val settings: Settings = jsonSettingsReader.loadSettings().success.value
      val motionData = CubismMotionData.apply(settings.motionGroups("idle")(1))

      motionData.fps shouldBe 30.0
      motionData.isLoop shouldBe true
      motionData.curveCount shouldBe 37
      motionData.duration shouldBe 4.8f

      val curves = motionData.curvesList
      curves(0) shouldBe CubismMotionCurve("Opacity", Model, 1, 0, -1.0f, -1.0f)
      curves(1) shouldBe CubismMotionCurve("EyeBlink", Model, 1, 1, -1.0f, -1.0f)
      curves(2) shouldBe CubismMotionCurve("ParamAngleX", Parameter, 16, 2, -1.0f, -1.0f)
      curves(3) shouldBe CubismMotionCurve("ParamAngleY", Parameter, 17, 18, -1.0f, -1.0f)
      curves(4) shouldBe CubismMotionCurve("ParamAngleZ", Parameter, 9, 35, -1.0f, -1.0f)
      curves(5) shouldBe CubismMotionCurve("ParamEyeBallX", Parameter, 8, 44, -1.0f, -1.0f)
      curves(6) shouldBe CubismMotionCurve("ParamEyeBallY", Parameter, 8, 52, -1.0f, -1.0f)
      curves(7) shouldBe CubismMotionCurve("ParamBrowLY", Parameter, 8, 60, -1.0f, -1.0f)
      curves(8) shouldBe CubismMotionCurve("ParamBrowRY", Parameter, 8, 68, -1.0f, -1.0f)
      curves(9) shouldBe CubismMotionCurve("ParamMouthOpenY", Parameter, 8, 76, -1.0f, -1.0f)
      curves(10) shouldBe CubismMotionCurve("ParamArmL", Parameter, 16, 84, -1.0f, -1.0f)
      curves(11) shouldBe CubismMotionCurve("ParamArmR", Parameter, 16, 100, -1.0f, -1.0f)
      curves(12) shouldBe CubismMotionCurve("ParamLeftLeg", Parameter, 16, 116, -1.0f, -1.0f)
      curves(13) shouldBe CubismMotionCurve("ParamRightLeg", Parameter, 16, 132, -1.0f, -1.0f)
      curves(14) shouldBe CubismMotionCurve("ParamBodyAngleX", Parameter, 16, 148, -1.0f, -1.0f)
      curves(15) shouldBe CubismMotionCurve("ParamBodyAngleY", Parameter, 32, 164, -1.0f, -1.0f)
      curves(16) shouldBe CubismMotionCurve("ParamBodyAngleZ", Parameter, 16, 196, -1.0f, -1.0f)
      curves(17) shouldBe CubismMotionCurve("ParamBreath", Parameter, 8, 212, -1.0f, -1.0f)
      curves(18) shouldBe CubismMotionCurve("ParamHairFront", Parameter, 8, 220, -1.0f, -1.0f)
      curves(19) shouldBe CubismMotionCurve("ParamHairSide", Parameter, 8, 228, -1.0f, -1.0f)
      curves(20) shouldBe CubismMotionCurve("ParamHairBack", Parameter, 8, 236, -1.0f, -1.0f)
      curves(21) shouldBe CubismMotionCurve("PartHead", PartOpacity, 1, 244, -1.0f, -1.0f)
      curves(22) shouldBe CubismMotionCurve("PartHairFront", PartOpacity, 1, 245, -1.0f, -1.0f)
      curves(23) shouldBe CubismMotionCurve("PartEyeL", PartOpacity, 1, 246, -1.0f, -1.0f)
      curves(24) shouldBe CubismMotionCurve("PartEyeBallL", PartOpacity, 1, 247, -1.0f, -1.0f)
      curves(25) shouldBe CubismMotionCurve("PartEyeWhiteL", PartOpacity, 1, 248, -1.0f, -1.0f)
      curves(26) shouldBe CubismMotionCurve("PartEyeR", PartOpacity, 1, 249, -1.0f, -1.0f)
      curves(27) shouldBe CubismMotionCurve("PartEyeBallR", PartOpacity, 1, 250, -1.0f, -1.0f)
      curves(28) shouldBe CubismMotionCurve("PartEyeWhiteR", PartOpacity, 1, 251, -1.0f, -1.0f)
      curves(29) shouldBe CubismMotionCurve("PartHairSide", PartOpacity, 1, 252, -1.0f, -1.0f)
      curves(30) shouldBe CubismMotionCurve("PartMouth", PartOpacity, 1, 253, -1.0f, -1.0f)
      curves(31) shouldBe CubismMotionCurve("PartOral", PartOpacity, 1, 254, -1.0f, -1.0f)
      curves(32) shouldBe CubismMotionCurve("PartFace", PartOpacity, 1, 255, -1.0f, -1.0f)
      curves(33) shouldBe CubismMotionCurve("PartBody", PartOpacity, 1, 256, -1.0f, -1.0f)
      curves(34) shouldBe CubismMotionCurve("PartArmL", PartOpacity, 1, 257, -1.0f, -1.0f)
      curves(35) shouldBe CubismMotionCurve("PartArmR", PartOpacity, 1, 258, -1.0f, -1.0f)
      curves(36) shouldBe CubismMotionCurve("PartHairBack", PartOpacity, 1, 259, -1.0f, -1.0f)

      val segments = motionData.segmentsList
      segments(0) shouldBe CubismMotionSegment(LinearEvaluate, 0, 0)
      segments(1) shouldBe CubismMotionSegment(LinearEvaluate, 2, 0)
      segments(2) shouldBe CubismMotionSegment(BezierEvaluate, 4, 1)
      segments(3) shouldBe CubismMotionSegment(BezierEvaluate, 7, 1)
      segments(4) shouldBe CubismMotionSegment(BezierEvaluate, 10, 1)
      segments(5) shouldBe CubismMotionSegment(BezierEvaluate, 13, 1)
      segments(6) shouldBe CubismMotionSegment(BezierEvaluate, 16, 1)
      segments(7) shouldBe CubismMotionSegment(BezierEvaluate, 19, 1)
      segments(8) shouldBe CubismMotionSegment(BezierEvaluate, 22, 1)
      segments(9) shouldBe CubismMotionSegment(BezierEvaluate, 25, 1)
      segments(10) shouldBe CubismMotionSegment(BezierEvaluate, 28, 1)
      segments(11) shouldBe CubismMotionSegment(BezierEvaluate, 31, 1)
      segments(12) shouldBe CubismMotionSegment(BezierEvaluate, 34, 1)
      segments(13) shouldBe CubismMotionSegment(BezierEvaluate, 37, 1)
      segments(14) shouldBe CubismMotionSegment(BezierEvaluate, 40, 1)
      segments(15) shouldBe CubismMotionSegment(BezierEvaluate, 43, 1)
      segments(16) shouldBe CubismMotionSegment(BezierEvaluate, 46, 1)
      segments(17) shouldBe CubismMotionSegment(BezierEvaluate, 49, 1)
      segments(18) shouldBe CubismMotionSegment(BezierEvaluate, 53, 1)
      segments(19) shouldBe CubismMotionSegment(BezierEvaluate, 56, 1)
      segments(20) shouldBe CubismMotionSegment(BezierEvaluate, 59, 1)
      segments(21) shouldBe CubismMotionSegment(BezierEvaluate, 62, 1)
      segments(22) shouldBe CubismMotionSegment(BezierEvaluate, 65, 1)
      segments(23) shouldBe CubismMotionSegment(BezierEvaluate, 68, 1)
      segments(24) shouldBe CubismMotionSegment(BezierEvaluate, 71, 1)
      segments(25) shouldBe CubismMotionSegment(BezierEvaluate, 74, 1)
      segments(26) shouldBe CubismMotionSegment(BezierEvaluate, 77, 1)
      segments(27) shouldBe CubismMotionSegment(BezierEvaluate, 80, 1)
      segments(28) shouldBe CubismMotionSegment(BezierEvaluate, 83, 1)
      segments(29) shouldBe CubismMotionSegment(BezierEvaluate, 86, 1)
      segments(30) shouldBe CubismMotionSegment(BezierEvaluate, 89, 1)
      segments(31) shouldBe CubismMotionSegment(BezierEvaluate, 92, 1)
      segments(32) shouldBe CubismMotionSegment(BezierEvaluate, 95, 1)
      segments(33) shouldBe CubismMotionSegment(BezierEvaluate, 98, 1)
      segments(34) shouldBe CubismMotionSegment(BezierEvaluate, 101, 1)
      segments(35) shouldBe CubismMotionSegment(BezierEvaluate, 105, 1)
      segments(36) shouldBe CubismMotionSegment(BezierEvaluate, 108, 1)
      segments(37) shouldBe CubismMotionSegment(BezierEvaluate, 111, 1)
      segments(38) shouldBe CubismMotionSegment(BezierEvaluate, 114, 1)
      segments(39) shouldBe CubismMotionSegment(BezierEvaluate, 117, 1)
      segments(40) shouldBe CubismMotionSegment(BezierEvaluate, 120, 1)
      segments(41) shouldBe CubismMotionSegment(BezierEvaluate, 123, 1)
      segments(42) shouldBe CubismMotionSegment(BezierEvaluate, 126, 1)
      segments(43) shouldBe CubismMotionSegment(BezierEvaluate, 129, 1)
      segments(44) shouldBe CubismMotionSegment(BezierEvaluate, 133, 1)
      segments(45) shouldBe CubismMotionSegment(BezierEvaluate, 136, 1)
      segments(46) shouldBe CubismMotionSegment(BezierEvaluate, 139, 1)
      segments(47) shouldBe CubismMotionSegment(BezierEvaluate, 142, 1)
      segments(48) shouldBe CubismMotionSegment(BezierEvaluate, 145, 1)
      segments(49) shouldBe CubismMotionSegment(BezierEvaluate, 148, 1)
      segments(50) shouldBe CubismMotionSegment(BezierEvaluate, 151, 1)
      segments(51) shouldBe CubismMotionSegment(BezierEvaluate, 154, 1)
      segments(52) shouldBe CubismMotionSegment(BezierEvaluate, 158, 1)
      segments(53) shouldBe CubismMotionSegment(BezierEvaluate, 161, 1)
      segments(54) shouldBe CubismMotionSegment(BezierEvaluate, 164, 1)
      segments(55) shouldBe CubismMotionSegment(BezierEvaluate, 167, 1)
      segments(56) shouldBe CubismMotionSegment(BezierEvaluate, 170, 1)
      segments(57) shouldBe CubismMotionSegment(BezierEvaluate, 173, 1)
      segments(58) shouldBe CubismMotionSegment(BezierEvaluate, 176, 1)
      segments(59) shouldBe CubismMotionSegment(BezierEvaluate, 179, 1)
      segments(60) shouldBe CubismMotionSegment(BezierEvaluate, 183, 1)
      segments(61) shouldBe CubismMotionSegment(BezierEvaluate, 186, 1)
      segments(62) shouldBe CubismMotionSegment(BezierEvaluate, 189, 1)
      segments(63) shouldBe CubismMotionSegment(BezierEvaluate, 192, 1)
      segments(64) shouldBe CubismMotionSegment(BezierEvaluate, 195, 1)
      segments(65) shouldBe CubismMotionSegment(BezierEvaluate, 198, 1)
      segments(66) shouldBe CubismMotionSegment(BezierEvaluate, 201, 1)
      segments(67) shouldBe CubismMotionSegment(BezierEvaluate, 204, 1)
      segments(68) shouldBe CubismMotionSegment(BezierEvaluate, 208, 1)
      segments(69) shouldBe CubismMotionSegment(BezierEvaluate, 211, 1)
      segments(70) shouldBe CubismMotionSegment(BezierEvaluate, 214, 1)
      segments(71) shouldBe CubismMotionSegment(BezierEvaluate, 217, 1)
      segments(72) shouldBe CubismMotionSegment(BezierEvaluate, 220, 1)
      segments(73) shouldBe CubismMotionSegment(BezierEvaluate, 223, 1)
      segments(74) shouldBe CubismMotionSegment(BezierEvaluate, 226, 1)
      segments(75) shouldBe CubismMotionSegment(BezierEvaluate, 229, 1)
      segments(76) shouldBe CubismMotionSegment(BezierEvaluate, 233, 1)
      segments(77) shouldBe CubismMotionSegment(BezierEvaluate, 236, 1)
      segments(78) shouldBe CubismMotionSegment(BezierEvaluate, 239, 1)
      segments(79) shouldBe CubismMotionSegment(BezierEvaluate, 242, 1)
      segments(80) shouldBe CubismMotionSegment(BezierEvaluate, 245, 1)
      segments(81) shouldBe CubismMotionSegment(BezierEvaluate, 248, 1)
      segments(82) shouldBe CubismMotionSegment(BezierEvaluate, 251, 1)
      segments(83) shouldBe CubismMotionSegment(BezierEvaluate, 254, 1)
      segments(84) shouldBe CubismMotionSegment(BezierEvaluate, 258, 1)
      segments(85) shouldBe CubismMotionSegment(BezierEvaluate, 261, 1)
      segments(86) shouldBe CubismMotionSegment(BezierEvaluate, 264, 1)
      segments(87) shouldBe CubismMotionSegment(BezierEvaluate, 267, 1)
      segments(88) shouldBe CubismMotionSegment(BezierEvaluate, 270, 1)
      segments(89) shouldBe CubismMotionSegment(BezierEvaluate, 273, 1)
      segments(90) shouldBe CubismMotionSegment(BezierEvaluate, 276, 1)
      segments(91) shouldBe CubismMotionSegment(BezierEvaluate, 279, 1)
      segments(92) shouldBe CubismMotionSegment(BezierEvaluate, 282, 1)
      segments(93) shouldBe CubismMotionSegment(BezierEvaluate, 285, 1)
      segments(94) shouldBe CubismMotionSegment(BezierEvaluate, 288, 1)
      segments(95) shouldBe CubismMotionSegment(BezierEvaluate, 291, 1)
      segments(96) shouldBe CubismMotionSegment(BezierEvaluate, 294, 1)
      segments(97) shouldBe CubismMotionSegment(BezierEvaluate, 297, 1)
      segments(98) shouldBe CubismMotionSegment(BezierEvaluate, 300, 1)
      segments(99) shouldBe CubismMotionSegment(BezierEvaluate, 303, 1)
      segments(100) shouldBe CubismMotionSegment(BezierEvaluate, 307, 1)
      segments(101) shouldBe CubismMotionSegment(BezierEvaluate, 310, 1)
      segments(102) shouldBe CubismMotionSegment(BezierEvaluate, 313, 1)
      segments(103) shouldBe CubismMotionSegment(BezierEvaluate, 316, 1)
      segments(104) shouldBe CubismMotionSegment(BezierEvaluate, 319, 1)
      segments(105) shouldBe CubismMotionSegment(BezierEvaluate, 322, 1)
      segments(106) shouldBe CubismMotionSegment(BezierEvaluate, 325, 1)
      segments(107) shouldBe CubismMotionSegment(BezierEvaluate, 328, 1)
      segments(108) shouldBe CubismMotionSegment(BezierEvaluate, 331, 1)
      segments(109) shouldBe CubismMotionSegment(BezierEvaluate, 334, 1)
      segments(110) shouldBe CubismMotionSegment(BezierEvaluate, 337, 1)
      segments(111) shouldBe CubismMotionSegment(BezierEvaluate, 340, 1)
      segments(112) shouldBe CubismMotionSegment(BezierEvaluate, 343, 1)
      segments(113) shouldBe CubismMotionSegment(BezierEvaluate, 346, 1)
      segments(114) shouldBe CubismMotionSegment(BezierEvaluate, 349, 1)
      segments(115) shouldBe CubismMotionSegment(BezierEvaluate, 352, 1)
      segments(116) shouldBe CubismMotionSegment(BezierEvaluate, 356, 1)
      segments(117) shouldBe CubismMotionSegment(BezierEvaluate, 359, 1)
      segments(118) shouldBe CubismMotionSegment(BezierEvaluate, 362, 1)
      segments(119) shouldBe CubismMotionSegment(BezierEvaluate, 365, 1)
      segments(120) shouldBe CubismMotionSegment(BezierEvaluate, 368, 1)
      segments(121) shouldBe CubismMotionSegment(BezierEvaluate, 371, 1)
      segments(122) shouldBe CubismMotionSegment(BezierEvaluate, 374, 1)
      segments(123) shouldBe CubismMotionSegment(BezierEvaluate, 377, 1)
      segments(124) shouldBe CubismMotionSegment(BezierEvaluate, 380, 1)
      segments(125) shouldBe CubismMotionSegment(BezierEvaluate, 383, 1)
      segments(126) shouldBe CubismMotionSegment(BezierEvaluate, 386, 1)
      segments(127) shouldBe CubismMotionSegment(BezierEvaluate, 389, 1)
      segments(128) shouldBe CubismMotionSegment(BezierEvaluate, 392, 1)
      segments(129) shouldBe CubismMotionSegment(BezierEvaluate, 395, 1)
      segments(130) shouldBe CubismMotionSegment(BezierEvaluate, 398, 1)
      segments(131) shouldBe CubismMotionSegment(BezierEvaluate, 401, 1)
      segments(132) shouldBe CubismMotionSegment(BezierEvaluate, 405, 1)
      segments(133) shouldBe CubismMotionSegment(BezierEvaluate, 408, 1)
      segments(134) shouldBe CubismMotionSegment(BezierEvaluate, 411, 1)
      segments(135) shouldBe CubismMotionSegment(BezierEvaluate, 414, 1)
      segments(136) shouldBe CubismMotionSegment(BezierEvaluate, 417, 1)
      segments(137) shouldBe CubismMotionSegment(BezierEvaluate, 420, 1)
      segments(138) shouldBe CubismMotionSegment(BezierEvaluate, 423, 1)
      segments(139) shouldBe CubismMotionSegment(BezierEvaluate, 426, 1)
      segments(140) shouldBe CubismMotionSegment(BezierEvaluate, 429, 1)
      segments(141) shouldBe CubismMotionSegment(BezierEvaluate, 432, 1)
      segments(142) shouldBe CubismMotionSegment(BezierEvaluate, 435, 1)
      segments(143) shouldBe CubismMotionSegment(BezierEvaluate, 438, 1)
      segments(144) shouldBe CubismMotionSegment(BezierEvaluate, 441, 1)
      segments(145) shouldBe CubismMotionSegment(BezierEvaluate, 444, 1)
      segments(146) shouldBe CubismMotionSegment(BezierEvaluate, 447, 1)
      segments(147) shouldBe CubismMotionSegment(BezierEvaluate, 450, 1)
      segments(148) shouldBe CubismMotionSegment(BezierEvaluate, 454, 1)
      segments(149) shouldBe CubismMotionSegment(BezierEvaluate, 457, 1)
      segments(150) shouldBe CubismMotionSegment(BezierEvaluate, 460, 1)
      segments(151) shouldBe CubismMotionSegment(BezierEvaluate, 463, 1)
      segments(152) shouldBe CubismMotionSegment(BezierEvaluate, 466, 1)
      segments(153) shouldBe CubismMotionSegment(BezierEvaluate, 469, 1)
      segments(154) shouldBe CubismMotionSegment(BezierEvaluate, 472, 1)
      segments(155) shouldBe CubismMotionSegment(BezierEvaluate, 475, 1)
      segments(156) shouldBe CubismMotionSegment(BezierEvaluate, 478, 1)
      segments(157) shouldBe CubismMotionSegment(BezierEvaluate, 481, 1)
      segments(158) shouldBe CubismMotionSegment(BezierEvaluate, 484, 1)
      segments(159) shouldBe CubismMotionSegment(BezierEvaluate, 487, 1)
      segments(160) shouldBe CubismMotionSegment(BezierEvaluate, 490, 1)
      segments(161) shouldBe CubismMotionSegment(BezierEvaluate, 493, 1)
      segments(162) shouldBe CubismMotionSegment(BezierEvaluate, 496, 1)
      segments(163) shouldBe CubismMotionSegment(BezierEvaluate, 499, 1)
      segments(164) shouldBe CubismMotionSegment(BezierEvaluate, 503, 1)
      segments(165) shouldBe CubismMotionSegment(BezierEvaluate, 506, 1)
      segments(166) shouldBe CubismMotionSegment(BezierEvaluate, 509, 1)
      segments(167) shouldBe CubismMotionSegment(BezierEvaluate, 512, 1)
      segments(168) shouldBe CubismMotionSegment(BezierEvaluate, 515, 1)
      segments(169) shouldBe CubismMotionSegment(BezierEvaluate, 518, 1)
      segments(170) shouldBe CubismMotionSegment(BezierEvaluate, 521, 1)
      segments(171) shouldBe CubismMotionSegment(BezierEvaluate, 524, 1)
      segments(172) shouldBe CubismMotionSegment(BezierEvaluate, 527, 1)
      segments(173) shouldBe CubismMotionSegment(BezierEvaluate, 530, 1)
      segments(174) shouldBe CubismMotionSegment(BezierEvaluate, 533, 1)
      segments(175) shouldBe CubismMotionSegment(BezierEvaluate, 536, 1)
      segments(176) shouldBe CubismMotionSegment(BezierEvaluate, 539, 1)
      segments(177) shouldBe CubismMotionSegment(BezierEvaluate, 542, 1)
      segments(178) shouldBe CubismMotionSegment(BezierEvaluate, 545, 1)
      segments(179) shouldBe CubismMotionSegment(BezierEvaluate, 548, 1)
      segments(180) shouldBe CubismMotionSegment(BezierEvaluate, 551, 1)
      segments(181) shouldBe CubismMotionSegment(BezierEvaluate, 554, 1)
      segments(182) shouldBe CubismMotionSegment(BezierEvaluate, 557, 1)
      segments(183) shouldBe CubismMotionSegment(BezierEvaluate, 560, 1)
      segments(184) shouldBe CubismMotionSegment(BezierEvaluate, 563, 1)
      segments(185) shouldBe CubismMotionSegment(BezierEvaluate, 566, 1)
      segments(186) shouldBe CubismMotionSegment(BezierEvaluate, 569, 1)
      segments(187) shouldBe CubismMotionSegment(BezierEvaluate, 572, 1)
      segments(188) shouldBe CubismMotionSegment(BezierEvaluate, 575, 1)
      segments(189) shouldBe CubismMotionSegment(BezierEvaluate, 578, 1)
      segments(190) shouldBe CubismMotionSegment(BezierEvaluate, 581, 1)
      segments(191) shouldBe CubismMotionSegment(BezierEvaluate, 584, 1)
      segments(192) shouldBe CubismMotionSegment(BezierEvaluate, 587, 1)
      segments(193) shouldBe CubismMotionSegment(BezierEvaluate, 590, 1)
      segments(194) shouldBe CubismMotionSegment(BezierEvaluate, 593, 1)
      segments(195) shouldBe CubismMotionSegment(BezierEvaluate, 596, 1)
      segments(196) shouldBe CubismMotionSegment(BezierEvaluate, 600, 1)
      segments(197) shouldBe CubismMotionSegment(BezierEvaluate, 603, 1)
      segments(198) shouldBe CubismMotionSegment(BezierEvaluate, 606, 1)
      segments(199) shouldBe CubismMotionSegment(BezierEvaluate, 609, 1)
      segments(200) shouldBe CubismMotionSegment(BezierEvaluate, 612, 1)
      segments(201) shouldBe CubismMotionSegment(BezierEvaluate, 615, 1)
      segments(202) shouldBe CubismMotionSegment(BezierEvaluate, 618, 1)
      segments(203) shouldBe CubismMotionSegment(BezierEvaluate, 621, 1)
      segments(204) shouldBe CubismMotionSegment(BezierEvaluate, 624, 1)
      segments(205) shouldBe CubismMotionSegment(BezierEvaluate, 627, 1)
      segments(206) shouldBe CubismMotionSegment(BezierEvaluate, 630, 1)
      segments(207) shouldBe CubismMotionSegment(BezierEvaluate, 633, 1)
      segments(208) shouldBe CubismMotionSegment(BezierEvaluate, 636, 1)
      segments(209) shouldBe CubismMotionSegment(BezierEvaluate, 639, 1)
      segments(210) shouldBe CubismMotionSegment(BezierEvaluate, 642, 1)
      segments(211) shouldBe CubismMotionSegment(BezierEvaluate, 645, 1)
      segments(212) shouldBe CubismMotionSegment(BezierEvaluate, 649, 1)
      segments(213) shouldBe CubismMotionSegment(BezierEvaluate, 652, 1)
      segments(214) shouldBe CubismMotionSegment(BezierEvaluate, 655, 1)
      segments(215) shouldBe CubismMotionSegment(BezierEvaluate, 658, 1)
      segments(216) shouldBe CubismMotionSegment(BezierEvaluate, 661, 1)
      segments(217) shouldBe CubismMotionSegment(BezierEvaluate, 664, 1)
      segments(218) shouldBe CubismMotionSegment(BezierEvaluate, 667, 1)
      segments(219) shouldBe CubismMotionSegment(BezierEvaluate, 670, 1)
      segments(220) shouldBe CubismMotionSegment(BezierEvaluate, 674, 1)
      segments(221) shouldBe CubismMotionSegment(BezierEvaluate, 677, 1)
      segments(222) shouldBe CubismMotionSegment(BezierEvaluate, 680, 1)
      segments(223) shouldBe CubismMotionSegment(BezierEvaluate, 683, 1)
      segments(224) shouldBe CubismMotionSegment(BezierEvaluate, 686, 1)
      segments(225) shouldBe CubismMotionSegment(BezierEvaluate, 689, 1)
      segments(226) shouldBe CubismMotionSegment(BezierEvaluate, 692, 1)
      segments(227) shouldBe CubismMotionSegment(BezierEvaluate, 695, 1)
      segments(228) shouldBe CubismMotionSegment(BezierEvaluate, 699, 1)
      segments(229) shouldBe CubismMotionSegment(BezierEvaluate, 702, 1)
      segments(230) shouldBe CubismMotionSegment(BezierEvaluate, 705, 1)
      segments(231) shouldBe CubismMotionSegment(BezierEvaluate, 708, 1)
      segments(232) shouldBe CubismMotionSegment(BezierEvaluate, 711, 1)
      segments(233) shouldBe CubismMotionSegment(BezierEvaluate, 714, 1)
      segments(234) shouldBe CubismMotionSegment(BezierEvaluate, 717, 1)
      segments(235) shouldBe CubismMotionSegment(BezierEvaluate, 720, 1)
      segments(236) shouldBe CubismMotionSegment(BezierEvaluate, 724, 1)
      segments(237) shouldBe CubismMotionSegment(BezierEvaluate, 727, 1)
      segments(238) shouldBe CubismMotionSegment(BezierEvaluate, 730, 1)
      segments(239) shouldBe CubismMotionSegment(BezierEvaluate, 733, 1)
      segments(240) shouldBe CubismMotionSegment(BezierEvaluate, 736, 1)
      segments(241) shouldBe CubismMotionSegment(BezierEvaluate, 739, 1)
      segments(242) shouldBe CubismMotionSegment(BezierEvaluate, 742, 1)
      segments(243) shouldBe CubismMotionSegment(BezierEvaluate, 745, 1)
      segments(244) shouldBe CubismMotionSegment(LinearEvaluate, 749, 0)
      segments(245) shouldBe CubismMotionSegment(LinearEvaluate, 751, 0)
      segments(246) shouldBe CubismMotionSegment(LinearEvaluate, 753, 0)
      segments(247) shouldBe CubismMotionSegment(LinearEvaluate, 755, 0)
      segments(248) shouldBe CubismMotionSegment(LinearEvaluate, 757, 0)
      segments(249) shouldBe CubismMotionSegment(LinearEvaluate, 759, 0)
      segments(250) shouldBe CubismMotionSegment(LinearEvaluate, 761, 0)
      segments(251) shouldBe CubismMotionSegment(LinearEvaluate, 763, 0)
      segments(252) shouldBe CubismMotionSegment(LinearEvaluate, 765, 0)
      segments(253) shouldBe CubismMotionSegment(LinearEvaluate, 767, 0)
      segments(254) shouldBe CubismMotionSegment(LinearEvaluate, 769, 0)
      segments(255) shouldBe CubismMotionSegment(LinearEvaluate, 771, 0)
      segments(256) shouldBe CubismMotionSegment(LinearEvaluate, 773, 0)
      segments(257) shouldBe CubismMotionSegment(LinearEvaluate, 775, 0)
      segments(258) shouldBe CubismMotionSegment(LinearEvaluate, 777, 0)
      segments(259) shouldBe CubismMotionSegment(LinearEvaluate, 779, 0)

    }

    Scenario("Load motion from avatar Hiyori") {
      Given("A folder path contains json files for a Live2D avatar model")
      val folderPath = "src/test/resources/models/Hiyori"

      When("Create a MotionData from this Live2D avatar settings")
      val jsonSettingsReader = new JsonSettingsReader(folderPath)
      val settings: Settings = jsonSettingsReader.loadSettings().success.value
      val motionData = CubismMotionData.apply(settings.motionGroups("idle")(0))

      motionData.fps shouldBe 30.0
      motionData.isLoop shouldBe true
      motionData.curveCount shouldBe 31
      motionData.duration shouldBe 4.7f

      val curves = motionData.curvesList
      curves(0) shouldBe CubismMotionCurve("ParamAngleX", Parameter, 10, 0, 0.2f, -1.0f)
      curves(1) shouldBe CubismMotionCurve("ParamAngleY", Parameter, 12, 10, -1.0f, 0.3f)
      curves(2) shouldBe CubismMotionCurve("ParamAngleZ", Parameter, 9, 22, 0.4f, 0.5f)
      curves(3) shouldBe CubismMotionCurve("ParamCheek", Parameter, 1, 31, -1.0f, -1.0f)
      curves(4) shouldBe CubismMotionCurve("ParamEyeLOpen", Parameter, 9, 32, -1.0f, -1.0f)
      curves(5) shouldBe CubismMotionCurve("ParamEyeLSmile", Parameter, 1, 41, -1.0f, -1.0f)
      curves(6) shouldBe CubismMotionCurve("ParamEyeROpen", Parameter, 9, 42, -1.0f, -1.0f)
      curves(7) shouldBe CubismMotionCurve("ParamEyeRSmile", Parameter, 1, 51, -1.0f, -1.0f)
      curves(8) shouldBe CubismMotionCurve("ParamEyeBallX", Parameter, 7, 52, -1.0f, -1.0f)
      curves(9) shouldBe CubismMotionCurve("ParamEyeBallY", Parameter, 7, 59, -1.0f, -1.0f)
      curves(10) shouldBe CubismMotionCurve("ParamBrowLY", Parameter, 1, 66, -1.0f, -1.0f)
      curves(11) shouldBe CubismMotionCurve("ParamBrowRY", Parameter, 1, 67, -1.0f, -1.0f)
      curves(12) shouldBe CubismMotionCurve("ParamBrowLX", Parameter, 1, 68, -1.0f, -1.0f)
      curves(13) shouldBe CubismMotionCurve("ParamBrowRX", Parameter, 1, 69, -1.0f, -1.0f)
      curves(14) shouldBe CubismMotionCurve("ParamBrowLAngle", Parameter, 1, 70, -1.0f, -1.0f)
      curves(15) shouldBe CubismMotionCurve("ParamBrowRAngle", Parameter, 1, 71, -1.0f, -1.0f)
      curves(16) shouldBe CubismMotionCurve("ParamBrowLForm", Parameter, 1, 72, -1.0f, -1.0f)
      curves(17) shouldBe CubismMotionCurve("ParamBrowRForm", Parameter, 1, 73, -1.0f, -1.0f)
      curves(18) shouldBe CubismMotionCurve("ParamMouthForm", Parameter, 1, 74, -1.0f, -1.0f)
      curves(19) shouldBe CubismMotionCurve("ParamMouthOpenY", Parameter, 1, 75, -1.0f, -1.0f)
      curves(20) shouldBe CubismMotionCurve("ParamBodyAngleX", Parameter, 4, 76, -1.0f, -1.0f)
      curves(21) shouldBe CubismMotionCurve("ParamBodyAngleY", Parameter, 12, 80, -1.0f, -1.0f)
      curves(22) shouldBe CubismMotionCurve("ParamBodyAngleZ", Parameter, 5, 92, -1.0f, -1.0f)
      curves(23) shouldBe CubismMotionCurve("ParamBreath", Parameter, 1, 97, -1.0f, -1.0f)
      curves(24) shouldBe CubismMotionCurve("ParamShoulder", Parameter, 6, 98, -1.0f, -1.0f)
      curves(25) shouldBe CubismMotionCurve("ParamLeg", Parameter, 1, 104, -1.0f, -1.0f)
      curves(26) shouldBe CubismMotionCurve("ParamArmLA", Parameter, 8, 105, -1.0f, -1.0f)
      curves(27) shouldBe CubismMotionCurve("ParamArmRA", Parameter, 8, 113, -1.0f, -1.0f)
      curves(28) shouldBe CubismMotionCurve("ParamHairAhoge", Parameter, 12, 121, -1.0f, -1.0f)
      curves(29) shouldBe CubismMotionCurve("PartArmA", PartOpacity, 1, 133, -1.0f, -1.0f)
      curves(30) shouldBe CubismMotionCurve("PartArmB", PartOpacity, 1, 134, -1.0f, -1.0f)

      val segments = motionData.segmentsList
      segments(0) shouldBe CubismMotionSegment(BezierEvaluateCardanoInterpretation, 0, 1)
      segments(1) shouldBe CubismMotionSegment(BezierEvaluateCardanoInterpretation, 3, 1)
      segments(2) shouldBe CubismMotionSegment(BezierEvaluateCardanoInterpretation, 6, 1)
      segments(3) shouldBe CubismMotionSegment(BezierEvaluateCardanoInterpretation, 9, 1)
      segments(4) shouldBe CubismMotionSegment(BezierEvaluateCardanoInterpretation, 12, 1)
      segments(5) shouldBe CubismMotionSegment(BezierEvaluateCardanoInterpretation, 15, 1)
      segments(6) shouldBe CubismMotionSegment(BezierEvaluateCardanoInterpretation, 18, 1)
      segments(7) shouldBe CubismMotionSegment(BezierEvaluateCardanoInterpretation, 21, 1)
      segments(8) shouldBe CubismMotionSegment(BezierEvaluateCardanoInterpretation, 24, 1)
      segments(9) shouldBe CubismMotionSegment(LinearEvaluate, 27, 0)
      segments(10) shouldBe CubismMotionSegment(BezierEvaluateCardanoInterpretation, 29, 1)
      segments(11) shouldBe CubismMotionSegment(BezierEvaluateCardanoInterpretation, 32, 1)
      segments(12) shouldBe CubismMotionSegment(BezierEvaluateCardanoInterpretation, 35, 1)
      segments(13) shouldBe CubismMotionSegment(BezierEvaluateCardanoInterpretation, 38, 1)
      segments(14) shouldBe CubismMotionSegment(BezierEvaluateCardanoInterpretation, 41, 1)
      segments(15) shouldBe CubismMotionSegment(BezierEvaluateCardanoInterpretation, 44, 1)
      segments(16) shouldBe CubismMotionSegment(BezierEvaluateCardanoInterpretation, 47, 1)
      segments(17) shouldBe CubismMotionSegment(BezierEvaluateCardanoInterpretation, 50, 1)
      segments(18) shouldBe CubismMotionSegment(BezierEvaluateCardanoInterpretation, 53, 1)
      segments(19) shouldBe CubismMotionSegment(BezierEvaluateCardanoInterpretation, 56, 1)
      segments(20) shouldBe CubismMotionSegment(BezierEvaluateCardanoInterpretation, 59, 1)
      segments(21) shouldBe CubismMotionSegment(LinearEvaluate, 62, 0)
      segments(22) shouldBe CubismMotionSegment(BezierEvaluateCardanoInterpretation, 64, 1)
      segments(23) shouldBe CubismMotionSegment(BezierEvaluateCardanoInterpretation, 67, 1)
      segments(24) shouldBe CubismMotionSegment(BezierEvaluateCardanoInterpretation, 70, 1)
      segments(25) shouldBe CubismMotionSegment(BezierEvaluateCardanoInterpretation, 73, 1)
      segments(26) shouldBe CubismMotionSegment(BezierEvaluateCardanoInterpretation, 76, 1)
      segments(27) shouldBe CubismMotionSegment(BezierEvaluateCardanoInterpretation, 79, 1)
      segments(28) shouldBe CubismMotionSegment(BezierEvaluateCardanoInterpretation, 82, 1)
      segments(29) shouldBe CubismMotionSegment(BezierEvaluateCardanoInterpretation, 85, 1)
      segments(30) shouldBe CubismMotionSegment(LinearEvaluate, 88, 0)
      segments(31) shouldBe CubismMotionSegment(LinearEvaluate, 90, 0)
      segments(32) shouldBe CubismMotionSegment(BezierEvaluateCardanoInterpretation, 92, 1)
      segments(33) shouldBe CubismMotionSegment(BezierEvaluateCardanoInterpretation, 95, 1)
      segments(34) shouldBe CubismMotionSegment(BezierEvaluateCardanoInterpretation, 98, 1)
      segments(35) shouldBe CubismMotionSegment(BezierEvaluateCardanoInterpretation, 101, 1)
      segments(36) shouldBe CubismMotionSegment(BezierEvaluateCardanoInterpretation, 104, 1)
      segments(37) shouldBe CubismMotionSegment(BezierEvaluateCardanoInterpretation, 107, 1)
      segments(38) shouldBe CubismMotionSegment(BezierEvaluateCardanoInterpretation, 110, 1)
      segments(39) shouldBe CubismMotionSegment(BezierEvaluateCardanoInterpretation, 113, 1)
      segments(40) shouldBe CubismMotionSegment(LinearEvaluate, 116, 0)
      segments(41) shouldBe CubismMotionSegment(LinearEvaluate, 118, 0)
      segments(42) shouldBe CubismMotionSegment(BezierEvaluateCardanoInterpretation, 120, 1)
      segments(43) shouldBe CubismMotionSegment(BezierEvaluateCardanoInterpretation, 123, 1)
      segments(44) shouldBe CubismMotionSegment(BezierEvaluateCardanoInterpretation, 126, 1)
      segments(45) shouldBe CubismMotionSegment(BezierEvaluateCardanoInterpretation, 129, 1)
      segments(46) shouldBe CubismMotionSegment(BezierEvaluateCardanoInterpretation, 132, 1)
      segments(47) shouldBe CubismMotionSegment(BezierEvaluateCardanoInterpretation, 135, 1)
      segments(48) shouldBe CubismMotionSegment(BezierEvaluateCardanoInterpretation, 138, 1)
      segments(49) shouldBe CubismMotionSegment(BezierEvaluateCardanoInterpretation, 141, 1)
      segments(50) shouldBe CubismMotionSegment(LinearEvaluate, 144, 0)
      segments(51) shouldBe CubismMotionSegment(LinearEvaluate, 146, 0)
      segments(52) shouldBe CubismMotionSegment(BezierEvaluateCardanoInterpretation, 148, 1)
      segments(53) shouldBe CubismMotionSegment(BezierEvaluateCardanoInterpretation, 151, 1)
      segments(54) shouldBe CubismMotionSegment(BezierEvaluateCardanoInterpretation, 154, 1)
      segments(55) shouldBe CubismMotionSegment(BezierEvaluateCardanoInterpretation, 157, 1)
      segments(56) shouldBe CubismMotionSegment(BezierEvaluateCardanoInterpretation, 160, 1)
      segments(57) shouldBe CubismMotionSegment(BezierEvaluateCardanoInterpretation, 163, 1)
      segments(58) shouldBe CubismMotionSegment(LinearEvaluate, 166, 0)
      segments(59) shouldBe CubismMotionSegment(BezierEvaluateCardanoInterpretation, 168, 1)
      segments(60) shouldBe CubismMotionSegment(BezierEvaluateCardanoInterpretation, 171, 1)
      segments(61) shouldBe CubismMotionSegment(BezierEvaluateCardanoInterpretation, 174, 1)
      segments(62) shouldBe CubismMotionSegment(BezierEvaluateCardanoInterpretation, 177, 1)
      segments(63) shouldBe CubismMotionSegment(BezierEvaluateCardanoInterpretation, 180, 1)
      segments(64) shouldBe CubismMotionSegment(BezierEvaluateCardanoInterpretation, 183, 1)
      segments(65) shouldBe CubismMotionSegment(LinearEvaluate, 186, 0)
      segments(66) shouldBe CubismMotionSegment(LinearEvaluate, 188, 0)
      segments(67) shouldBe CubismMotionSegment(LinearEvaluate, 190, 0)
      segments(68) shouldBe CubismMotionSegment(LinearEvaluate, 192, 0)
      segments(69) shouldBe CubismMotionSegment(LinearEvaluate, 194, 0)
      segments(70) shouldBe CubismMotionSegment(LinearEvaluate, 196, 0)
      segments(71) shouldBe CubismMotionSegment(LinearEvaluate, 198, 0)
      segments(72) shouldBe CubismMotionSegment(LinearEvaluate, 200, 0)
      segments(73) shouldBe CubismMotionSegment(LinearEvaluate, 202, 0)
      segments(74) shouldBe CubismMotionSegment(LinearEvaluate, 204, 0)
      segments(75) shouldBe CubismMotionSegment(LinearEvaluate, 206, 0)
      segments(76) shouldBe CubismMotionSegment(BezierEvaluateCardanoInterpretation, 208, 1)
      segments(77) shouldBe CubismMotionSegment(BezierEvaluateCardanoInterpretation, 211, 1)
      segments(78) shouldBe CubismMotionSegment(BezierEvaluateCardanoInterpretation, 214, 1)
      segments(79) shouldBe CubismMotionSegment(LinearEvaluate, 217, 0)
      segments(80) shouldBe CubismMotionSegment(BezierEvaluateCardanoInterpretation, 219, 1)
      segments(81) shouldBe CubismMotionSegment(BezierEvaluateCardanoInterpretation, 222, 1)
      segments(82) shouldBe CubismMotionSegment(BezierEvaluateCardanoInterpretation, 225, 1)
      segments(83) shouldBe CubismMotionSegment(BezierEvaluateCardanoInterpretation, 228, 1)
      segments(84) shouldBe CubismMotionSegment(BezierEvaluateCardanoInterpretation, 231, 1)
      segments(85) shouldBe CubismMotionSegment(BezierEvaluateCardanoInterpretation, 234, 1)
      segments(86) shouldBe CubismMotionSegment(BezierEvaluateCardanoInterpretation, 237, 1)
      segments(87) shouldBe CubismMotionSegment(BezierEvaluateCardanoInterpretation, 240, 1)
      segments(88) shouldBe CubismMotionSegment(BezierEvaluateCardanoInterpretation, 243, 1)
      segments(89) shouldBe CubismMotionSegment(BezierEvaluateCardanoInterpretation, 246, 1)
      segments(90) shouldBe CubismMotionSegment(BezierEvaluateCardanoInterpretation, 249, 1)
      segments(91) shouldBe CubismMotionSegment(LinearEvaluate, 252, 0)
      segments(92) shouldBe CubismMotionSegment(BezierEvaluateCardanoInterpretation, 254, 1)
      segments(93) shouldBe CubismMotionSegment(BezierEvaluateCardanoInterpretation, 257, 1)
      segments(94) shouldBe CubismMotionSegment(BezierEvaluateCardanoInterpretation, 260, 1)
      segments(95) shouldBe CubismMotionSegment(BezierEvaluateCardanoInterpretation, 263, 1)
      segments(96) shouldBe CubismMotionSegment(LinearEvaluate, 266, 0)
      segments(97) shouldBe CubismMotionSegment(LinearEvaluate, 268, 0)
      segments(98) shouldBe CubismMotionSegment(BezierEvaluateCardanoInterpretation, 270, 1)
      segments(99) shouldBe CubismMotionSegment(BezierEvaluateCardanoInterpretation, 273, 1)
      segments(100) shouldBe CubismMotionSegment(BezierEvaluateCardanoInterpretation, 276, 1)
      segments(101) shouldBe CubismMotionSegment(BezierEvaluateCardanoInterpretation, 279, 1)
      segments(102) shouldBe CubismMotionSegment(BezierEvaluateCardanoInterpretation, 282, 1)
      segments(103) shouldBe CubismMotionSegment(LinearEvaluate, 285, 0)
      segments(104) shouldBe CubismMotionSegment(LinearEvaluate, 287, 0)
      segments(105) shouldBe CubismMotionSegment(BezierEvaluateCardanoInterpretation, 289, 1)
      segments(106) shouldBe CubismMotionSegment(BezierEvaluateCardanoInterpretation, 292, 1)
      segments(107) shouldBe CubismMotionSegment(BezierEvaluateCardanoInterpretation, 295, 1)
      segments(108) shouldBe CubismMotionSegment(BezierEvaluateCardanoInterpretation, 298, 1)
      segments(109) shouldBe CubismMotionSegment(BezierEvaluateCardanoInterpretation, 301, 1)
      segments(110) shouldBe CubismMotionSegment(BezierEvaluateCardanoInterpretation, 304, 1)
      segments(111) shouldBe CubismMotionSegment(BezierEvaluateCardanoInterpretation, 307, 1)
      segments(112) shouldBe CubismMotionSegment(LinearEvaluate, 310, 0)
      segments(113) shouldBe CubismMotionSegment(BezierEvaluateCardanoInterpretation, 312, 1)
      segments(114) shouldBe CubismMotionSegment(BezierEvaluateCardanoInterpretation, 315, 1)
      segments(115) shouldBe CubismMotionSegment(BezierEvaluateCardanoInterpretation, 318, 1)
      segments(116) shouldBe CubismMotionSegment(BezierEvaluateCardanoInterpretation, 321, 1)
      segments(117) shouldBe CubismMotionSegment(BezierEvaluateCardanoInterpretation, 324, 1)
      segments(118) shouldBe CubismMotionSegment(BezierEvaluateCardanoInterpretation, 327, 1)
      segments(119) shouldBe CubismMotionSegment(BezierEvaluateCardanoInterpretation, 330, 1)
      segments(120) shouldBe CubismMotionSegment(LinearEvaluate, 333, 0)
      segments(121) shouldBe CubismMotionSegment(BezierEvaluateCardanoInterpretation, 335, 1)
      segments(122) shouldBe CubismMotionSegment(BezierEvaluateCardanoInterpretation, 338, 1)
      segments(123) shouldBe CubismMotionSegment(BezierEvaluateCardanoInterpretation, 341, 1)
      segments(124) shouldBe CubismMotionSegment(BezierEvaluateCardanoInterpretation, 344, 1)
      segments(125) shouldBe CubismMotionSegment(BezierEvaluateCardanoInterpretation, 347, 1)
      segments(126) shouldBe CubismMotionSegment(BezierEvaluateCardanoInterpretation, 350, 1)
      segments(127) shouldBe CubismMotionSegment(BezierEvaluateCardanoInterpretation, 353, 1)
      segments(128) shouldBe CubismMotionSegment(BezierEvaluateCardanoInterpretation, 356, 1)
      segments(129) shouldBe CubismMotionSegment(BezierEvaluateCardanoInterpretation, 359, 1)
      segments(130) shouldBe CubismMotionSegment(BezierEvaluateCardanoInterpretation, 362, 1)
      segments(131) shouldBe CubismMotionSegment(BezierEvaluateCardanoInterpretation, 365, 1)
      segments(132) shouldBe CubismMotionSegment(LinearEvaluate, 368, 0)
      segments(133) shouldBe CubismMotionSegment(LinearEvaluate, 370, 0)
      segments(134) shouldBe CubismMotionSegment(LinearEvaluate, 372, 0)
    }
  }

}
