package moe.brianhsu.porting.live2d.temp

import moe.brianhsu.live2d.adapter.gateway.avatar.settings.json.JsonSettingsReader
import moe.brianhsu.live2d.enitiy.avatar.motion.data.SegmentType.{Bezier, BezierCardanoInterpretation, InverseStepped, Linear, Stepped}
import moe.brianhsu.live2d.enitiy.avatar.settings.Settings
import moe.brianhsu.porting.live2d.framework.CubismMotionCurveTarget.{Model, Parameter, PartOpacity}
import moe.brianhsu.porting.live2d.framework.{CubismMotionCurve, CubismMotionData, CubismMotionPoint, CubismMotionSegment}
import org.scalatest.featurespec.AnyFeatureSpec
import org.scalatest.matchers.should.Matchers
import org.scalatest.{GivenWhenThen, TryValues}

import scala.io.Source
import scala.util.Using

class MotionDataFeature extends AnyFeatureSpec with GivenWhenThen with Matchers with TryValues {
  Feature("Read pose parts data from Live2D avatar settings") {

    Scenario("Load motion idle[0] from avatar Mark") {
      Given("A folder path contains json files for a Live2D avatar model")
      val folderPath = "src/test/resources/models/Mark"

      When("Create a MotionData from this Live2D avatar settings")
      val jsonSettingsReader = new JsonSettingsReader(folderPath)
      val settings: Settings = jsonSettingsReader.loadSettings().success.value
      val motionData = CubismMotionData.apply(settings.motionGroups("idle")(0))

      motionData.fps shouldBe 30.0
      motionData.isLoop shouldBe true
      motionData.curveCount shouldBe 37
      motionData.duration shouldBe 10.4f
      val curves = motionData.curvesList
      curves.size shouldBe 37
      curves(0) shouldBe CubismMotionCurve("Opacity", Model, 1, 0, -1.0f, -1.0f)
      curves(1) shouldBe CubismMotionCurve("EyeBlink", Model, 9, 1, -1.0f, -1.0f)
      curves(2) shouldBe CubismMotionCurve("ParamAngleX", Parameter, 16, 10, -1.0f, -1.0f)
      curves(3) shouldBe CubismMotionCurve("ParamAngleY", Parameter, 32, 26, -1.0f, -1.0f)
      curves(4) shouldBe CubismMotionCurve("ParamAngleZ", Parameter, 17, 58, -1.0f, -1.0f)
      curves(5) shouldBe CubismMotionCurve("ParamEyeBallX", Parameter, 21, 75, -1.0f, -1.0f)
      curves(6) shouldBe CubismMotionCurve("ParamEyeBallY", Parameter, 21, 96, -1.0f, -1.0f)
      curves(7) shouldBe CubismMotionCurve("ParamBrowLY", Parameter, 16, 117, -1.0f, -1.0f)
      curves(8) shouldBe CubismMotionCurve("ParamBrowRY", Parameter, 16, 133, -1.0f, -1.0f)
      curves(9) shouldBe CubismMotionCurve("ParamMouthOpenY", Parameter, 16, 149, -1.0f, -1.0f)
      curves(10) shouldBe CubismMotionCurve("ParamArmL", Parameter, 32, 165, -1.0f, -1.0f)
      curves(11) shouldBe CubismMotionCurve("ParamArmR", Parameter, 32, 197, -1.0f, -1.0f)
      curves(12) shouldBe CubismMotionCurve("ParamLeftLeg", Parameter, 16, 229, -1.0f, -1.0f)
      curves(13) shouldBe CubismMotionCurve("ParamRightLeg", Parameter, 16, 245, -1.0f, -1.0f)
      curves(14) shouldBe CubismMotionCurve("ParamBodyAngleX", Parameter, 16, 261, -1.0f, -1.0f)
      curves(15) shouldBe CubismMotionCurve("ParamBodyAngleY", Parameter, 32, 277, -1.0f, -1.0f)
      curves(16) shouldBe CubismMotionCurve("ParamBodyAngleZ", Parameter, 16, 309, -1.0f, -1.0f)
      curves(17) shouldBe CubismMotionCurve("ParamBreath", Parameter, 16, 325, -1.0f, -1.0f)
      curves(18) shouldBe CubismMotionCurve("ParamHairFront", Parameter, 16, 341, -1.0f, -1.0f)
      curves(19) shouldBe CubismMotionCurve("ParamHairSide", Parameter, 16, 357, -1.0f, -1.0f)
      curves(20) shouldBe CubismMotionCurve("ParamHairBack", Parameter, 16, 373, -1.0f, -1.0f)
      curves(21) shouldBe CubismMotionCurve("PartHead", PartOpacity, 1, 389, -1.0f, -1.0f)
      curves(22) shouldBe CubismMotionCurve("PartHairFront", PartOpacity, 1, 390, -1.0f, -1.0f)
      curves(23) shouldBe CubismMotionCurve("PartEyeL", PartOpacity, 1, 391, -1.0f, -1.0f)
      curves(24) shouldBe CubismMotionCurve("PartEyeBallL", PartOpacity, 1, 392, -1.0f, -1.0f)
      curves(25) shouldBe CubismMotionCurve("PartEyeWhiteL", PartOpacity, 1, 393, -1.0f, -1.0f)
      curves(26) shouldBe CubismMotionCurve("PartEyeR", PartOpacity, 1, 394, -1.0f, -1.0f)
      curves(27) shouldBe CubismMotionCurve("PartEyeBallR", PartOpacity, 1, 395, -1.0f, -1.0f)
      curves(28) shouldBe CubismMotionCurve("PartEyeWhiteR", PartOpacity, 1, 396, -1.0f, -1.0f)
      curves(29) shouldBe CubismMotionCurve("PartHairSide", PartOpacity, 1, 397, -1.0f, -1.0f)
      curves(30) shouldBe CubismMotionCurve("PartMouth", PartOpacity, 1, 398, -1.0f, -1.0f)
      curves(31) shouldBe CubismMotionCurve("PartOral", PartOpacity, 1, 399, -1.0f, -1.0f)
      curves(32) shouldBe CubismMotionCurve("PartFace", PartOpacity, 1, 400, -1.0f, -1.0f)
      curves(33) shouldBe CubismMotionCurve("PartBody", PartOpacity, 1, 401, -1.0f, -1.0f)
      curves(34) shouldBe CubismMotionCurve("PartArmL", PartOpacity, 1, 402, -1.0f, -1.0f)
      curves(35) shouldBe CubismMotionCurve("PartArmR", PartOpacity, 1, 403, -1.0f, -1.0f)
      curves(36) shouldBe CubismMotionCurve("PartHairBack", PartOpacity, 1, 404, -1.0f, -1.0f)

      val segments = motionData.segmentsList
      segments.size shouldBe 405
      segments(0) shouldBe CubismMotionSegment(0, Linear)
      segments(1) shouldBe CubismMotionSegment(2, Bezier)
      segments(2) shouldBe CubismMotionSegment(5, Bezier)
      segments(3) shouldBe CubismMotionSegment(8, Bezier)
      segments(4) shouldBe CubismMotionSegment(11, Bezier)
      segments(5) shouldBe CubismMotionSegment(14, Bezier)
      segments(6) shouldBe CubismMotionSegment(17, Bezier)
      segments(7) shouldBe CubismMotionSegment(20, Bezier)
      segments(8) shouldBe CubismMotionSegment(23, Bezier)
      segments(9) shouldBe CubismMotionSegment(26, Linear)
      segments(10) shouldBe CubismMotionSegment(28, Bezier)
      segments(11) shouldBe CubismMotionSegment(31, Bezier)
      segments(12) shouldBe CubismMotionSegment(34, Bezier)
      segments(13) shouldBe CubismMotionSegment(37, Bezier)
      segments(14) shouldBe CubismMotionSegment(40, Bezier)
      segments(15) shouldBe CubismMotionSegment(43, Bezier)
      segments(16) shouldBe CubismMotionSegment(46, Bezier)
      segments(17) shouldBe CubismMotionSegment(49, Bezier)
      segments(18) shouldBe CubismMotionSegment(52, Bezier)
      segments(19) shouldBe CubismMotionSegment(55, Bezier)
      segments(20) shouldBe CubismMotionSegment(58, Bezier)
      segments(21) shouldBe CubismMotionSegment(61, Bezier)
      segments(22) shouldBe CubismMotionSegment(64, Bezier)
      segments(23) shouldBe CubismMotionSegment(67, Bezier)
      segments(24) shouldBe CubismMotionSegment(70, Bezier)
      segments(25) shouldBe CubismMotionSegment(73, Bezier)
      segments(26) shouldBe CubismMotionSegment(77, Bezier)
      segments(27) shouldBe CubismMotionSegment(80, Bezier)
      segments(28) shouldBe CubismMotionSegment(83, Bezier)
      segments(29) shouldBe CubismMotionSegment(86, Bezier)
      segments(30) shouldBe CubismMotionSegment(89, Bezier)
      segments(31) shouldBe CubismMotionSegment(92, Bezier)
      segments(32) shouldBe CubismMotionSegment(95, Bezier)
      segments(33) shouldBe CubismMotionSegment(98, Bezier)
      segments(34) shouldBe CubismMotionSegment(101, Bezier)
      segments(35) shouldBe CubismMotionSegment(104, Bezier)
      segments(36) shouldBe CubismMotionSegment(107, Bezier)
      segments(37) shouldBe CubismMotionSegment(110, Bezier)
      segments(38) shouldBe CubismMotionSegment(113, Bezier)
      segments(39) shouldBe CubismMotionSegment(116, Bezier)
      segments(40) shouldBe CubismMotionSegment(119, Bezier)
      segments(41) shouldBe CubismMotionSegment(122, Bezier)
      segments(42) shouldBe CubismMotionSegment(125, Bezier)
      segments(43) shouldBe CubismMotionSegment(128, Bezier)
      segments(44) shouldBe CubismMotionSegment(131, Bezier)
      segments(45) shouldBe CubismMotionSegment(134, Bezier)
      segments(46) shouldBe CubismMotionSegment(137, Bezier)
      segments(47) shouldBe CubismMotionSegment(140, Bezier)
      segments(48) shouldBe CubismMotionSegment(143, Bezier)
      segments(49) shouldBe CubismMotionSegment(146, Bezier)
      segments(50) shouldBe CubismMotionSegment(149, Bezier)
      segments(51) shouldBe CubismMotionSegment(152, Bezier)
      segments(52) shouldBe CubismMotionSegment(155, Bezier)
      segments(53) shouldBe CubismMotionSegment(158, Bezier)
      segments(54) shouldBe CubismMotionSegment(161, Bezier)
      segments(55) shouldBe CubismMotionSegment(164, Bezier)
      segments(56) shouldBe CubismMotionSegment(167, Bezier)
      segments(57) shouldBe CubismMotionSegment(170, Bezier)
      segments(58) shouldBe CubismMotionSegment(174, Bezier)
      segments(59) shouldBe CubismMotionSegment(177, Bezier)
      segments(60) shouldBe CubismMotionSegment(180, Bezier)
      segments(61) shouldBe CubismMotionSegment(183, Bezier)
      segments(62) shouldBe CubismMotionSegment(186, Bezier)
      segments(63) shouldBe CubismMotionSegment(189, Bezier)
      segments(64) shouldBe CubismMotionSegment(192, Bezier)
      segments(65) shouldBe CubismMotionSegment(195, Bezier)
      segments(66) shouldBe CubismMotionSegment(198, Bezier)
      segments(67) shouldBe CubismMotionSegment(201, Bezier)
      segments(68) shouldBe CubismMotionSegment(204, Bezier)
      segments(69) shouldBe CubismMotionSegment(207, Bezier)
      segments(70) shouldBe CubismMotionSegment(210, Bezier)
      segments(71) shouldBe CubismMotionSegment(213, Bezier)
      segments(72) shouldBe CubismMotionSegment(216, Bezier)
      segments(73) shouldBe CubismMotionSegment(219, Bezier)
      segments(74) shouldBe CubismMotionSegment(222, Bezier)
      segments(75) shouldBe CubismMotionSegment(226, Bezier)
      segments(76) shouldBe CubismMotionSegment(229, Bezier)
      segments(77) shouldBe CubismMotionSegment(232, Bezier)
      segments(78) shouldBe CubismMotionSegment(235, Bezier)
      segments(79) shouldBe CubismMotionSegment(238, Bezier)
      segments(80) shouldBe CubismMotionSegment(241, Bezier)
      segments(81) shouldBe CubismMotionSegment(244, Bezier)
      segments(82) shouldBe CubismMotionSegment(247, Bezier)
      segments(83) shouldBe CubismMotionSegment(250, Bezier)
      segments(84) shouldBe CubismMotionSegment(253, Bezier)
      segments(85) shouldBe CubismMotionSegment(256, Bezier)
      segments(86) shouldBe CubismMotionSegment(259, Bezier)
      segments(87) shouldBe CubismMotionSegment(262, Bezier)
      segments(88) shouldBe CubismMotionSegment(265, Bezier)
      segments(89) shouldBe CubismMotionSegment(268, Bezier)
      segments(90) shouldBe CubismMotionSegment(271, Bezier)
      segments(91) shouldBe CubismMotionSegment(274, Bezier)
      segments(92) shouldBe CubismMotionSegment(277, Bezier)
      segments(93) shouldBe CubismMotionSegment(280, Bezier)
      segments(94) shouldBe CubismMotionSegment(283, Bezier)
      segments(95) shouldBe CubismMotionSegment(286, Bezier)
      segments(96) shouldBe CubismMotionSegment(290, Bezier)
      segments(97) shouldBe CubismMotionSegment(293, Bezier)
      segments(98) shouldBe CubismMotionSegment(296, Bezier)
      segments(99) shouldBe CubismMotionSegment(299, Bezier)
      segments(100) shouldBe CubismMotionSegment(302, Bezier)
      segments(101) shouldBe CubismMotionSegment(305, Bezier)
      segments(102) shouldBe CubismMotionSegment(308, Bezier)
      segments(103) shouldBe CubismMotionSegment(311, Bezier)
      segments(104) shouldBe CubismMotionSegment(314, Bezier)
      segments(105) shouldBe CubismMotionSegment(317, Bezier)
      segments(106) shouldBe CubismMotionSegment(320, Bezier)
      segments(107) shouldBe CubismMotionSegment(323, Bezier)
      segments(108) shouldBe CubismMotionSegment(326, Bezier)
      segments(109) shouldBe CubismMotionSegment(329, Bezier)
      segments(110) shouldBe CubismMotionSegment(332, Bezier)
      segments(111) shouldBe CubismMotionSegment(335, Bezier)
      segments(112) shouldBe CubismMotionSegment(338, Bezier)
      segments(113) shouldBe CubismMotionSegment(341, Bezier)
      segments(114) shouldBe CubismMotionSegment(344, Bezier)
      segments(115) shouldBe CubismMotionSegment(347, Bezier)
      segments(116) shouldBe CubismMotionSegment(350, Bezier)
      segments(117) shouldBe CubismMotionSegment(354, Bezier)
      segments(118) shouldBe CubismMotionSegment(357, Bezier)
      segments(119) shouldBe CubismMotionSegment(360, Bezier)
      segments(120) shouldBe CubismMotionSegment(363, Bezier)
      segments(121) shouldBe CubismMotionSegment(366, Bezier)
      segments(122) shouldBe CubismMotionSegment(369, Bezier)
      segments(123) shouldBe CubismMotionSegment(372, Bezier)
      segments(124) shouldBe CubismMotionSegment(375, Bezier)
      segments(125) shouldBe CubismMotionSegment(378, Bezier)
      segments(126) shouldBe CubismMotionSegment(381, Bezier)
      segments(127) shouldBe CubismMotionSegment(384, Bezier)
      segments(128) shouldBe CubismMotionSegment(387, Bezier)
      segments(129) shouldBe CubismMotionSegment(390, Bezier)
      segments(130) shouldBe CubismMotionSegment(393, Bezier)
      segments(131) shouldBe CubismMotionSegment(396, Bezier)
      segments(132) shouldBe CubismMotionSegment(399, Bezier)
      segments(133) shouldBe CubismMotionSegment(403, Bezier)
      segments(134) shouldBe CubismMotionSegment(406, Bezier)
      segments(135) shouldBe CubismMotionSegment(409, Bezier)
      segments(136) shouldBe CubismMotionSegment(412, Bezier)
      segments(137) shouldBe CubismMotionSegment(415, Bezier)
      segments(138) shouldBe CubismMotionSegment(418, Bezier)
      segments(139) shouldBe CubismMotionSegment(421, Bezier)
      segments(140) shouldBe CubismMotionSegment(424, Bezier)
      segments(141) shouldBe CubismMotionSegment(427, Bezier)
      segments(142) shouldBe CubismMotionSegment(430, Bezier)
      segments(143) shouldBe CubismMotionSegment(433, Bezier)
      segments(144) shouldBe CubismMotionSegment(436, Bezier)
      segments(145) shouldBe CubismMotionSegment(439, Bezier)
      segments(146) shouldBe CubismMotionSegment(442, Bezier)
      segments(147) shouldBe CubismMotionSegment(445, Bezier)
      segments(148) shouldBe CubismMotionSegment(448, Bezier)
      segments(149) shouldBe CubismMotionSegment(452, Bezier)
      segments(150) shouldBe CubismMotionSegment(455, Bezier)
      segments(151) shouldBe CubismMotionSegment(458, Bezier)
      segments(152) shouldBe CubismMotionSegment(461, Bezier)
      segments(153) shouldBe CubismMotionSegment(464, Bezier)
      segments(154) shouldBe CubismMotionSegment(467, Bezier)
      segments(155) shouldBe CubismMotionSegment(470, Bezier)
      segments(156) shouldBe CubismMotionSegment(473, Bezier)
      segments(157) shouldBe CubismMotionSegment(476, Bezier)
      segments(158) shouldBe CubismMotionSegment(479, Bezier)
      segments(159) shouldBe CubismMotionSegment(482, Bezier)
      segments(160) shouldBe CubismMotionSegment(485, Bezier)
      segments(161) shouldBe CubismMotionSegment(488, Bezier)
      segments(162) shouldBe CubismMotionSegment(491, Bezier)
      segments(163) shouldBe CubismMotionSegment(494, Bezier)
      segments(164) shouldBe CubismMotionSegment(497, Bezier)
      segments(165) shouldBe CubismMotionSegment(501, Bezier)
      segments(166) shouldBe CubismMotionSegment(504, Bezier)
      segments(167) shouldBe CubismMotionSegment(507, Bezier)
      segments(168) shouldBe CubismMotionSegment(510, Bezier)
      segments(169) shouldBe CubismMotionSegment(513, Bezier)
      segments(170) shouldBe CubismMotionSegment(516, Bezier)
      segments(171) shouldBe CubismMotionSegment(519, Bezier)
      segments(172) shouldBe CubismMotionSegment(522, Bezier)
      segments(173) shouldBe CubismMotionSegment(525, Bezier)
      segments(174) shouldBe CubismMotionSegment(528, Bezier)
      segments(175) shouldBe CubismMotionSegment(531, Bezier)
      segments(176) shouldBe CubismMotionSegment(534, Bezier)
      segments(177) shouldBe CubismMotionSegment(537, Bezier)
      segments(178) shouldBe CubismMotionSegment(540, Bezier)
      segments(179) shouldBe CubismMotionSegment(543, Bezier)
      segments(180) shouldBe CubismMotionSegment(546, Bezier)
      segments(181) shouldBe CubismMotionSegment(549, Bezier)
      segments(182) shouldBe CubismMotionSegment(552, Bezier)
      segments(183) shouldBe CubismMotionSegment(555, Bezier)
      segments(184) shouldBe CubismMotionSegment(558, Bezier)
      segments(185) shouldBe CubismMotionSegment(561, Bezier)
      segments(186) shouldBe CubismMotionSegment(564, Bezier)
      segments(187) shouldBe CubismMotionSegment(567, Bezier)
      segments(188) shouldBe CubismMotionSegment(570, Bezier)
      segments(189) shouldBe CubismMotionSegment(573, Bezier)
      segments(190) shouldBe CubismMotionSegment(576, Bezier)
      segments(191) shouldBe CubismMotionSegment(579, Bezier)
      segments(192) shouldBe CubismMotionSegment(582, Bezier)
      segments(193) shouldBe CubismMotionSegment(585, Bezier)
      segments(194) shouldBe CubismMotionSegment(588, Bezier)
      segments(195) shouldBe CubismMotionSegment(591, Bezier)
      segments(196) shouldBe CubismMotionSegment(594, Bezier)
      segments(197) shouldBe CubismMotionSegment(598, Bezier)
      segments(198) shouldBe CubismMotionSegment(601, Bezier)
      segments(199) shouldBe CubismMotionSegment(604, Bezier)
      segments(200) shouldBe CubismMotionSegment(607, Bezier)
      segments(201) shouldBe CubismMotionSegment(610, Bezier)
      segments(202) shouldBe CubismMotionSegment(613, Bezier)
      segments(203) shouldBe CubismMotionSegment(616, Bezier)
      segments(204) shouldBe CubismMotionSegment(619, Bezier)
      segments(205) shouldBe CubismMotionSegment(622, Bezier)
      segments(206) shouldBe CubismMotionSegment(625, Bezier)
      segments(207) shouldBe CubismMotionSegment(628, Bezier)
      segments(208) shouldBe CubismMotionSegment(631, Bezier)
      segments(209) shouldBe CubismMotionSegment(634, Bezier)
      segments(210) shouldBe CubismMotionSegment(637, Bezier)
      segments(211) shouldBe CubismMotionSegment(640, Bezier)
      segments(212) shouldBe CubismMotionSegment(643, Bezier)
      segments(213) shouldBe CubismMotionSegment(646, Bezier)
      segments(214) shouldBe CubismMotionSegment(649, Bezier)
      segments(215) shouldBe CubismMotionSegment(652, Bezier)
      segments(216) shouldBe CubismMotionSegment(655, Bezier)
      segments(217) shouldBe CubismMotionSegment(658, Bezier)
      segments(218) shouldBe CubismMotionSegment(661, Bezier)
      segments(219) shouldBe CubismMotionSegment(664, Bezier)
      segments(220) shouldBe CubismMotionSegment(667, Bezier)
      segments(221) shouldBe CubismMotionSegment(670, Bezier)
      segments(222) shouldBe CubismMotionSegment(673, Bezier)
      segments(223) shouldBe CubismMotionSegment(676, Bezier)
      segments(224) shouldBe CubismMotionSegment(679, Bezier)
      segments(225) shouldBe CubismMotionSegment(682, Bezier)
      segments(226) shouldBe CubismMotionSegment(685, Bezier)
      segments(227) shouldBe CubismMotionSegment(688, Bezier)
      segments(228) shouldBe CubismMotionSegment(691, Bezier)
      segments(229) shouldBe CubismMotionSegment(695, Bezier)
      segments(230) shouldBe CubismMotionSegment(698, Bezier)
      segments(231) shouldBe CubismMotionSegment(701, Bezier)
      segments(232) shouldBe CubismMotionSegment(704, Bezier)
      segments(233) shouldBe CubismMotionSegment(707, Bezier)
      segments(234) shouldBe CubismMotionSegment(710, Bezier)
      segments(235) shouldBe CubismMotionSegment(713, Bezier)
      segments(236) shouldBe CubismMotionSegment(716, Bezier)
      segments(237) shouldBe CubismMotionSegment(719, Bezier)
      segments(238) shouldBe CubismMotionSegment(722, Bezier)
      segments(239) shouldBe CubismMotionSegment(725, Bezier)
      segments(240) shouldBe CubismMotionSegment(728, Bezier)
      segments(241) shouldBe CubismMotionSegment(731, Bezier)
      segments(242) shouldBe CubismMotionSegment(734, Bezier)
      segments(243) shouldBe CubismMotionSegment(737, Bezier)
      segments(244) shouldBe CubismMotionSegment(740, Bezier)
      segments(245) shouldBe CubismMotionSegment(744, Bezier)
      segments(246) shouldBe CubismMotionSegment(747, Bezier)
      segments(247) shouldBe CubismMotionSegment(750, Bezier)
      segments(248) shouldBe CubismMotionSegment(753, Bezier)
      segments(249) shouldBe CubismMotionSegment(756, Bezier)
      segments(250) shouldBe CubismMotionSegment(759, Bezier)
      segments(251) shouldBe CubismMotionSegment(762, Bezier)
      segments(252) shouldBe CubismMotionSegment(765, Bezier)
      segments(253) shouldBe CubismMotionSegment(768, Bezier)
      segments(254) shouldBe CubismMotionSegment(771, Bezier)
      segments(255) shouldBe CubismMotionSegment(774, Bezier)
      segments(256) shouldBe CubismMotionSegment(777, Bezier)
      segments(257) shouldBe CubismMotionSegment(780, Bezier)
      segments(258) shouldBe CubismMotionSegment(783, Bezier)
      segments(259) shouldBe CubismMotionSegment(786, Bezier)
      segments(260) shouldBe CubismMotionSegment(789, Bezier)
      segments(261) shouldBe CubismMotionSegment(793, Bezier)
      segments(262) shouldBe CubismMotionSegment(796, Bezier)
      segments(263) shouldBe CubismMotionSegment(799, Bezier)
      segments(264) shouldBe CubismMotionSegment(802, Bezier)
      segments(265) shouldBe CubismMotionSegment(805, Bezier)
      segments(266) shouldBe CubismMotionSegment(808, Bezier)
      segments(267) shouldBe CubismMotionSegment(811, Bezier)
      segments(268) shouldBe CubismMotionSegment(814, Bezier)
      segments(269) shouldBe CubismMotionSegment(817, Bezier)
      segments(270) shouldBe CubismMotionSegment(820, Bezier)
      segments(271) shouldBe CubismMotionSegment(823, Bezier)
      segments(272) shouldBe CubismMotionSegment(826, Bezier)
      segments(273) shouldBe CubismMotionSegment(829, Bezier)
      segments(274) shouldBe CubismMotionSegment(832, Bezier)
      segments(275) shouldBe CubismMotionSegment(835, Bezier)
      segments(276) shouldBe CubismMotionSegment(838, Bezier)
      segments(277) shouldBe CubismMotionSegment(842, Bezier)
      segments(278) shouldBe CubismMotionSegment(845, Bezier)
      segments(279) shouldBe CubismMotionSegment(848, Bezier)
      segments(280) shouldBe CubismMotionSegment(851, Bezier)
      segments(281) shouldBe CubismMotionSegment(854, Bezier)
      segments(282) shouldBe CubismMotionSegment(857, Bezier)
      segments(283) shouldBe CubismMotionSegment(860, Bezier)
      segments(284) shouldBe CubismMotionSegment(863, Bezier)
      segments(285) shouldBe CubismMotionSegment(866, Bezier)
      segments(286) shouldBe CubismMotionSegment(869, Bezier)
      segments(287) shouldBe CubismMotionSegment(872, Bezier)
      segments(288) shouldBe CubismMotionSegment(875, Bezier)
      segments(289) shouldBe CubismMotionSegment(878, Bezier)
      segments(290) shouldBe CubismMotionSegment(881, Bezier)
      segments(291) shouldBe CubismMotionSegment(884, Bezier)
      segments(292) shouldBe CubismMotionSegment(887, Bezier)
      segments(293) shouldBe CubismMotionSegment(890, Bezier)
      segments(294) shouldBe CubismMotionSegment(893, Bezier)
      segments(295) shouldBe CubismMotionSegment(896, Bezier)
      segments(296) shouldBe CubismMotionSegment(899, Bezier)
      segments(297) shouldBe CubismMotionSegment(902, Bezier)
      segments(298) shouldBe CubismMotionSegment(905, Bezier)
      segments(299) shouldBe CubismMotionSegment(908, Bezier)
      segments(300) shouldBe CubismMotionSegment(911, Bezier)
      segments(301) shouldBe CubismMotionSegment(914, Bezier)
      segments(302) shouldBe CubismMotionSegment(917, Bezier)
      segments(303) shouldBe CubismMotionSegment(920, Bezier)
      segments(304) shouldBe CubismMotionSegment(923, Bezier)
      segments(305) shouldBe CubismMotionSegment(926, Bezier)
      segments(306) shouldBe CubismMotionSegment(929, Bezier)
      segments(307) shouldBe CubismMotionSegment(932, Bezier)
      segments(308) shouldBe CubismMotionSegment(935, Bezier)
      segments(309) shouldBe CubismMotionSegment(939, Bezier)
      segments(310) shouldBe CubismMotionSegment(942, Bezier)
      segments(311) shouldBe CubismMotionSegment(945, Bezier)
      segments(312) shouldBe CubismMotionSegment(948, Bezier)
      segments(313) shouldBe CubismMotionSegment(951, Bezier)
      segments(314) shouldBe CubismMotionSegment(954, Bezier)
      segments(315) shouldBe CubismMotionSegment(957, Bezier)
      segments(316) shouldBe CubismMotionSegment(960, Bezier)
      segments(317) shouldBe CubismMotionSegment(963, Bezier)
      segments(318) shouldBe CubismMotionSegment(966, Bezier)
      segments(319) shouldBe CubismMotionSegment(969, Bezier)
      segments(320) shouldBe CubismMotionSegment(972, Bezier)
      segments(321) shouldBe CubismMotionSegment(975, Bezier)
      segments(322) shouldBe CubismMotionSegment(978, Bezier)
      segments(323) shouldBe CubismMotionSegment(981, Bezier)
      segments(324) shouldBe CubismMotionSegment(984, Bezier)
      segments(325) shouldBe CubismMotionSegment(988, Bezier)
      segments(326) shouldBe CubismMotionSegment(991, Bezier)
      segments(327) shouldBe CubismMotionSegment(994, Bezier)
      segments(328) shouldBe CubismMotionSegment(997, Bezier)
      segments(329) shouldBe CubismMotionSegment(1000, Bezier)
      segments(330) shouldBe CubismMotionSegment(1003, Bezier)
      segments(331) shouldBe CubismMotionSegment(1006, Bezier)
      segments(332) shouldBe CubismMotionSegment(1009, Bezier)
      segments(333) shouldBe CubismMotionSegment(1012, Bezier)
      segments(334) shouldBe CubismMotionSegment(1015, Bezier)
      segments(335) shouldBe CubismMotionSegment(1018, Bezier)
      segments(336) shouldBe CubismMotionSegment(1021, Bezier)
      segments(337) shouldBe CubismMotionSegment(1024, Bezier)
      segments(338) shouldBe CubismMotionSegment(1027, Bezier)
      segments(339) shouldBe CubismMotionSegment(1030, Bezier)
      segments(340) shouldBe CubismMotionSegment(1033, Bezier)
      segments(341) shouldBe CubismMotionSegment(1037, Bezier)
      segments(342) shouldBe CubismMotionSegment(1040, Bezier)
      segments(343) shouldBe CubismMotionSegment(1043, Bezier)
      segments(344) shouldBe CubismMotionSegment(1046, Bezier)
      segments(345) shouldBe CubismMotionSegment(1049, Bezier)
      segments(346) shouldBe CubismMotionSegment(1052, Bezier)
      segments(347) shouldBe CubismMotionSegment(1055, Bezier)
      segments(348) shouldBe CubismMotionSegment(1058, Bezier)
      segments(349) shouldBe CubismMotionSegment(1061, Bezier)
      segments(350) shouldBe CubismMotionSegment(1064, Bezier)
      segments(351) shouldBe CubismMotionSegment(1067, Bezier)
      segments(352) shouldBe CubismMotionSegment(1070, Bezier)
      segments(353) shouldBe CubismMotionSegment(1073, Bezier)
      segments(354) shouldBe CubismMotionSegment(1076, Bezier)
      segments(355) shouldBe CubismMotionSegment(1079, Bezier)
      segments(356) shouldBe CubismMotionSegment(1082, Bezier)
      segments(357) shouldBe CubismMotionSegment(1086, Bezier)
      segments(358) shouldBe CubismMotionSegment(1089, Bezier)
      segments(359) shouldBe CubismMotionSegment(1092, Bezier)
      segments(360) shouldBe CubismMotionSegment(1095, Bezier)
      segments(361) shouldBe CubismMotionSegment(1098, Bezier)
      segments(362) shouldBe CubismMotionSegment(1101, Bezier)
      segments(363) shouldBe CubismMotionSegment(1104, Bezier)
      segments(364) shouldBe CubismMotionSegment(1107, Bezier)
      segments(365) shouldBe CubismMotionSegment(1110, Bezier)
      segments(366) shouldBe CubismMotionSegment(1113, Bezier)
      segments(367) shouldBe CubismMotionSegment(1116, Bezier)
      segments(368) shouldBe CubismMotionSegment(1119, Bezier)
      segments(369) shouldBe CubismMotionSegment(1122, Bezier)
      segments(370) shouldBe CubismMotionSegment(1125, Bezier)
      segments(371) shouldBe CubismMotionSegment(1128, Bezier)
      segments(372) shouldBe CubismMotionSegment(1131, Bezier)
      segments(373) shouldBe CubismMotionSegment(1135, Bezier)
      segments(374) shouldBe CubismMotionSegment(1138, Bezier)
      segments(375) shouldBe CubismMotionSegment(1141, Bezier)
      segments(376) shouldBe CubismMotionSegment(1144, Bezier)
      segments(377) shouldBe CubismMotionSegment(1147, Bezier)
      segments(378) shouldBe CubismMotionSegment(1150, Bezier)
      segments(379) shouldBe CubismMotionSegment(1153, Bezier)
      segments(380) shouldBe CubismMotionSegment(1156, Bezier)
      segments(381) shouldBe CubismMotionSegment(1159, Bezier)
      segments(382) shouldBe CubismMotionSegment(1162, Bezier)
      segments(383) shouldBe CubismMotionSegment(1165, Bezier)
      segments(384) shouldBe CubismMotionSegment(1168, Bezier)
      segments(385) shouldBe CubismMotionSegment(1171, Bezier)
      segments(386) shouldBe CubismMotionSegment(1174, Bezier)
      segments(387) shouldBe CubismMotionSegment(1177, Bezier)
      segments(388) shouldBe CubismMotionSegment(1180, Bezier)
      segments(389) shouldBe CubismMotionSegment(1184, Linear)
      segments(390) shouldBe CubismMotionSegment(1186, Linear)
      segments(391) shouldBe CubismMotionSegment(1188, Linear)
      segments(392) shouldBe CubismMotionSegment(1190, Linear)
      segments(393) shouldBe CubismMotionSegment(1192, Linear)
      segments(394) shouldBe CubismMotionSegment(1194, Linear)
      segments(395) shouldBe CubismMotionSegment(1196, Linear)
      segments(396) shouldBe CubismMotionSegment(1198, Linear)
      segments(397) shouldBe CubismMotionSegment(1200, Linear)
      segments(398) shouldBe CubismMotionSegment(1202, Linear)
      segments(399) shouldBe CubismMotionSegment(1204, Linear)
      segments(400) shouldBe CubismMotionSegment(1206, Linear)
      segments(401) shouldBe CubismMotionSegment(1208, Linear)
      segments(402) shouldBe CubismMotionSegment(1210, Linear)
      segments(403) shouldBe CubismMotionSegment(1212, Linear)
      segments(404) shouldBe CubismMotionSegment(1214, Linear)

      assertPointList("src/test/resources/expectation/markMotionIdle0Points.csv", motionData.pointsList)
    }

    Scenario("Load motion idle[1] from avatar Mark") {
      Given("A folder path contains json files for a Live2D avatar model")
      val folderPath = "src/test/resources/models/Mark"

      When("Create a MotionData from this Live2D avatar settings")
      val jsonSettingsReader = new JsonSettingsReader(folderPath)
      val settings: Settings = jsonSettingsReader.loadSettings().success.value
      val motionData = CubismMotionData.apply(settings.motionGroups("idle")(1))

      motionData.fps shouldBe 30.0
      motionData.isLoop shouldBe true
      motionData.curveCount shouldBe 37
      motionData.duration shouldBe 4.8f

      val curves = motionData.curvesList
      curves.size shouldBe 37
      curves(0) shouldBe CubismMotionCurve("Opacity", Model, 1, 0, -1.0f, -1.0f)
      curves(1) shouldBe CubismMotionCurve("EyeBlink", Model, 1, 1, -1.0f, -1.0f)
      curves(2) shouldBe CubismMotionCurve("ParamAngleX", Parameter, 16, 2, -1.0f, -1.0f)
      curves(3) shouldBe CubismMotionCurve("ParamAngleY", Parameter, 17, 18, -1.0f, -1.0f)
      curves(4) shouldBe CubismMotionCurve("ParamAngleZ", Parameter, 9, 35, -1.0f, -1.0f)
      curves(5) shouldBe CubismMotionCurve("ParamEyeBallX", Parameter, 8, 44, -1.0f, -1.0f)
      curves(6) shouldBe CubismMotionCurve("ParamEyeBallY", Parameter, 8, 52, -1.0f, -1.0f)
      curves(7) shouldBe CubismMotionCurve("ParamBrowLY", Parameter, 8, 60, -1.0f, -1.0f)
      curves(8) shouldBe CubismMotionCurve("ParamBrowRY", Parameter, 8, 68, -1.0f, -1.0f)
      curves(9) shouldBe CubismMotionCurve("ParamMouthOpenY", Parameter, 8, 76, -1.0f, -1.0f)
      curves(10) shouldBe CubismMotionCurve("ParamArmL", Parameter, 16, 84, -1.0f, -1.0f)
      curves(11) shouldBe CubismMotionCurve("ParamArmR", Parameter, 16, 100, -1.0f, -1.0f)
      curves(12) shouldBe CubismMotionCurve("ParamLeftLeg", Parameter, 16, 116, -1.0f, -1.0f)
      curves(13) shouldBe CubismMotionCurve("ParamRightLeg", Parameter, 16, 132, -1.0f, -1.0f)
      curves(14) shouldBe CubismMotionCurve("ParamBodyAngleX", Parameter, 16, 148, -1.0f, -1.0f)
      curves(15) shouldBe CubismMotionCurve("ParamBodyAngleY", Parameter, 32, 164, -1.0f, -1.0f)
      curves(16) shouldBe CubismMotionCurve("ParamBodyAngleZ", Parameter, 16, 196, -1.0f, -1.0f)
      curves(17) shouldBe CubismMotionCurve("ParamBreath", Parameter, 8, 212, -1.0f, -1.0f)
      curves(18) shouldBe CubismMotionCurve("ParamHairFront", Parameter, 8, 220, -1.0f, -1.0f)
      curves(19) shouldBe CubismMotionCurve("ParamHairSide", Parameter, 8, 228, -1.0f, -1.0f)
      curves(20) shouldBe CubismMotionCurve("ParamHairBack", Parameter, 8, 236, -1.0f, -1.0f)
      curves(21) shouldBe CubismMotionCurve("PartHead", PartOpacity, 1, 244, -1.0f, -1.0f)
      curves(22) shouldBe CubismMotionCurve("PartHairFront", PartOpacity, 1, 245, -1.0f, -1.0f)
      curves(23) shouldBe CubismMotionCurve("PartEyeL", PartOpacity, 1, 246, -1.0f, -1.0f)
      curves(24) shouldBe CubismMotionCurve("PartEyeBallL", PartOpacity, 1, 247, -1.0f, -1.0f)
      curves(25) shouldBe CubismMotionCurve("PartEyeWhiteL", PartOpacity, 1, 248, -1.0f, -1.0f)
      curves(26) shouldBe CubismMotionCurve("PartEyeR", PartOpacity, 1, 249, -1.0f, -1.0f)
      curves(27) shouldBe CubismMotionCurve("PartEyeBallR", PartOpacity, 1, 250, -1.0f, -1.0f)
      curves(28) shouldBe CubismMotionCurve("PartEyeWhiteR", PartOpacity, 1, 251, -1.0f, -1.0f)
      curves(29) shouldBe CubismMotionCurve("PartHairSide", PartOpacity, 1, 252, -1.0f, -1.0f)
      curves(30) shouldBe CubismMotionCurve("PartMouth", PartOpacity, 1, 253, -1.0f, -1.0f)
      curves(31) shouldBe CubismMotionCurve("PartOral", PartOpacity, 1, 254, -1.0f, -1.0f)
      curves(32) shouldBe CubismMotionCurve("PartFace", PartOpacity, 1, 255, -1.0f, -1.0f)
      curves(33) shouldBe CubismMotionCurve("PartBody", PartOpacity, 1, 256, -1.0f, -1.0f)
      curves(34) shouldBe CubismMotionCurve("PartArmL", PartOpacity, 1, 257, -1.0f, -1.0f)
      curves(35) shouldBe CubismMotionCurve("PartArmR", PartOpacity, 1, 258, -1.0f, -1.0f)
      curves(36) shouldBe CubismMotionCurve("PartHairBack", PartOpacity, 1, 259, -1.0f, -1.0f)

      val segments = motionData.segmentsList
      segments.size shouldBe 260
      segments(0) shouldBe CubismMotionSegment(0, Linear)
      segments(1) shouldBe CubismMotionSegment(2, Linear)
      segments(2) shouldBe CubismMotionSegment(4, Bezier)
      segments(3) shouldBe CubismMotionSegment(7, Bezier)
      segments(4) shouldBe CubismMotionSegment(10, Bezier)
      segments(5) shouldBe CubismMotionSegment(13, Bezier)
      segments(6) shouldBe CubismMotionSegment(16, Bezier)
      segments(7) shouldBe CubismMotionSegment(19, Bezier)
      segments(8) shouldBe CubismMotionSegment(22, Bezier)
      segments(9) shouldBe CubismMotionSegment(25, Bezier)
      segments(10) shouldBe CubismMotionSegment(28, Bezier)
      segments(11) shouldBe CubismMotionSegment(31, Bezier)
      segments(12) shouldBe CubismMotionSegment(34, Bezier)
      segments(13) shouldBe CubismMotionSegment(37, Bezier)
      segments(14) shouldBe CubismMotionSegment(40, Bezier)
      segments(15) shouldBe CubismMotionSegment(43, Bezier)
      segments(16) shouldBe CubismMotionSegment(46, Bezier)
      segments(17) shouldBe CubismMotionSegment(49, Bezier)
      segments(18) shouldBe CubismMotionSegment(53, Bezier)
      segments(19) shouldBe CubismMotionSegment(56, Bezier)
      segments(20) shouldBe CubismMotionSegment(59, Bezier)
      segments(21) shouldBe CubismMotionSegment(62, Bezier)
      segments(22) shouldBe CubismMotionSegment(65, Bezier)
      segments(23) shouldBe CubismMotionSegment(68, Bezier)
      segments(24) shouldBe CubismMotionSegment(71, Bezier)
      segments(25) shouldBe CubismMotionSegment(74, Bezier)
      segments(26) shouldBe CubismMotionSegment(77, Bezier)
      segments(27) shouldBe CubismMotionSegment(80, Bezier)
      segments(28) shouldBe CubismMotionSegment(83, Bezier)
      segments(29) shouldBe CubismMotionSegment(86, Bezier)
      segments(30) shouldBe CubismMotionSegment(89, Bezier)
      segments(31) shouldBe CubismMotionSegment(92, Bezier)
      segments(32) shouldBe CubismMotionSegment(95, Bezier)
      segments(33) shouldBe CubismMotionSegment(98, Bezier)
      segments(34) shouldBe CubismMotionSegment(101, Bezier)
      segments(35) shouldBe CubismMotionSegment(105, Bezier)
      segments(36) shouldBe CubismMotionSegment(108, Bezier)
      segments(37) shouldBe CubismMotionSegment(111, Bezier)
      segments(38) shouldBe CubismMotionSegment(114, Bezier)
      segments(39) shouldBe CubismMotionSegment(117, Bezier)
      segments(40) shouldBe CubismMotionSegment(120, Bezier)
      segments(41) shouldBe CubismMotionSegment(123, Bezier)
      segments(42) shouldBe CubismMotionSegment(126, Bezier)
      segments(43) shouldBe CubismMotionSegment(129, Bezier)
      segments(44) shouldBe CubismMotionSegment(133, Bezier)
      segments(45) shouldBe CubismMotionSegment(136, Bezier)
      segments(46) shouldBe CubismMotionSegment(139, Bezier)
      segments(47) shouldBe CubismMotionSegment(142, Bezier)
      segments(48) shouldBe CubismMotionSegment(145, Bezier)
      segments(49) shouldBe CubismMotionSegment(148, Bezier)
      segments(50) shouldBe CubismMotionSegment(151, Bezier)
      segments(51) shouldBe CubismMotionSegment(154, Bezier)
      segments(52) shouldBe CubismMotionSegment(158, Bezier)
      segments(53) shouldBe CubismMotionSegment(161, Bezier)
      segments(54) shouldBe CubismMotionSegment(164, Bezier)
      segments(55) shouldBe CubismMotionSegment(167, Bezier)
      segments(56) shouldBe CubismMotionSegment(170, Bezier)
      segments(57) shouldBe CubismMotionSegment(173, Bezier)
      segments(58) shouldBe CubismMotionSegment(176, Bezier)
      segments(59) shouldBe CubismMotionSegment(179, Bezier)
      segments(60) shouldBe CubismMotionSegment(183, Bezier)
      segments(61) shouldBe CubismMotionSegment(186, Bezier)
      segments(62) shouldBe CubismMotionSegment(189, Bezier)
      segments(63) shouldBe CubismMotionSegment(192, Bezier)
      segments(64) shouldBe CubismMotionSegment(195, Bezier)
      segments(65) shouldBe CubismMotionSegment(198, Bezier)
      segments(66) shouldBe CubismMotionSegment(201, Bezier)
      segments(67) shouldBe CubismMotionSegment(204, Bezier)
      segments(68) shouldBe CubismMotionSegment(208, Bezier)
      segments(69) shouldBe CubismMotionSegment(211, Bezier)
      segments(70) shouldBe CubismMotionSegment(214, Bezier)
      segments(71) shouldBe CubismMotionSegment(217, Bezier)
      segments(72) shouldBe CubismMotionSegment(220, Bezier)
      segments(73) shouldBe CubismMotionSegment(223, Bezier)
      segments(74) shouldBe CubismMotionSegment(226, Bezier)
      segments(75) shouldBe CubismMotionSegment(229, Bezier)
      segments(76) shouldBe CubismMotionSegment(233, Bezier)
      segments(77) shouldBe CubismMotionSegment(236, Bezier)
      segments(78) shouldBe CubismMotionSegment(239, Bezier)
      segments(79) shouldBe CubismMotionSegment(242, Bezier)
      segments(80) shouldBe CubismMotionSegment(245, Bezier)
      segments(81) shouldBe CubismMotionSegment(248, Bezier)
      segments(82) shouldBe CubismMotionSegment(251, Bezier)
      segments(83) shouldBe CubismMotionSegment(254, Bezier)
      segments(84) shouldBe CubismMotionSegment(258, Bezier)
      segments(85) shouldBe CubismMotionSegment(261, Bezier)
      segments(86) shouldBe CubismMotionSegment(264, Bezier)
      segments(87) shouldBe CubismMotionSegment(267, Bezier)
      segments(88) shouldBe CubismMotionSegment(270, Bezier)
      segments(89) shouldBe CubismMotionSegment(273, Bezier)
      segments(90) shouldBe CubismMotionSegment(276, Bezier)
      segments(91) shouldBe CubismMotionSegment(279, Bezier)
      segments(92) shouldBe CubismMotionSegment(282, Bezier)
      segments(93) shouldBe CubismMotionSegment(285, Bezier)
      segments(94) shouldBe CubismMotionSegment(288, Bezier)
      segments(95) shouldBe CubismMotionSegment(291, Bezier)
      segments(96) shouldBe CubismMotionSegment(294, Bezier)
      segments(97) shouldBe CubismMotionSegment(297, Bezier)
      segments(98) shouldBe CubismMotionSegment(300, Bezier)
      segments(99) shouldBe CubismMotionSegment(303, Bezier)
      segments(100) shouldBe CubismMotionSegment(307, Bezier)
      segments(101) shouldBe CubismMotionSegment(310, Bezier)
      segments(102) shouldBe CubismMotionSegment(313, Bezier)
      segments(103) shouldBe CubismMotionSegment(316, Bezier)
      segments(104) shouldBe CubismMotionSegment(319, Bezier)
      segments(105) shouldBe CubismMotionSegment(322, Bezier)
      segments(106) shouldBe CubismMotionSegment(325, Bezier)
      segments(107) shouldBe CubismMotionSegment(328, Bezier)
      segments(108) shouldBe CubismMotionSegment(331, Bezier)
      segments(109) shouldBe CubismMotionSegment(334, Bezier)
      segments(110) shouldBe CubismMotionSegment(337, Bezier)
      segments(111) shouldBe CubismMotionSegment(340, Bezier)
      segments(112) shouldBe CubismMotionSegment(343, Bezier)
      segments(113) shouldBe CubismMotionSegment(346, Bezier)
      segments(114) shouldBe CubismMotionSegment(349, Bezier)
      segments(115) shouldBe CubismMotionSegment(352, Bezier)
      segments(116) shouldBe CubismMotionSegment(356, Bezier)
      segments(117) shouldBe CubismMotionSegment(359, Bezier)
      segments(118) shouldBe CubismMotionSegment(362, Bezier)
      segments(119) shouldBe CubismMotionSegment(365, Bezier)
      segments(120) shouldBe CubismMotionSegment(368, Bezier)
      segments(121) shouldBe CubismMotionSegment(371, Bezier)
      segments(122) shouldBe CubismMotionSegment(374, Bezier)
      segments(123) shouldBe CubismMotionSegment(377, Bezier)
      segments(124) shouldBe CubismMotionSegment(380, Bezier)
      segments(125) shouldBe CubismMotionSegment(383, Bezier)
      segments(126) shouldBe CubismMotionSegment(386, Bezier)
      segments(127) shouldBe CubismMotionSegment(389, Bezier)
      segments(128) shouldBe CubismMotionSegment(392, Bezier)
      segments(129) shouldBe CubismMotionSegment(395, Bezier)
      segments(130) shouldBe CubismMotionSegment(398, Bezier)
      segments(131) shouldBe CubismMotionSegment(401, Bezier)
      segments(132) shouldBe CubismMotionSegment(405, Bezier)
      segments(133) shouldBe CubismMotionSegment(408, Bezier)
      segments(134) shouldBe CubismMotionSegment(411, Bezier)
      segments(135) shouldBe CubismMotionSegment(414, Bezier)
      segments(136) shouldBe CubismMotionSegment(417, Bezier)
      segments(137) shouldBe CubismMotionSegment(420, Bezier)
      segments(138) shouldBe CubismMotionSegment(423, Bezier)
      segments(139) shouldBe CubismMotionSegment(426, Bezier)
      segments(140) shouldBe CubismMotionSegment(429, Bezier)
      segments(141) shouldBe CubismMotionSegment(432, Bezier)
      segments(142) shouldBe CubismMotionSegment(435, Bezier)
      segments(143) shouldBe CubismMotionSegment(438, Bezier)
      segments(144) shouldBe CubismMotionSegment(441, Bezier)
      segments(145) shouldBe CubismMotionSegment(444, Bezier)
      segments(146) shouldBe CubismMotionSegment(447, Bezier)
      segments(147) shouldBe CubismMotionSegment(450, Bezier)
      segments(148) shouldBe CubismMotionSegment(454, Bezier)
      segments(149) shouldBe CubismMotionSegment(457, Bezier)
      segments(150) shouldBe CubismMotionSegment(460, Bezier)
      segments(151) shouldBe CubismMotionSegment(463, Bezier)
      segments(152) shouldBe CubismMotionSegment(466, Bezier)
      segments(153) shouldBe CubismMotionSegment(469, Bezier)
      segments(154) shouldBe CubismMotionSegment(472, Bezier)
      segments(155) shouldBe CubismMotionSegment(475, Bezier)
      segments(156) shouldBe CubismMotionSegment(478, Bezier)
      segments(157) shouldBe CubismMotionSegment(481, Bezier)
      segments(158) shouldBe CubismMotionSegment(484, Bezier)
      segments(159) shouldBe CubismMotionSegment(487, Bezier)
      segments(160) shouldBe CubismMotionSegment(490, Bezier)
      segments(161) shouldBe CubismMotionSegment(493, Bezier)
      segments(162) shouldBe CubismMotionSegment(496, Bezier)
      segments(163) shouldBe CubismMotionSegment(499, Bezier)
      segments(164) shouldBe CubismMotionSegment(503, Bezier)
      segments(165) shouldBe CubismMotionSegment(506, Bezier)
      segments(166) shouldBe CubismMotionSegment(509, Bezier)
      segments(167) shouldBe CubismMotionSegment(512, Bezier)
      segments(168) shouldBe CubismMotionSegment(515, Bezier)
      segments(169) shouldBe CubismMotionSegment(518, Bezier)
      segments(170) shouldBe CubismMotionSegment(521, Bezier)
      segments(171) shouldBe CubismMotionSegment(524, Bezier)
      segments(172) shouldBe CubismMotionSegment(527, Bezier)
      segments(173) shouldBe CubismMotionSegment(530, Bezier)
      segments(174) shouldBe CubismMotionSegment(533, Bezier)
      segments(175) shouldBe CubismMotionSegment(536, Bezier)
      segments(176) shouldBe CubismMotionSegment(539, Bezier)
      segments(177) shouldBe CubismMotionSegment(542, Bezier)
      segments(178) shouldBe CubismMotionSegment(545, Bezier)
      segments(179) shouldBe CubismMotionSegment(548, Bezier)
      segments(180) shouldBe CubismMotionSegment(551, Bezier)
      segments(181) shouldBe CubismMotionSegment(554, Bezier)
      segments(182) shouldBe CubismMotionSegment(557, Bezier)
      segments(183) shouldBe CubismMotionSegment(560, Bezier)
      segments(184) shouldBe CubismMotionSegment(563, Bezier)
      segments(185) shouldBe CubismMotionSegment(566, Bezier)
      segments(186) shouldBe CubismMotionSegment(569, Bezier)
      segments(187) shouldBe CubismMotionSegment(572, Bezier)
      segments(188) shouldBe CubismMotionSegment(575, Bezier)
      segments(189) shouldBe CubismMotionSegment(578, Bezier)
      segments(190) shouldBe CubismMotionSegment(581, Bezier)
      segments(191) shouldBe CubismMotionSegment(584, Bezier)
      segments(192) shouldBe CubismMotionSegment(587, Bezier)
      segments(193) shouldBe CubismMotionSegment(590, Bezier)
      segments(194) shouldBe CubismMotionSegment(593, Bezier)
      segments(195) shouldBe CubismMotionSegment(596, Bezier)
      segments(196) shouldBe CubismMotionSegment(600, Bezier)
      segments(197) shouldBe CubismMotionSegment(603, Bezier)
      segments(198) shouldBe CubismMotionSegment(606, Bezier)
      segments(199) shouldBe CubismMotionSegment(609, Bezier)
      segments(200) shouldBe CubismMotionSegment(612, Bezier)
      segments(201) shouldBe CubismMotionSegment(615, Bezier)
      segments(202) shouldBe CubismMotionSegment(618, Bezier)
      segments(203) shouldBe CubismMotionSegment(621, Bezier)
      segments(204) shouldBe CubismMotionSegment(624, Bezier)
      segments(205) shouldBe CubismMotionSegment(627, Bezier)
      segments(206) shouldBe CubismMotionSegment(630, Bezier)
      segments(207) shouldBe CubismMotionSegment(633, Bezier)
      segments(208) shouldBe CubismMotionSegment(636, Bezier)
      segments(209) shouldBe CubismMotionSegment(639, Bezier)
      segments(210) shouldBe CubismMotionSegment(642, Bezier)
      segments(211) shouldBe CubismMotionSegment(645, Bezier)
      segments(212) shouldBe CubismMotionSegment(649, Bezier)
      segments(213) shouldBe CubismMotionSegment(652, Bezier)
      segments(214) shouldBe CubismMotionSegment(655, Bezier)
      segments(215) shouldBe CubismMotionSegment(658, Bezier)
      segments(216) shouldBe CubismMotionSegment(661, Bezier)
      segments(217) shouldBe CubismMotionSegment(664, Bezier)
      segments(218) shouldBe CubismMotionSegment(667, Bezier)
      segments(219) shouldBe CubismMotionSegment(670, Bezier)
      segments(220) shouldBe CubismMotionSegment(674, Bezier)
      segments(221) shouldBe CubismMotionSegment(677, Bezier)
      segments(222) shouldBe CubismMotionSegment(680, Bezier)
      segments(223) shouldBe CubismMotionSegment(683, Bezier)
      segments(224) shouldBe CubismMotionSegment(686, Bezier)
      segments(225) shouldBe CubismMotionSegment(689, Bezier)
      segments(226) shouldBe CubismMotionSegment(692, Bezier)
      segments(227) shouldBe CubismMotionSegment(695, Bezier)
      segments(228) shouldBe CubismMotionSegment(699, Bezier)
      segments(229) shouldBe CubismMotionSegment(702, Bezier)
      segments(230) shouldBe CubismMotionSegment(705, Bezier)
      segments(231) shouldBe CubismMotionSegment(708, Bezier)
      segments(232) shouldBe CubismMotionSegment(711, Bezier)
      segments(233) shouldBe CubismMotionSegment(714, Bezier)
      segments(234) shouldBe CubismMotionSegment(717, Bezier)
      segments(235) shouldBe CubismMotionSegment(720, Bezier)
      segments(236) shouldBe CubismMotionSegment(724, Bezier)
      segments(237) shouldBe CubismMotionSegment(727, Bezier)
      segments(238) shouldBe CubismMotionSegment(730, Bezier)
      segments(239) shouldBe CubismMotionSegment(733, Bezier)
      segments(240) shouldBe CubismMotionSegment(736, Bezier)
      segments(241) shouldBe CubismMotionSegment(739, Bezier)
      segments(242) shouldBe CubismMotionSegment(742, Bezier)
      segments(243) shouldBe CubismMotionSegment(745, Bezier)
      segments(244) shouldBe CubismMotionSegment(749, Linear)
      segments(245) shouldBe CubismMotionSegment(751, Linear)
      segments(246) shouldBe CubismMotionSegment(753, Linear)
      segments(247) shouldBe CubismMotionSegment(755, Linear)
      segments(248) shouldBe CubismMotionSegment(757, Linear)
      segments(249) shouldBe CubismMotionSegment(759, Linear)
      segments(250) shouldBe CubismMotionSegment(761, Linear)
      segments(251) shouldBe CubismMotionSegment(763, Linear)
      segments(252) shouldBe CubismMotionSegment(765, Linear)
      segments(253) shouldBe CubismMotionSegment(767, Linear)
      segments(254) shouldBe CubismMotionSegment(769, Linear)
      segments(255) shouldBe CubismMotionSegment(771, Linear)
      segments(256) shouldBe CubismMotionSegment(773, Linear)
      segments(257) shouldBe CubismMotionSegment(775, Linear)
      segments(258) shouldBe CubismMotionSegment(777, Linear)
      segments(259) shouldBe CubismMotionSegment(779, Linear)

      assertPointList("src/test/resources/expectation/markMotionIdle1Points.csv", motionData.pointsList)
    }

    Scenario("Load motion idle[3] from avatar Mark") {
      Given("A folder path contains json files for a Live2D avatar model")
      val folderPath = "src/test/resources/models/Mark"

      When("Create a MotionData from this Live2D avatar settings")
      val jsonSettingsReader = new JsonSettingsReader(folderPath)
      val settings: Settings = jsonSettingsReader.loadSettings().success.value
      val motionData = CubismMotionData.apply(settings.motionGroups("idle")(3))

      motionData.fps shouldBe 30.0
      motionData.isLoop shouldBe true
      motionData.curveCount shouldBe 37
      motionData.duration shouldBe 4.833f

      val curves = motionData.curvesList
      curves.size shouldBe 37
      curves(0) shouldBe CubismMotionCurve("Opacity", Model, 2, 0, -1.0f, -1.0f)
      curves(1) shouldBe CubismMotionCurve("EyeBlink", Model, 5, 2, -1.0f, -1.0f)
      curves(2) shouldBe CubismMotionCurve("ParamAngleX", Parameter, 11, 7, -1.0f, -1.0f)
      curves(3) shouldBe CubismMotionCurve("ParamAngleY", Parameter, 9, 18, -1.0f, -1.0f)
      curves(4) shouldBe CubismMotionCurve("ParamAngleZ", Parameter, 13, 27, -1.0f, -1.0f)
      curves(5) shouldBe CubismMotionCurve("ParamEyeBallX", Parameter, 11, 40, -1.0f, -1.0f)
      curves(6) shouldBe CubismMotionCurve("ParamEyeBallY", Parameter, 11, 51, -1.0f, -1.0f)
      curves(7) shouldBe CubismMotionCurve("ParamBrowLY", Parameter, 9, 62, -1.0f, -1.0f)
      curves(8) shouldBe CubismMotionCurve("ParamBrowRY", Parameter, 9, 71, -1.0f, -1.0f)
      curves(9) shouldBe CubismMotionCurve("ParamMouthOpenY", Parameter, 8, 80, -1.0f, -1.0f)
      curves(10) shouldBe CubismMotionCurve("ParamArmL", Parameter, 13, 88, -1.0f, -1.0f)
      curves(11) shouldBe CubismMotionCurve("ParamArmR", Parameter, 13, 101, -1.0f, -1.0f)
      curves(12) shouldBe CubismMotionCurve("ParamLeftLeg", Parameter, 8, 114, -1.0f, -1.0f)
      curves(13) shouldBe CubismMotionCurve("ParamRightLeg", Parameter, 8, 122, -1.0f, -1.0f)
      curves(14) shouldBe CubismMotionCurve("ParamBodyAngleX", Parameter, 11, 130, -1.0f, -1.0f)
      curves(15) shouldBe CubismMotionCurve("ParamBodyAngleY", Parameter, 10, 141, -1.0f, -1.0f)
      curves(16) shouldBe CubismMotionCurve("ParamBodyAngleZ", Parameter, 9, 151, -1.0f, -1.0f)
      curves(17) shouldBe CubismMotionCurve("ParamBreath", Parameter, 8, 160, -1.0f, -1.0f)
      curves(18) shouldBe CubismMotionCurve("ParamHairFront", Parameter, 8, 168, -1.0f, -1.0f)
      curves(19) shouldBe CubismMotionCurve("ParamHairSide", Parameter, 8, 176, -1.0f, -1.0f)
      curves(20) shouldBe CubismMotionCurve("ParamHairBack", Parameter, 8, 184, -1.0f, -1.0f)
      curves(21) shouldBe CubismMotionCurve("PartHead", PartOpacity, 2, 192, -1.0f, -1.0f)
      curves(22) shouldBe CubismMotionCurve("PartHairFront", PartOpacity, 2, 194, -1.0f, -1.0f)
      curves(23) shouldBe CubismMotionCurve("PartEyeL", PartOpacity, 2, 196, -1.0f, -1.0f)
      curves(24) shouldBe CubismMotionCurve("PartEyeBallL", PartOpacity, 2, 198, -1.0f, -1.0f)
      curves(25) shouldBe CubismMotionCurve("PartEyeWhiteL", PartOpacity, 2, 200, -1.0f, -1.0f)
      curves(26) shouldBe CubismMotionCurve("PartEyeR", PartOpacity, 2, 202, -1.0f, -1.0f)
      curves(27) shouldBe CubismMotionCurve("PartEyeBallR", PartOpacity, 2, 204, -1.0f, -1.0f)
      curves(28) shouldBe CubismMotionCurve("PartEyeWhiteR", PartOpacity, 2, 206, -1.0f, -1.0f)
      curves(29) shouldBe CubismMotionCurve("PartHairSide", PartOpacity, 2, 208, -1.0f, -1.0f)
      curves(30) shouldBe CubismMotionCurve("PartMouth", PartOpacity, 2, 210, -1.0f, -1.0f)
      curves(31) shouldBe CubismMotionCurve("PartOral", PartOpacity, 2, 212, -1.0f, -1.0f)
      curves(32) shouldBe CubismMotionCurve("PartFace", PartOpacity, 2, 214, -1.0f, -1.0f)
      curves(33) shouldBe CubismMotionCurve("PartBody", PartOpacity, 2, 216, -1.0f, -1.0f)
      curves(34) shouldBe CubismMotionCurve("PartArmL", PartOpacity, 2, 218, -1.0f, -1.0f)
      curves(35) shouldBe CubismMotionCurve("PartArmR", PartOpacity, 2, 220, -1.0f, -1.0f)
      curves(36) shouldBe CubismMotionCurve("PartHairBack", PartOpacity, 2, 222, -1.0f, -1.0f)

      val segments = motionData.segmentsList
      segments.size shouldBe 224
      segments(0) shouldBe CubismMotionSegment(0, Bezier)
      segments(1) shouldBe CubismMotionSegment(3, Linear)
      segments(2) shouldBe CubismMotionSegment(5, Bezier)
      segments(3) shouldBe CubismMotionSegment(8, Bezier)
      segments(4) shouldBe CubismMotionSegment(11, Bezier)
      segments(5) shouldBe CubismMotionSegment(14, Bezier)
      segments(6) shouldBe CubismMotionSegment(17, Linear)
      segments(7) shouldBe CubismMotionSegment(19, Bezier)
      segments(8) shouldBe CubismMotionSegment(22, Bezier)
      segments(9) shouldBe CubismMotionSegment(25, Bezier)
      segments(10) shouldBe CubismMotionSegment(28, Bezier)
      segments(11) shouldBe CubismMotionSegment(31, Bezier)
      segments(12) shouldBe CubismMotionSegment(34, Bezier)
      segments(13) shouldBe CubismMotionSegment(37, Bezier)
      segments(14) shouldBe CubismMotionSegment(40, Bezier)
      segments(15) shouldBe CubismMotionSegment(43, Bezier)
      segments(16) shouldBe CubismMotionSegment(46, Bezier)
      segments(17) shouldBe CubismMotionSegment(49, Linear)
      segments(18) shouldBe CubismMotionSegment(51, Bezier)
      segments(19) shouldBe CubismMotionSegment(54, Bezier)
      segments(20) shouldBe CubismMotionSegment(57, Bezier)
      segments(21) shouldBe CubismMotionSegment(60, Bezier)
      segments(22) shouldBe CubismMotionSegment(63, Bezier)
      segments(23) shouldBe CubismMotionSegment(66, Bezier)
      segments(24) shouldBe CubismMotionSegment(69, Bezier)
      segments(25) shouldBe CubismMotionSegment(72, Bezier)
      segments(26) shouldBe CubismMotionSegment(75, Linear)
      segments(27) shouldBe CubismMotionSegment(77, Bezier)
      segments(28) shouldBe CubismMotionSegment(80, Bezier)
      segments(29) shouldBe CubismMotionSegment(83, Bezier)
      segments(30) shouldBe CubismMotionSegment(86, Bezier)
      segments(31) shouldBe CubismMotionSegment(89, Bezier)
      segments(32) shouldBe CubismMotionSegment(92, Bezier)
      segments(33) shouldBe CubismMotionSegment(95, Bezier)
      segments(34) shouldBe CubismMotionSegment(98, Bezier)
      segments(35) shouldBe CubismMotionSegment(101, Bezier)
      segments(36) shouldBe CubismMotionSegment(104, Bezier)
      segments(37) shouldBe CubismMotionSegment(107, Bezier)
      segments(38) shouldBe CubismMotionSegment(110, Bezier)
      segments(39) shouldBe CubismMotionSegment(113, Linear)
      segments(40) shouldBe CubismMotionSegment(115, Bezier)
      segments(41) shouldBe CubismMotionSegment(118, Bezier)
      segments(42) shouldBe CubismMotionSegment(121, Bezier)
      segments(43) shouldBe CubismMotionSegment(124, Bezier)
      segments(44) shouldBe CubismMotionSegment(127, Bezier)
      segments(45) shouldBe CubismMotionSegment(130, Bezier)
      segments(46) shouldBe CubismMotionSegment(133, Bezier)
      segments(47) shouldBe CubismMotionSegment(136, Bezier)
      segments(48) shouldBe CubismMotionSegment(139, Bezier)
      segments(49) shouldBe CubismMotionSegment(142, Bezier)
      segments(50) shouldBe CubismMotionSegment(145, Linear)
      segments(51) shouldBe CubismMotionSegment(147, Bezier)
      segments(52) shouldBe CubismMotionSegment(150, Bezier)
      segments(53) shouldBe CubismMotionSegment(153, Bezier)
      segments(54) shouldBe CubismMotionSegment(156, Bezier)
      segments(55) shouldBe CubismMotionSegment(159, Bezier)
      segments(56) shouldBe CubismMotionSegment(162, Bezier)
      segments(57) shouldBe CubismMotionSegment(165, Bezier)
      segments(58) shouldBe CubismMotionSegment(168, Bezier)
      segments(59) shouldBe CubismMotionSegment(171, Bezier)
      segments(60) shouldBe CubismMotionSegment(174, Bezier)
      segments(61) shouldBe CubismMotionSegment(177, Linear)
      segments(62) shouldBe CubismMotionSegment(179, Bezier)
      segments(63) shouldBe CubismMotionSegment(182, Bezier)
      segments(64) shouldBe CubismMotionSegment(185, Bezier)
      segments(65) shouldBe CubismMotionSegment(188, Bezier)
      segments(66) shouldBe CubismMotionSegment(191, Bezier)
      segments(67) shouldBe CubismMotionSegment(194, Bezier)
      segments(68) shouldBe CubismMotionSegment(197, Bezier)
      segments(69) shouldBe CubismMotionSegment(200, Bezier)
      segments(70) shouldBe CubismMotionSegment(203, Linear)
      segments(71) shouldBe CubismMotionSegment(205, Bezier)
      segments(72) shouldBe CubismMotionSegment(208, Bezier)
      segments(73) shouldBe CubismMotionSegment(211, Bezier)
      segments(74) shouldBe CubismMotionSegment(214, Bezier)
      segments(75) shouldBe CubismMotionSegment(217, Bezier)
      segments(76) shouldBe CubismMotionSegment(220, Bezier)
      segments(77) shouldBe CubismMotionSegment(223, Bezier)
      segments(78) shouldBe CubismMotionSegment(226, Bezier)
      segments(79) shouldBe CubismMotionSegment(229, Linear)
      segments(80) shouldBe CubismMotionSegment(231, Bezier)
      segments(81) shouldBe CubismMotionSegment(234, Bezier)
      segments(82) shouldBe CubismMotionSegment(237, Bezier)
      segments(83) shouldBe CubismMotionSegment(240, Bezier)
      segments(84) shouldBe CubismMotionSegment(243, Bezier)
      segments(85) shouldBe CubismMotionSegment(246, Bezier)
      segments(86) shouldBe CubismMotionSegment(249, Bezier)
      segments(87) shouldBe CubismMotionSegment(252, Linear)
      segments(88) shouldBe CubismMotionSegment(254, Bezier)
      segments(89) shouldBe CubismMotionSegment(257, Bezier)
      segments(90) shouldBe CubismMotionSegment(260, Bezier)
      segments(91) shouldBe CubismMotionSegment(263, Bezier)
      segments(92) shouldBe CubismMotionSegment(266, Bezier)
      segments(93) shouldBe CubismMotionSegment(269, Bezier)
      segments(94) shouldBe CubismMotionSegment(272, Bezier)
      segments(95) shouldBe CubismMotionSegment(275, Bezier)
      segments(96) shouldBe CubismMotionSegment(278, Bezier)
      segments(97) shouldBe CubismMotionSegment(281, Bezier)
      segments(98) shouldBe CubismMotionSegment(284, Bezier)
      segments(99) shouldBe CubismMotionSegment(287, Bezier)
      segments(100) shouldBe CubismMotionSegment(290, Linear)
      segments(101) shouldBe CubismMotionSegment(292, Bezier)
      segments(102) shouldBe CubismMotionSegment(295, Bezier)
      segments(103) shouldBe CubismMotionSegment(298, Bezier)
      segments(104) shouldBe CubismMotionSegment(301, Bezier)
      segments(105) shouldBe CubismMotionSegment(304, Bezier)
      segments(106) shouldBe CubismMotionSegment(307, Bezier)
      segments(107) shouldBe CubismMotionSegment(310, Bezier)
      segments(108) shouldBe CubismMotionSegment(313, Bezier)
      segments(109) shouldBe CubismMotionSegment(316, Bezier)
      segments(110) shouldBe CubismMotionSegment(319, Bezier)
      segments(111) shouldBe CubismMotionSegment(322, Bezier)
      segments(112) shouldBe CubismMotionSegment(325, Bezier)
      segments(113) shouldBe CubismMotionSegment(328, Linear)
      segments(114) shouldBe CubismMotionSegment(330, Bezier)
      segments(115) shouldBe CubismMotionSegment(333, Bezier)
      segments(116) shouldBe CubismMotionSegment(336, Bezier)
      segments(117) shouldBe CubismMotionSegment(339, Bezier)
      segments(118) shouldBe CubismMotionSegment(342, Bezier)
      segments(119) shouldBe CubismMotionSegment(345, Bezier)
      segments(120) shouldBe CubismMotionSegment(348, Bezier)
      segments(121) shouldBe CubismMotionSegment(351, Linear)
      segments(122) shouldBe CubismMotionSegment(353, Bezier)
      segments(123) shouldBe CubismMotionSegment(356, Bezier)
      segments(124) shouldBe CubismMotionSegment(359, Bezier)
      segments(125) shouldBe CubismMotionSegment(362, Bezier)
      segments(126) shouldBe CubismMotionSegment(365, Bezier)
      segments(127) shouldBe CubismMotionSegment(368, Bezier)
      segments(128) shouldBe CubismMotionSegment(371, Bezier)
      segments(129) shouldBe CubismMotionSegment(374, Linear)
      segments(130) shouldBe CubismMotionSegment(376, Bezier)
      segments(131) shouldBe CubismMotionSegment(379, Bezier)
      segments(132) shouldBe CubismMotionSegment(382, Bezier)
      segments(133) shouldBe CubismMotionSegment(385, Bezier)
      segments(134) shouldBe CubismMotionSegment(388, Bezier)
      segments(135) shouldBe CubismMotionSegment(391, Bezier)
      segments(136) shouldBe CubismMotionSegment(394, Bezier)
      segments(137) shouldBe CubismMotionSegment(397, Bezier)
      segments(138) shouldBe CubismMotionSegment(400, Bezier)
      segments(139) shouldBe CubismMotionSegment(403, Bezier)
      segments(140) shouldBe CubismMotionSegment(406, Linear)
      segments(141) shouldBe CubismMotionSegment(408, Bezier)
      segments(142) shouldBe CubismMotionSegment(411, Bezier)
      segments(143) shouldBe CubismMotionSegment(414, Bezier)
      segments(144) shouldBe CubismMotionSegment(417, Bezier)
      segments(145) shouldBe CubismMotionSegment(420, Bezier)
      segments(146) shouldBe CubismMotionSegment(423, Bezier)
      segments(147) shouldBe CubismMotionSegment(426, Bezier)
      segments(148) shouldBe CubismMotionSegment(429, Bezier)
      segments(149) shouldBe CubismMotionSegment(432, Bezier)
      segments(150) shouldBe CubismMotionSegment(435, Linear)
      segments(151) shouldBe CubismMotionSegment(437, Linear)
      segments(152) shouldBe CubismMotionSegment(438, Bezier)
      segments(153) shouldBe CubismMotionSegment(441, Bezier)
      segments(154) shouldBe CubismMotionSegment(444, Bezier)
      segments(155) shouldBe CubismMotionSegment(447, Bezier)
      segments(156) shouldBe CubismMotionSegment(450, Bezier)
      segments(157) shouldBe CubismMotionSegment(453, Bezier)
      segments(158) shouldBe CubismMotionSegment(456, Bezier)
      segments(159) shouldBe CubismMotionSegment(459, Linear)
      segments(160) shouldBe CubismMotionSegment(461, Bezier)
      segments(161) shouldBe CubismMotionSegment(464, Bezier)
      segments(162) shouldBe CubismMotionSegment(467, Bezier)
      segments(163) shouldBe CubismMotionSegment(470, Bezier)
      segments(164) shouldBe CubismMotionSegment(473, Bezier)
      segments(165) shouldBe CubismMotionSegment(476, Bezier)
      segments(166) shouldBe CubismMotionSegment(479, Bezier)
      segments(167) shouldBe CubismMotionSegment(482, Linear)
      segments(168) shouldBe CubismMotionSegment(484, Bezier)
      segments(169) shouldBe CubismMotionSegment(487, Bezier)
      segments(170) shouldBe CubismMotionSegment(490, Bezier)
      segments(171) shouldBe CubismMotionSegment(493, Bezier)
      segments(172) shouldBe CubismMotionSegment(496, Bezier)
      segments(173) shouldBe CubismMotionSegment(499, Bezier)
      segments(174) shouldBe CubismMotionSegment(502, Bezier)
      segments(175) shouldBe CubismMotionSegment(505, Linear)
      segments(176) shouldBe CubismMotionSegment(507, Bezier)
      segments(177) shouldBe CubismMotionSegment(510, Bezier)
      segments(178) shouldBe CubismMotionSegment(513, Bezier)
      segments(179) shouldBe CubismMotionSegment(516, Bezier)
      segments(180) shouldBe CubismMotionSegment(519, Bezier)
      segments(181) shouldBe CubismMotionSegment(522, Bezier)
      segments(182) shouldBe CubismMotionSegment(525, Bezier)
      segments(183) shouldBe CubismMotionSegment(528, Linear)
      segments(184) shouldBe CubismMotionSegment(530, Bezier)
      segments(185) shouldBe CubismMotionSegment(533, Bezier)
      segments(186) shouldBe CubismMotionSegment(536, Bezier)
      segments(187) shouldBe CubismMotionSegment(539, Bezier)
      segments(188) shouldBe CubismMotionSegment(542, Bezier)
      segments(189) shouldBe CubismMotionSegment(545, Bezier)
      segments(190) shouldBe CubismMotionSegment(548, Bezier)
      segments(191) shouldBe CubismMotionSegment(551, Linear)
      segments(192) shouldBe CubismMotionSegment(553, InverseStepped)
      segments(193) shouldBe CubismMotionSegment(554, Linear)
      segments(194) shouldBe CubismMotionSegment(556, Stepped)
      segments(195) shouldBe CubismMotionSegment(557, Linear)
      segments(196) shouldBe CubismMotionSegment(559, Stepped)
      segments(197) shouldBe CubismMotionSegment(560, Linear)
      segments(198) shouldBe CubismMotionSegment(562, Stepped)
      segments(199) shouldBe CubismMotionSegment(563, Linear)
      segments(200) shouldBe CubismMotionSegment(565, Stepped)
      segments(201) shouldBe CubismMotionSegment(566, Linear)
      segments(202) shouldBe CubismMotionSegment(568, Stepped)
      segments(203) shouldBe CubismMotionSegment(569, Linear)
      segments(204) shouldBe CubismMotionSegment(571, Stepped)
      segments(205) shouldBe CubismMotionSegment(572, Linear)
      segments(206) shouldBe CubismMotionSegment(574, Stepped)
      segments(207) shouldBe CubismMotionSegment(575, Linear)
      segments(208) shouldBe CubismMotionSegment(577, Stepped)
      segments(209) shouldBe CubismMotionSegment(578, Linear)
      segments(210) shouldBe CubismMotionSegment(580, Stepped)
      segments(211) shouldBe CubismMotionSegment(581, Linear)
      segments(212) shouldBe CubismMotionSegment(583, Stepped)
      segments(213) shouldBe CubismMotionSegment(584, Linear)
      segments(214) shouldBe CubismMotionSegment(586, Stepped)
      segments(215) shouldBe CubismMotionSegment(587, Linear)
      segments(216) shouldBe CubismMotionSegment(589, Stepped)
      segments(217) shouldBe CubismMotionSegment(590, Linear)
      segments(218) shouldBe CubismMotionSegment(592, Stepped)
      segments(219) shouldBe CubismMotionSegment(593, Linear)
      segments(220) shouldBe CubismMotionSegment(595, Stepped)
      segments(221) shouldBe CubismMotionSegment(596, Linear)
      segments(222) shouldBe CubismMotionSegment(598, Stepped)
      segments(223) shouldBe CubismMotionSegment(599, Linear)

      assertPointList("src/test/resources/expectation/markMotionIdle3Points.csv", motionData.pointsList)
    }

    Scenario("Load motion from avatar Hiyori") {
      Given("A folder path contains json files for a Live2D avatar model")
      val folderPath = "src/test/resources/models/Hiyori"

      When("Create a MotionData from this Live2D avatar settings")
      val jsonSettingsReader = new JsonSettingsReader(folderPath)
      val settings: Settings = jsonSettingsReader.loadSettings().success.value
      val motionData = CubismMotionData.apply(settings.motionGroups("idle")(0))

      motionData.fps shouldBe 30.0
      motionData.isLoop shouldBe true
      motionData.curveCount shouldBe 31
      motionData.duration shouldBe 4.7f

      val curves = motionData.curvesList
      curves.size shouldBe 31
      curves(0) shouldBe CubismMotionCurve("ParamAngleX", Parameter, 10, 0, 0.2f, -1.0f)
      curves(1) shouldBe CubismMotionCurve("ParamAngleY", Parameter, 12, 10, -1.0f, 0.3f)
      curves(2) shouldBe CubismMotionCurve("ParamAngleZ", Parameter, 9, 22, 0.4f, 0.5f)
      curves(3) shouldBe CubismMotionCurve("ParamCheek", Parameter, 1, 31, -1.0f, -1.0f)
      curves(4) shouldBe CubismMotionCurve("ParamEyeLOpen", Parameter, 9, 32, -1.0f, -1.0f)
      curves(5) shouldBe CubismMotionCurve("ParamEyeLSmile", Parameter, 1, 41, -1.0f, -1.0f)
      curves(6) shouldBe CubismMotionCurve("ParamEyeROpen", Parameter, 9, 42, -1.0f, -1.0f)
      curves(7) shouldBe CubismMotionCurve("ParamEyeRSmile", Parameter, 1, 51, -1.0f, -1.0f)
      curves(8) shouldBe CubismMotionCurve("ParamEyeBallX", Parameter, 7, 52, -1.0f, -1.0f)
      curves(9) shouldBe CubismMotionCurve("ParamEyeBallY", Parameter, 7, 59, -1.0f, -1.0f)
      curves(10) shouldBe CubismMotionCurve("ParamBrowLY", Parameter, 1, 66, -1.0f, -1.0f)
      curves(11) shouldBe CubismMotionCurve("ParamBrowRY", Parameter, 1, 67, -1.0f, -1.0f)
      curves(12) shouldBe CubismMotionCurve("ParamBrowLX", Parameter, 1, 68, -1.0f, -1.0f)
      curves(13) shouldBe CubismMotionCurve("ParamBrowRX", Parameter, 1, 69, -1.0f, -1.0f)
      curves(14) shouldBe CubismMotionCurve("ParamBrowLAngle", Parameter, 1, 70, -1.0f, -1.0f)
      curves(15) shouldBe CubismMotionCurve("ParamBrowRAngle", Parameter, 1, 71, -1.0f, -1.0f)
      curves(16) shouldBe CubismMotionCurve("ParamBrowLForm", Parameter, 1, 72, -1.0f, -1.0f)
      curves(17) shouldBe CubismMotionCurve("ParamBrowRForm", Parameter, 1, 73, -1.0f, -1.0f)
      curves(18) shouldBe CubismMotionCurve("ParamMouthForm", Parameter, 1, 74, -1.0f, -1.0f)
      curves(19) shouldBe CubismMotionCurve("ParamMouthOpenY", Parameter, 1, 75, -1.0f, -1.0f)
      curves(20) shouldBe CubismMotionCurve("ParamBodyAngleX", Parameter, 4, 76, -1.0f, -1.0f)
      curves(21) shouldBe CubismMotionCurve("ParamBodyAngleY", Parameter, 12, 80, -1.0f, -1.0f)
      curves(22) shouldBe CubismMotionCurve("ParamBodyAngleZ", Parameter, 5, 92, -1.0f, -1.0f)
      curves(23) shouldBe CubismMotionCurve("ParamBreath", Parameter, 1, 97, -1.0f, -1.0f)
      curves(24) shouldBe CubismMotionCurve("ParamShoulder", Parameter, 6, 98, -1.0f, -1.0f)
      curves(25) shouldBe CubismMotionCurve("ParamLeg", Parameter, 1, 104, -1.0f, -1.0f)
      curves(26) shouldBe CubismMotionCurve("ParamArmLA", Parameter, 8, 105, -1.0f, -1.0f)
      curves(27) shouldBe CubismMotionCurve("ParamArmRA", Parameter, 8, 113, -1.0f, -1.0f)
      curves(28) shouldBe CubismMotionCurve("ParamHairAhoge", Parameter, 12, 121, -1.0f, -1.0f)
      curves(29) shouldBe CubismMotionCurve("PartArmA", PartOpacity, 1, 133, -1.0f, -1.0f)
      curves(30) shouldBe CubismMotionCurve("PartArmB", PartOpacity, 0, 134, -1.0f, -1.0f)

      val segments = motionData.segmentsList
      segments.size shouldBe 134
      segments(0) shouldBe CubismMotionSegment(0, BezierCardanoInterpretation)
      segments(1) shouldBe CubismMotionSegment(3, BezierCardanoInterpretation)
      segments(2) shouldBe CubismMotionSegment(6, BezierCardanoInterpretation)
      segments(3) shouldBe CubismMotionSegment(9, BezierCardanoInterpretation)
      segments(4) shouldBe CubismMotionSegment(12, BezierCardanoInterpretation)
      segments(5) shouldBe CubismMotionSegment(15, BezierCardanoInterpretation)
      segments(6) shouldBe CubismMotionSegment(18, BezierCardanoInterpretation)
      segments(7) shouldBe CubismMotionSegment(21, BezierCardanoInterpretation)
      segments(8) shouldBe CubismMotionSegment(24, BezierCardanoInterpretation)
      segments(9) shouldBe CubismMotionSegment(27, Linear)
      segments(10) shouldBe CubismMotionSegment(29, BezierCardanoInterpretation)
      segments(11) shouldBe CubismMotionSegment(32, BezierCardanoInterpretation)
      segments(12) shouldBe CubismMotionSegment(35, BezierCardanoInterpretation)
      segments(13) shouldBe CubismMotionSegment(38, BezierCardanoInterpretation)
      segments(14) shouldBe CubismMotionSegment(41, BezierCardanoInterpretation)
      segments(15) shouldBe CubismMotionSegment(44, BezierCardanoInterpretation)
      segments(16) shouldBe CubismMotionSegment(47, BezierCardanoInterpretation)
      segments(17) shouldBe CubismMotionSegment(50, BezierCardanoInterpretation)
      segments(18) shouldBe CubismMotionSegment(53, BezierCardanoInterpretation)
      segments(19) shouldBe CubismMotionSegment(56, BezierCardanoInterpretation)
      segments(20) shouldBe CubismMotionSegment(59, BezierCardanoInterpretation)
      segments(21) shouldBe CubismMotionSegment(62, Linear)
      segments(22) shouldBe CubismMotionSegment(64, BezierCardanoInterpretation)
      segments(23) shouldBe CubismMotionSegment(67, BezierCardanoInterpretation)
      segments(24) shouldBe CubismMotionSegment(70, BezierCardanoInterpretation)
      segments(25) shouldBe CubismMotionSegment(73, BezierCardanoInterpretation)
      segments(26) shouldBe CubismMotionSegment(76, BezierCardanoInterpretation)
      segments(27) shouldBe CubismMotionSegment(79, BezierCardanoInterpretation)
      segments(28) shouldBe CubismMotionSegment(82, BezierCardanoInterpretation)
      segments(29) shouldBe CubismMotionSegment(85, BezierCardanoInterpretation)
      segments(30) shouldBe CubismMotionSegment(88, Linear)
      segments(31) shouldBe CubismMotionSegment(90, Linear)
      segments(32) shouldBe CubismMotionSegment(92, BezierCardanoInterpretation)
      segments(33) shouldBe CubismMotionSegment(95, BezierCardanoInterpretation)
      segments(34) shouldBe CubismMotionSegment(98, BezierCardanoInterpretation)
      segments(35) shouldBe CubismMotionSegment(101, BezierCardanoInterpretation)
      segments(36) shouldBe CubismMotionSegment(104, BezierCardanoInterpretation)
      segments(37) shouldBe CubismMotionSegment(107, BezierCardanoInterpretation)
      segments(38) shouldBe CubismMotionSegment(110, BezierCardanoInterpretation)
      segments(39) shouldBe CubismMotionSegment(113, BezierCardanoInterpretation)
      segments(40) shouldBe CubismMotionSegment(116, Linear)
      segments(41) shouldBe CubismMotionSegment(118, Linear)
      segments(42) shouldBe CubismMotionSegment(120, BezierCardanoInterpretation)
      segments(43) shouldBe CubismMotionSegment(123, BezierCardanoInterpretation)
      segments(44) shouldBe CubismMotionSegment(126, BezierCardanoInterpretation)
      segments(45) shouldBe CubismMotionSegment(129, BezierCardanoInterpretation)
      segments(46) shouldBe CubismMotionSegment(132, BezierCardanoInterpretation)
      segments(47) shouldBe CubismMotionSegment(135, BezierCardanoInterpretation)
      segments(48) shouldBe CubismMotionSegment(138, BezierCardanoInterpretation)
      segments(49) shouldBe CubismMotionSegment(141, BezierCardanoInterpretation)
      segments(50) shouldBe CubismMotionSegment(144, Linear)
      segments(51) shouldBe CubismMotionSegment(146, Linear)
      segments(52) shouldBe CubismMotionSegment(148, BezierCardanoInterpretation)
      segments(53) shouldBe CubismMotionSegment(151, BezierCardanoInterpretation)
      segments(54) shouldBe CubismMotionSegment(154, BezierCardanoInterpretation)
      segments(55) shouldBe CubismMotionSegment(157, BezierCardanoInterpretation)
      segments(56) shouldBe CubismMotionSegment(160, BezierCardanoInterpretation)
      segments(57) shouldBe CubismMotionSegment(163, BezierCardanoInterpretation)
      segments(58) shouldBe CubismMotionSegment(166, Linear)
      segments(59) shouldBe CubismMotionSegment(168, BezierCardanoInterpretation)
      segments(60) shouldBe CubismMotionSegment(171, BezierCardanoInterpretation)
      segments(61) shouldBe CubismMotionSegment(174, BezierCardanoInterpretation)
      segments(62) shouldBe CubismMotionSegment(177, BezierCardanoInterpretation)
      segments(63) shouldBe CubismMotionSegment(180, BezierCardanoInterpretation)
      segments(64) shouldBe CubismMotionSegment(183, BezierCardanoInterpretation)
      segments(65) shouldBe CubismMotionSegment(186, Linear)
      segments(66) shouldBe CubismMotionSegment(188, Linear)
      segments(67) shouldBe CubismMotionSegment(190, Linear)
      segments(68) shouldBe CubismMotionSegment(192, Linear)
      segments(69) shouldBe CubismMotionSegment(194, Linear)
      segments(70) shouldBe CubismMotionSegment(196, Linear)
      segments(71) shouldBe CubismMotionSegment(198, Linear)
      segments(72) shouldBe CubismMotionSegment(200, Linear)
      segments(73) shouldBe CubismMotionSegment(202, Linear)
      segments(74) shouldBe CubismMotionSegment(204, Linear)
      segments(75) shouldBe CubismMotionSegment(206, Linear)
      segments(76) shouldBe CubismMotionSegment(208, BezierCardanoInterpretation)
      segments(77) shouldBe CubismMotionSegment(211, BezierCardanoInterpretation)
      segments(78) shouldBe CubismMotionSegment(214, BezierCardanoInterpretation)
      segments(79) shouldBe CubismMotionSegment(217, Linear)
      segments(80) shouldBe CubismMotionSegment(219, BezierCardanoInterpretation)
      segments(81) shouldBe CubismMotionSegment(222, BezierCardanoInterpretation)
      segments(82) shouldBe CubismMotionSegment(225, BezierCardanoInterpretation)
      segments(83) shouldBe CubismMotionSegment(228, BezierCardanoInterpretation)
      segments(84) shouldBe CubismMotionSegment(231, BezierCardanoInterpretation)
      segments(85) shouldBe CubismMotionSegment(234, BezierCardanoInterpretation)
      segments(86) shouldBe CubismMotionSegment(237, BezierCardanoInterpretation)
      segments(87) shouldBe CubismMotionSegment(240, BezierCardanoInterpretation)
      segments(88) shouldBe CubismMotionSegment(243, BezierCardanoInterpretation)
      segments(89) shouldBe CubismMotionSegment(246, BezierCardanoInterpretation)
      segments(90) shouldBe CubismMotionSegment(249, BezierCardanoInterpretation)
      segments(91) shouldBe CubismMotionSegment(252, Linear)
      segments(92) shouldBe CubismMotionSegment(254, BezierCardanoInterpretation)
      segments(93) shouldBe CubismMotionSegment(257, BezierCardanoInterpretation)
      segments(94) shouldBe CubismMotionSegment(260, BezierCardanoInterpretation)
      segments(95) shouldBe CubismMotionSegment(263, BezierCardanoInterpretation)
      segments(96) shouldBe CubismMotionSegment(266, Linear)
      segments(97) shouldBe CubismMotionSegment(268, Linear)
      segments(98) shouldBe CubismMotionSegment(270, BezierCardanoInterpretation)
      segments(99) shouldBe CubismMotionSegment(273, BezierCardanoInterpretation)
      segments(100) shouldBe CubismMotionSegment(276, BezierCardanoInterpretation)
      segments(101) shouldBe CubismMotionSegment(279, BezierCardanoInterpretation)
      segments(102) shouldBe CubismMotionSegment(282, BezierCardanoInterpretation)
      segments(103) shouldBe CubismMotionSegment(285, Linear)
      segments(104) shouldBe CubismMotionSegment(287, Linear)
      segments(105) shouldBe CubismMotionSegment(289, BezierCardanoInterpretation)
      segments(106) shouldBe CubismMotionSegment(292, BezierCardanoInterpretation)
      segments(107) shouldBe CubismMotionSegment(295, BezierCardanoInterpretation)
      segments(108) shouldBe CubismMotionSegment(298, BezierCardanoInterpretation)
      segments(109) shouldBe CubismMotionSegment(301, BezierCardanoInterpretation)
      segments(110) shouldBe CubismMotionSegment(304, BezierCardanoInterpretation)
      segments(111) shouldBe CubismMotionSegment(307, BezierCardanoInterpretation)
      segments(112) shouldBe CubismMotionSegment(310, Linear)
      segments(113) shouldBe CubismMotionSegment(312, BezierCardanoInterpretation)
      segments(114) shouldBe CubismMotionSegment(315, BezierCardanoInterpretation)
      segments(115) shouldBe CubismMotionSegment(318, BezierCardanoInterpretation)
      segments(116) shouldBe CubismMotionSegment(321, BezierCardanoInterpretation)
      segments(117) shouldBe CubismMotionSegment(324, BezierCardanoInterpretation)
      segments(118) shouldBe CubismMotionSegment(327, BezierCardanoInterpretation)
      segments(119) shouldBe CubismMotionSegment(330, BezierCardanoInterpretation)
      segments(120) shouldBe CubismMotionSegment(333, Linear)
      segments(121) shouldBe CubismMotionSegment(335, BezierCardanoInterpretation)
      segments(122) shouldBe CubismMotionSegment(338, BezierCardanoInterpretation)
      segments(123) shouldBe CubismMotionSegment(341, BezierCardanoInterpretation)
      segments(124) shouldBe CubismMotionSegment(344, BezierCardanoInterpretation)
      segments(125) shouldBe CubismMotionSegment(347, BezierCardanoInterpretation)
      segments(126) shouldBe CubismMotionSegment(350, BezierCardanoInterpretation)
      segments(127) shouldBe CubismMotionSegment(353, BezierCardanoInterpretation)
      segments(128) shouldBe CubismMotionSegment(356, BezierCardanoInterpretation)
      segments(129) shouldBe CubismMotionSegment(359, BezierCardanoInterpretation)
      segments(130) shouldBe CubismMotionSegment(362, BezierCardanoInterpretation)
      segments(131) shouldBe CubismMotionSegment(365, BezierCardanoInterpretation)
      segments(132) shouldBe CubismMotionSegment(368, Linear)
      segments(133) shouldBe CubismMotionSegment(370, Linear)

      assertPointList("src/test/resources/expectation/hiyoriMotionIdle0Points.csv", motionData.pointsList)
    }
  }

  private def assertPointList(expectationFile: String, points: List[CubismMotionPoint]): Unit = {
    val source = Source.fromFile(expectationFile)
    val testData = Using.resource(source) { source => source.getLines().toList.drop(1) }
    points.size shouldBe testData.size
    testData.zipWithIndex.foreach { case (line, index) =>
      val Array(time, value) = line.split("\\s+")
      withClue(s"$expectationFile[$index]") {
        points(index) shouldBe CubismMotionPoint(time.toFloat, value.toFloat)
      }
    }
  }
}
