name: Release

on:
  push:
    branches: ["release"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  release:
    name: "Release"
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
      LANG: en_US.utf-8
    container:
      image: debian:sid
    steps:
      - name: "Installing Git"
        run: |
          apt-get -yqq update
          apt-get -yqq install git

      - name: "Checkout Source Code"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: "Prepare Building Envoriment"
        uses: ./.github/actions/prepare-building-envoriment
      
      - name: "Run Unit Test"
        uses: ./.github/actions/run-unit-test

      - name: "Build Release Package"
        uses: ./.github/actions/release-build

      - name: "Update Badges to Git Repository"
        uses: ./.github/actions/update-badge

      - name: "Release to Maven"
        uses: ./.github/actions/upload-to-maven

      - name: "Upload to GitHub Release Page"
        uses: ./.github/actions/upload-to-github-release

      - name: "Push Release Change to Original GitHub Repository"
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
