name: Unit Test

on:
  push:
    branches: develop
  pull_request:
    branches: develop

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  unitTest:
    name: "Unit Test"
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      LANG: en_US.utf-8
    container:
      image: debian:sid
    steps:
      - name: "Installing Git"
        run: |
          apt-get -yqq update
          apt-get -yqq install git

      - name: "Checkout Source Code"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: "Prepare Building Envoriment"
        uses: ./.github/actions/prepare-building-envoriment

      - name: "Run Unit Test"
        uses: ./.github/actions/run-unit-test

