name: Unit Test

on:
  push:
    branches: develop
  pull_request:
    branches: develop

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  unitTest:
    name: "Unit Test"
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      LANG: en_US.utf-8
    container:
      image: debian:sid
    steps:
      - name: "Checkout Source Code"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Prepare Building Env
        uses: ./.github/actions/prepare-building-envoriment

      - name: Unit test
        uses: ./.github/actions/run-unit-test
      - name: Show coverage rate
        run: |
          echo $COVERAGE_RATE

