name: Unit Test

on:
  push:
    branches: develop
  pull_request:
    branches: develop

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  unitTest:
    name: "Unit Test"
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      EXCLUDE_TEST_TAG: moe.brianhsu.AudioOutputTest  
    container:
      image: openjdk:11
    steps:
      - name: "Checkout Source Code"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Unit test
        uses: ./.github/actions/run-unit-test

